language: java
jdk: oraclejdk8
sudo: false
branches:
  only:
  - homolog
services:
- mysql
cache:
  directories:
  - $HOME/.m2
before_install:
- openssl aes-256-cbc -K $encrypted_3df6c6586a65_key -iv $encrypted_3df6c6586a65_iv
  -in $TRAVIS_BUILD_DIR/scripts/travis/deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
- mysql -e 'CREATE DATABASE IF NOT EXISTS xcolab;'
- sh $TRAVIS_BUILD_DIR/scripts/travis/before_script.sh
addons:
  ssh_known_hosts: cognosis.mit.edu
install: true
script:
- sh $TRAVIS_BUILD_DIR/scripts/travis/deploy.sh
after_success:
  - sh $TRAVIS_BUILD_DIR/scripts/travis/after_script.sh
  - ls $TRAVIS_BUILD_DIR/deploy/
deploy:
  - provider: script
    skip_cleanup: true
    script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/deploy travis@cognosis.mit.edu:deploy
    on:
      branch: homolog