language: java
jdk: oraclejdk8
sudo: false

services:
- mysql

cache:
  directories:
  - $HOME/.m2

env:
  - RUN_INTEGRATION_TESTS=true
  - RUN_INTEGRATION_TESTS=false

before_install:
- gem install dpl --source http://rubygems.org
- source scripts/travis/travis_rc.sh
- openssl aes-256-cbc -K $encrypted_3721589d2908_key -iv $encrypted_3721589d2908_iv -in $TRAVIS_BUILD_DIR/scripts/travis/deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
- mysql -e 'CREATE DATABASE IF NOT EXISTS xcolab;'
- scripts/travis/before_script.sh

addons:
  ssh_known_hosts: cognosis.mit.edu

install: true

script:
- scripts/travis/build.sh

after_success:
- scripts/travis/after_script.sh

deploy:
- provider: script
  skip_cleanup: true
  script: scripts/travis/deploy.sh
  on:
    all_branches: true

notifications:
  slack:
    secure: rhro98Ms8yOaxkJ1frjEVdY8H39z3usNsbfdemviJk4iXZ5NMd1f6siCipXmjQc0DQY9wCM26rEpmjxVtF7P71D/jE85g/5LBSTpx03bQjvJQGVHCYl9kzStrJd5OBGWsfcv+NbiYxkjzg7w/xVZX452bmvqISCNbPMhmKcKFU4nbKBE8I28XfBdhpYvrWbAsINUreyJGAq1qfZqNI49yTm2PrFDepPJUugPUthH9QZktfiqbF2a/rOKQWk8ssRBv6tcqVTZWMKtPEJ5o2Gj/QdWxg+9Q0g+VwxLHWZ/JLC1tRzTpiDqTZCgKpiTa82OqSSlfOpCkRFvkjmkoQsKRXtJYDrgIw9ePxVnmFqa3U9tHc9PatCoNsP2FiiU1I29VGAMtOL7i8fIzxktRJz3lbVgWsFgdirDHcb5t/kNL3+LWa7j9kg22NPl48ugaaaxeyvF5LmO0zyCJ+g/GOuuNOLpsWP90bgytAIduyP3OYTYT9EqY78YwE8yx9McXoDQ1dPWwlPe0Wi84DKQ8mwQHF4UpHYbeu6WRdNQ52BXS443PY2Ykxw70vjABkUjAXCLHqVte3mG/kItsUguDMV4EBl3gawV9JhfRpR6ZNNbJG2Vbte6qbC5v0YZAVqkg62n32ICfPjz4XIi2oWpOQSNVMgGoFbLvEG1s6RV/bF9FBM=
    on_success: change
    on_failure: always
