package com.ext.portlet.Activity.model.impl;

import com.ext.portlet.Activity.model.ActivitySubscription;
import com.ext.portlet.Activity.model.ActivitySubscriptionModel;
import com.ext.portlet.Activity.model.ActivitySubscriptionSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * The base model implementation for the ActivitySubscription service. Represents a row in the &quot;xcolab_ActivitySubscription&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ext.portlet.Activity.model.ActivitySubscriptionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ActivitySubscriptionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ActivitySubscriptionImpl
 * @see com.ext.portlet.Activity.model.ActivitySubscription
 * @see com.ext.portlet.Activity.model.ActivitySubscriptionModel
 * @generated
 */
@JSON(strict = true)
public class ActivitySubscriptionModelImpl extends BaseModelImpl<ActivitySubscription>
    implements ActivitySubscriptionModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a activity subscription model instance should use the {@link com.ext.portlet.Activity.model.ActivitySubscription} interface instead.
     */
    public static final String TABLE_NAME = "xcolab_ActivitySubscription";
    public static final Object[][] TABLE_COLUMNS = {
            { "pk", Types.BIGINT },
            { "classNameId", Types.BIGINT },
            { "classPK", Types.BIGINT },
            { "type_", Types.INTEGER },
            { "extraData", Types.VARCHAR },
            { "receiverId", Types.BIGINT },
            { "createDate", Types.TIMESTAMP },
            { "modifiedDate", Types.TIMESTAMP }
        };
    public static final String TABLE_SQL_CREATE = "create table xcolab_ActivitySubscription (pk LONG not null primary key,classNameId LONG,classPK LONG,type_ INTEGER,extraData VARCHAR(75) null,receiverId LONG,createDate DATE null,modifiedDate DATE null)";
    public static final String TABLE_SQL_DROP = "drop table xcolab_ActivitySubscription";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.ext.portlet.Activity.model.ActivitySubscription"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.ext.portlet.Activity.model.ActivitySubscription"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.ext.portlet.Activity.model.ActivitySubscription"),
            true);
    public static long CLASSNAMEID_COLUMN_BITMASK = 1L;
    public static long CLASSPK_COLUMN_BITMASK = 2L;
    public static long EXTRADATA_COLUMN_BITMASK = 4L;
    public static long RECEIVERID_COLUMN_BITMASK = 8L;
    public static long TYPE_COLUMN_BITMASK = 16L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.ext.portlet.Activity.model.ActivitySubscription"));
    private static ClassLoader _classLoader = ActivitySubscription.class.getClassLoader();
    private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
            ActivitySubscription.class
        };
    private long _pk;
    private long _classNameId;
    private long _originalClassNameId;
    private boolean _setOriginalClassNameId;
    private long _classPK;
    private long _originalClassPK;
    private boolean _setOriginalClassPK;
    private int _type;
    private int _originalType;
    private boolean _setOriginalType;
    private String _extraData;
    private String _originalExtraData;
    private long _receiverId;
    private long _originalReceiverId;
    private boolean _setOriginalReceiverId;
    private Date _createDate;
    private Date _modifiedDate;
    private transient ExpandoBridge _expandoBridge;
    private long _columnBitmask;
    private ActivitySubscription _escapedModelProxy;

    public ActivitySubscriptionModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static ActivitySubscription toModel(
        ActivitySubscriptionSoap soapModel) {
        ActivitySubscription model = new ActivitySubscriptionImpl();

        model.setPk(soapModel.getPk());
        model.setClassNameId(soapModel.getClassNameId());
        model.setClassPK(soapModel.getClassPK());
        model.setType(soapModel.getType());
        model.setExtraData(soapModel.getExtraData());
        model.setReceiverId(soapModel.getReceiverId());
        model.setCreateDate(soapModel.getCreateDate());
        model.setModifiedDate(soapModel.getModifiedDate());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<ActivitySubscription> toModels(
        ActivitySubscriptionSoap[] soapModels) {
        List<ActivitySubscription> models = new ArrayList<ActivitySubscription>(soapModels.length);

        for (ActivitySubscriptionSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    public long getPrimaryKey() {
        return _pk;
    }

    public void setPrimaryKey(long primaryKey) {
        setPk(primaryKey);
    }

    public Serializable getPrimaryKeyObj() {
        return new Long(_pk);
    }

    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    public Class<?> getModelClass() {
        return ActivitySubscription.class;
    }

    public String getModelClassName() {
        return ActivitySubscription.class.getName();
    }

    @JSON
    public long getPk() {
        return _pk;
    }

    public void setPk(long pk) {
        _pk = pk;
    }

    public String getClassName() {
        if (getClassNameId() <= 0) {
            return StringPool.BLANK;
        }

        return PortalUtil.getClassName(getClassNameId());
    }

    @JSON
    public long getClassNameId() {
        return _classNameId;
    }

    public void setClassNameId(long classNameId) {
        _columnBitmask |= CLASSNAMEID_COLUMN_BITMASK;

        if (!_setOriginalClassNameId) {
            _setOriginalClassNameId = true;

            _originalClassNameId = _classNameId;
        }

        _classNameId = classNameId;
    }

    public long getOriginalClassNameId() {
        return _originalClassNameId;
    }

    @JSON
    public long getClassPK() {
        return _classPK;
    }

    public void setClassPK(long classPK) {
        _columnBitmask |= CLASSPK_COLUMN_BITMASK;

        if (!_setOriginalClassPK) {
            _setOriginalClassPK = true;

            _originalClassPK = _classPK;
        }

        _classPK = classPK;
    }

    public long getOriginalClassPK() {
        return _originalClassPK;
    }

    @JSON
    public int getType() {
        return _type;
    }

    public void setType(int type) {
        _columnBitmask |= TYPE_COLUMN_BITMASK;

        if (!_setOriginalType) {
            _setOriginalType = true;

            _originalType = _type;
        }

        _type = type;
    }

    public int getOriginalType() {
        return _originalType;
    }

    @JSON
    public String getExtraData() {
        if (_extraData == null) {
            return StringPool.BLANK;
        } else {
            return _extraData;
        }
    }

    public void setExtraData(String extraData) {
        _columnBitmask |= EXTRADATA_COLUMN_BITMASK;

        if (_originalExtraData == null) {
            _originalExtraData = _extraData;
        }

        _extraData = extraData;
    }

    public String getOriginalExtraData() {
        return GetterUtil.getString(_originalExtraData);
    }

    @JSON
    public long getReceiverId() {
        return _receiverId;
    }

    public void setReceiverId(long receiverId) {
        _columnBitmask |= RECEIVERID_COLUMN_BITMASK;

        if (!_setOriginalReceiverId) {
            _setOriginalReceiverId = true;

            _originalReceiverId = _receiverId;
        }

        _receiverId = receiverId;
    }

    public long getOriginalReceiverId() {
        return _originalReceiverId;
    }

    @JSON
    public Date getCreateDate() {
        return _createDate;
    }

    public void setCreateDate(Date createDate) {
        _createDate = createDate;
    }

    @JSON
    public Date getModifiedDate() {
        return _modifiedDate;
    }

    public void setModifiedDate(Date modifiedDate) {
        _modifiedDate = modifiedDate;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ActivitySubscription toEscapedModel() {
        if (_escapedModelProxy == null) {
            _escapedModelProxy = (ActivitySubscription) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelProxyInterfaces,
                    new AutoEscapeBeanHandler(this));
        }

        return _escapedModelProxy;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        if (_expandoBridge == null) {
            _expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
                    ActivitySubscription.class.getName(), getPrimaryKey());
        }

        return _expandoBridge;
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        getExpandoBridge().setAttributes(serviceContext);
    }

    @Override
    public Object clone() {
        ActivitySubscriptionImpl activitySubscriptionImpl = new ActivitySubscriptionImpl();

        activitySubscriptionImpl.setPk(getPk());
        activitySubscriptionImpl.setClassNameId(getClassNameId());
        activitySubscriptionImpl.setClassPK(getClassPK());
        activitySubscriptionImpl.setType(getType());
        activitySubscriptionImpl.setExtraData(getExtraData());
        activitySubscriptionImpl.setReceiverId(getReceiverId());
        activitySubscriptionImpl.setCreateDate(getCreateDate());
        activitySubscriptionImpl.setModifiedDate(getModifiedDate());

        activitySubscriptionImpl.resetOriginalValues();

        return activitySubscriptionImpl;
    }

    public int compareTo(ActivitySubscription activitySubscription) {
        long primaryKey = activitySubscription.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }

        ActivitySubscription activitySubscription = null;

        try {
            activitySubscription = (ActivitySubscription) obj;
        } catch (ClassCastException cce) {
            return false;
        }

        long primaryKey = activitySubscription.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        ActivitySubscriptionModelImpl activitySubscriptionModelImpl = this;

        activitySubscriptionModelImpl._originalClassNameId = activitySubscriptionModelImpl._classNameId;

        activitySubscriptionModelImpl._setOriginalClassNameId = false;

        activitySubscriptionModelImpl._originalClassPK = activitySubscriptionModelImpl._classPK;

        activitySubscriptionModelImpl._setOriginalClassPK = false;

        activitySubscriptionModelImpl._originalType = activitySubscriptionModelImpl._type;

        activitySubscriptionModelImpl._setOriginalType = false;

        activitySubscriptionModelImpl._originalExtraData = activitySubscriptionModelImpl._extraData;

        activitySubscriptionModelImpl._originalReceiverId = activitySubscriptionModelImpl._receiverId;

        activitySubscriptionModelImpl._setOriginalReceiverId = false;

        activitySubscriptionModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<ActivitySubscription> toCacheModel() {
        ActivitySubscriptionCacheModel activitySubscriptionCacheModel = new ActivitySubscriptionCacheModel();

        activitySubscriptionCacheModel.pk = getPk();

        activitySubscriptionCacheModel.classNameId = getClassNameId();

        activitySubscriptionCacheModel.classPK = getClassPK();

        activitySubscriptionCacheModel.type = getType();

        activitySubscriptionCacheModel.extraData = getExtraData();

        String extraData = activitySubscriptionCacheModel.extraData;

        if ((extraData != null) && (extraData.length() == 0)) {
            activitySubscriptionCacheModel.extraData = null;
        }

        activitySubscriptionCacheModel.receiverId = getReceiverId();

        Date createDate = getCreateDate();

        if (createDate != null) {
            activitySubscriptionCacheModel.createDate = createDate.getTime();
        } else {
            activitySubscriptionCacheModel.createDate = Long.MIN_VALUE;
        }

        Date modifiedDate = getModifiedDate();

        if (modifiedDate != null) {
            activitySubscriptionCacheModel.modifiedDate = modifiedDate.getTime();
        } else {
            activitySubscriptionCacheModel.modifiedDate = Long.MIN_VALUE;
        }

        return activitySubscriptionCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(17);

        sb.append("{pk=");
        sb.append(getPk());
        sb.append(", classNameId=");
        sb.append(getClassNameId());
        sb.append(", classPK=");
        sb.append(getClassPK());
        sb.append(", type=");
        sb.append(getType());
        sb.append(", extraData=");
        sb.append(getExtraData());
        sb.append(", receiverId=");
        sb.append(getReceiverId());
        sb.append(", createDate=");
        sb.append(getCreateDate());
        sb.append(", modifiedDate=");
        sb.append(getModifiedDate());
        sb.append("}");

        return sb.toString();
    }

    public String toXmlString() {
        StringBundler sb = new StringBundler(28);

        sb.append("<model><model-name>");
        sb.append("com.ext.portlet.Activity.model.ActivitySubscription");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>pk</column-name><column-value><![CDATA[");
        sb.append(getPk());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>classNameId</column-name><column-value><![CDATA[");
        sb.append(getClassNameId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>classPK</column-name><column-value><![CDATA[");
        sb.append(getClassPK());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>type</column-name><column-value><![CDATA[");
        sb.append(getType());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>extraData</column-name><column-value><![CDATA[");
        sb.append(getExtraData());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>receiverId</column-name><column-value><![CDATA[");
        sb.append(getReceiverId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>createDate</column-name><column-value><![CDATA[");
        sb.append(getCreateDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
        sb.append(getModifiedDate());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
