package com.ext.portlet.model.impl;

import com.ext.portlet.model.AnalyticsUserEvent;

/**
 * The extended model base implementation for the AnalyticsUserEvent service. Represents a row in the &quot;xcolab_AnalyticsUserEvent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AnalyticsUserEventImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AnalyticsUserEventImpl
 * @see com.ext.portlet.model.AnalyticsUserEvent
 * @generated
 */
public abstract class AnalyticsUserEventBaseImpl
    extends AnalyticsUserEventModelImpl implements AnalyticsUserEvent {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a analytics user event model instance should use the {@link AnalyticsUserEvent} interface instead.
     */
}
