package com.ext.portlet.model.impl;

import com.ext.portlet.model.ContestPhase;
import com.ext.portlet.model.ContestPhaseModel;
import com.ext.portlet.model.ContestPhaseSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ContestPhase service. Represents a row in the &quot;xcolab_ContestPhase&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ext.portlet.model.ContestPhaseModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContestPhaseImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContestPhaseImpl
 * @see com.ext.portlet.model.ContestPhase
 * @see com.ext.portlet.model.ContestPhaseModel
 * @generated
 */
@JSON(strict = true)
public class ContestPhaseModelImpl extends BaseModelImpl<ContestPhase>
    implements ContestPhaseModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a contest phase model instance should use the {@link com.ext.portlet.model.ContestPhase} interface instead.
     */
    public static final String TABLE_NAME = "xcolab_ContestPhase";
    public static final Object[][] TABLE_COLUMNS = {
            { "ContestPhasePK", Types.BIGINT },
            { "ContestPK", Types.BIGINT },
            { "ContestPhaseType", Types.BIGINT },
            { "contestScheduleId", Types.BIGINT },
            { "fellowScreeningActive", Types.BOOLEAN },
            { "contestPhaseAutopromote", Types.VARCHAR },
            { "ContestPhaseDescriptionOverride", Types.VARCHAR },
            { "phaseActiveOverride", Types.BOOLEAN },
            { "phaseInactiveOverride", Types.BOOLEAN },
            { "PhaseStartDate", Types.TIMESTAMP },
            { "PhaseEndDate", Types.TIMESTAMP },
            { "PhaseBufferEndDated", Types.TIMESTAMP },
            { "nextStatus", Types.VARCHAR },
            { "created", Types.TIMESTAMP },
            { "updated", Types.TIMESTAMP },
            { "authorId", Types.BIGINT }
        };
    public static final String TABLE_SQL_CREATE = "create table xcolab_ContestPhase (ContestPhasePK LONG not null primary key,ContestPK LONG,ContestPhaseType LONG,contestScheduleId LONG,fellowScreeningActive BOOLEAN,contestPhaseAutopromote VARCHAR(75) null,ContestPhaseDescriptionOverride TEXT null,phaseActiveOverride BOOLEAN,phaseInactiveOverride BOOLEAN,PhaseStartDate DATE null,PhaseEndDate DATE null,PhaseBufferEndDated DATE null,nextStatus VARCHAR(75) null,created DATE null,updated DATE null,authorId LONG)";
    public static final String TABLE_SQL_DROP = "drop table xcolab_ContestPhase";
    public static final String ORDER_BY_JPQL = " ORDER BY contestPhase.PhaseStartDate ASC";
    public static final String ORDER_BY_SQL = " ORDER BY xcolab_ContestPhase.PhaseStartDate ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.ext.portlet.model.ContestPhase"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.ext.portlet.model.ContestPhase"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.ext.portlet.model.ContestPhase"),
            true);
    public static long CONTESTPK_COLUMN_BITMASK = 1L;
    public static long PHASEENDDATE_COLUMN_BITMASK = 2L;
    public static long PHASESTARTDATE_COLUMN_BITMASK = 4L;
    public static long CONTESTPHASEAUTOPROMOTE_COLUMN_BITMASK = 8L;
    public static long CONTESTSCHEDULEID_COLUMN_BITMASK = 16L;
    public static long PHASEACTIVEOVERRIDE_COLUMN_BITMASK = 32L;
    public static long PHASEINACTIVEOVERRIDE_COLUMN_BITMASK = 64L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.ext.portlet.model.ContestPhase"));
    private static ClassLoader _classLoader = ContestPhase.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            ContestPhase.class
        };
    private long _ContestPhasePK;
    private long _ContestPK;
    private long _originalContestPK;
    private boolean _setOriginalContestPK;
    private long _ContestPhaseType;
    private long _contestScheduleId;
    private long _originalContestScheduleId;
    private boolean _setOriginalContestScheduleId;
    private boolean _fellowScreeningActive;
    private String _contestPhaseAutopromote;
    private String _originalContestPhaseAutopromote;
    private String _ContestPhaseDescriptionOverride;
    private boolean _phaseActiveOverride;
    private boolean _originalPhaseActiveOverride;
    private boolean _setOriginalPhaseActiveOverride;
    private boolean _phaseInactiveOverride;
    private boolean _originalPhaseInactiveOverride;
    private boolean _setOriginalPhaseInactiveOverride;
    private Date _PhaseStartDate;
    private Date _originalPhaseStartDate;
    private Date _PhaseEndDate;
    private Date _originalPhaseEndDate;
    private Date _PhaseBufferEndDated;
    private String _nextStatus;
    private Date _created;
    private Date _updated;
    private long _authorId;
    private long _columnBitmask;
    private ContestPhase _escapedModel;

    public ContestPhaseModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static ContestPhase toModel(ContestPhaseSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        ContestPhase model = new ContestPhaseImpl();

        model.setContestPhasePK(soapModel.getContestPhasePK());
        model.setContestPK(soapModel.getContestPK());
        model.setContestPhaseType(soapModel.getContestPhaseType());
        model.setContestScheduleId(soapModel.getContestScheduleId());
        model.setFellowScreeningActive(soapModel.getFellowScreeningActive());
        model.setContestPhaseAutopromote(soapModel.getContestPhaseAutopromote());
        model.setContestPhaseDescriptionOverride(soapModel.getContestPhaseDescriptionOverride());
        model.setPhaseActiveOverride(soapModel.getPhaseActiveOverride());
        model.setPhaseInactiveOverride(soapModel.getPhaseInactiveOverride());
        model.setPhaseStartDate(soapModel.getPhaseStartDate());
        model.setPhaseEndDate(soapModel.getPhaseEndDate());
        model.setPhaseBufferEndDated(soapModel.getPhaseBufferEndDated());
        model.setNextStatus(soapModel.getNextStatus());
        model.setCreated(soapModel.getCreated());
        model.setUpdated(soapModel.getUpdated());
        model.setAuthorId(soapModel.getAuthorId());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<ContestPhase> toModels(ContestPhaseSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<ContestPhase> models = new ArrayList<ContestPhase>(soapModels.length);

        for (ContestPhaseSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _ContestPhasePK;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setContestPhasePK(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _ContestPhasePK;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return ContestPhase.class;
    }

    @Override
    public String getModelClassName() {
        return ContestPhase.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("ContestPhasePK", getContestPhasePK());
        attributes.put("ContestPK", getContestPK());
        attributes.put("ContestPhaseType", getContestPhaseType());
        attributes.put("contestScheduleId", getContestScheduleId());
        attributes.put("fellowScreeningActive", getFellowScreeningActive());
        attributes.put("contestPhaseAutopromote", getContestPhaseAutopromote());
        attributes.put("ContestPhaseDescriptionOverride",
            getContestPhaseDescriptionOverride());
        attributes.put("phaseActiveOverride", getPhaseActiveOverride());
        attributes.put("phaseInactiveOverride", getPhaseInactiveOverride());
        attributes.put("PhaseStartDate", getPhaseStartDate());
        attributes.put("PhaseEndDate", getPhaseEndDate());
        attributes.put("PhaseBufferEndDated", getPhaseBufferEndDated());
        attributes.put("nextStatus", getNextStatus());
        attributes.put("created", getCreated());
        attributes.put("updated", getUpdated());
        attributes.put("authorId", getAuthorId());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long ContestPhasePK = (Long) attributes.get("ContestPhasePK");

        if (ContestPhasePK != null) {
            setContestPhasePK(ContestPhasePK);
        }

        Long ContestPK = (Long) attributes.get("ContestPK");

        if (ContestPK != null) {
            setContestPK(ContestPK);
        }

        Long ContestPhaseType = (Long) attributes.get("ContestPhaseType");

        if (ContestPhaseType != null) {
            setContestPhaseType(ContestPhaseType);
        }

        Long contestScheduleId = (Long) attributes.get("contestScheduleId");

        if (contestScheduleId != null) {
            setContestScheduleId(contestScheduleId);
        }

        Boolean fellowScreeningActive = (Boolean) attributes.get(
                "fellowScreeningActive");

        if (fellowScreeningActive != null) {
            setFellowScreeningActive(fellowScreeningActive);
        }

        String contestPhaseAutopromote = (String) attributes.get(
                "contestPhaseAutopromote");

        if (contestPhaseAutopromote != null) {
            setContestPhaseAutopromote(contestPhaseAutopromote);
        }

        String ContestPhaseDescriptionOverride = (String) attributes.get(
                "ContestPhaseDescriptionOverride");

        if (ContestPhaseDescriptionOverride != null) {
            setContestPhaseDescriptionOverride(ContestPhaseDescriptionOverride);
        }

        Boolean phaseActiveOverride = (Boolean) attributes.get(
                "phaseActiveOverride");

        if (phaseActiveOverride != null) {
            setPhaseActiveOverride(phaseActiveOverride);
        }

        Boolean phaseInactiveOverride = (Boolean) attributes.get(
                "phaseInactiveOverride");

        if (phaseInactiveOverride != null) {
            setPhaseInactiveOverride(phaseInactiveOverride);
        }

        Date PhaseStartDate = (Date) attributes.get("PhaseStartDate");

        if (PhaseStartDate != null) {
            setPhaseStartDate(PhaseStartDate);
        }

        Date PhaseEndDate = (Date) attributes.get("PhaseEndDate");

        if (PhaseEndDate != null) {
            setPhaseEndDate(PhaseEndDate);
        }

        Date PhaseBufferEndDated = (Date) attributes.get("PhaseBufferEndDated");

        if (PhaseBufferEndDated != null) {
            setPhaseBufferEndDated(PhaseBufferEndDated);
        }

        String nextStatus = (String) attributes.get("nextStatus");

        if (nextStatus != null) {
            setNextStatus(nextStatus);
        }

        Date created = (Date) attributes.get("created");

        if (created != null) {
            setCreated(created);
        }

        Date updated = (Date) attributes.get("updated");

        if (updated != null) {
            setUpdated(updated);
        }

        Long authorId = (Long) attributes.get("authorId");

        if (authorId != null) {
            setAuthorId(authorId);
        }
    }

    @JSON
    @Override
    public long getContestPhasePK() {
        return _ContestPhasePK;
    }

    @Override
    public void setContestPhasePK(long ContestPhasePK) {
        _ContestPhasePK = ContestPhasePK;
    }

    @JSON
    @Override
    public long getContestPK() {
        return _ContestPK;
    }

    @Override
    public void setContestPK(long ContestPK) {
        _columnBitmask |= CONTESTPK_COLUMN_BITMASK;

        if (!_setOriginalContestPK) {
            _setOriginalContestPK = true;

            _originalContestPK = _ContestPK;
        }

        _ContestPK = ContestPK;
    }

    public long getOriginalContestPK() {
        return _originalContestPK;
    }

    @JSON
    @Override
    public long getContestPhaseType() {
        return _ContestPhaseType;
    }

    @Override
    public void setContestPhaseType(long ContestPhaseType) {
        _ContestPhaseType = ContestPhaseType;
    }

    @JSON
    @Override
    public long getContestScheduleId() {
        return _contestScheduleId;
    }

    @Override
    public void setContestScheduleId(long contestScheduleId) {
        _columnBitmask |= CONTESTSCHEDULEID_COLUMN_BITMASK;

        if (!_setOriginalContestScheduleId) {
            _setOriginalContestScheduleId = true;

            _originalContestScheduleId = _contestScheduleId;
        }

        _contestScheduleId = contestScheduleId;
    }

    public long getOriginalContestScheduleId() {
        return _originalContestScheduleId;
    }

    @JSON
    @Override
    public boolean getFellowScreeningActive() {
        return _fellowScreeningActive;
    }

    @Override
    public boolean isFellowScreeningActive() {
        return _fellowScreeningActive;
    }

    @Override
    public void setFellowScreeningActive(boolean fellowScreeningActive) {
        _fellowScreeningActive = fellowScreeningActive;
    }

    @JSON
    @Override
    public String getContestPhaseAutopromote() {
        if (_contestPhaseAutopromote == null) {
            return StringPool.BLANK;
        } else {
            return _contestPhaseAutopromote;
        }
    }

    @Override
    public void setContestPhaseAutopromote(String contestPhaseAutopromote) {
        _columnBitmask |= CONTESTPHASEAUTOPROMOTE_COLUMN_BITMASK;

        if (_originalContestPhaseAutopromote == null) {
            _originalContestPhaseAutopromote = _contestPhaseAutopromote;
        }

        _contestPhaseAutopromote = contestPhaseAutopromote;
    }

    public String getOriginalContestPhaseAutopromote() {
        return GetterUtil.getString(_originalContestPhaseAutopromote);
    }

    @JSON
    @Override
    public String getContestPhaseDescriptionOverride() {
        if (_ContestPhaseDescriptionOverride == null) {
            return StringPool.BLANK;
        } else {
            return _ContestPhaseDescriptionOverride;
        }
    }

    @Override
    public void setContestPhaseDescriptionOverride(
        String ContestPhaseDescriptionOverride) {
        _ContestPhaseDescriptionOverride = ContestPhaseDescriptionOverride;
    }

    @JSON
    @Override
    public boolean getPhaseActiveOverride() {
        return _phaseActiveOverride;
    }

    @Override
    public boolean isPhaseActiveOverride() {
        return _phaseActiveOverride;
    }

    @Override
    public void setPhaseActiveOverride(boolean phaseActiveOverride) {
        _columnBitmask |= PHASEACTIVEOVERRIDE_COLUMN_BITMASK;

        if (!_setOriginalPhaseActiveOverride) {
            _setOriginalPhaseActiveOverride = true;

            _originalPhaseActiveOverride = _phaseActiveOverride;
        }

        _phaseActiveOverride = phaseActiveOverride;
    }

    public boolean getOriginalPhaseActiveOverride() {
        return _originalPhaseActiveOverride;
    }

    @JSON
    @Override
    public boolean getPhaseInactiveOverride() {
        return _phaseInactiveOverride;
    }

    @Override
    public boolean isPhaseInactiveOverride() {
        return _phaseInactiveOverride;
    }

    @Override
    public void setPhaseInactiveOverride(boolean phaseInactiveOverride) {
        _columnBitmask |= PHASEINACTIVEOVERRIDE_COLUMN_BITMASK;

        if (!_setOriginalPhaseInactiveOverride) {
            _setOriginalPhaseInactiveOverride = true;

            _originalPhaseInactiveOverride = _phaseInactiveOverride;
        }

        _phaseInactiveOverride = phaseInactiveOverride;
    }

    public boolean getOriginalPhaseInactiveOverride() {
        return _originalPhaseInactiveOverride;
    }

    @JSON
    @Override
    public Date getPhaseStartDate() {
        return _PhaseStartDate;
    }

    @Override
    public void setPhaseStartDate(Date PhaseStartDate) {
        _columnBitmask = -1L;

        if (_originalPhaseStartDate == null) {
            _originalPhaseStartDate = _PhaseStartDate;
        }

        _PhaseStartDate = PhaseStartDate;
    }

    public Date getOriginalPhaseStartDate() {
        return _originalPhaseStartDate;
    }

    @JSON
    @Override
    public Date getPhaseEndDate() {
        return _PhaseEndDate;
    }

    @Override
    public void setPhaseEndDate(Date PhaseEndDate) {
        _columnBitmask |= PHASEENDDATE_COLUMN_BITMASK;

        if (_originalPhaseEndDate == null) {
            _originalPhaseEndDate = _PhaseEndDate;
        }

        _PhaseEndDate = PhaseEndDate;
    }

    public Date getOriginalPhaseEndDate() {
        return _originalPhaseEndDate;
    }

    @JSON
    @Override
    public Date getPhaseBufferEndDated() {
        return _PhaseBufferEndDated;
    }

    @Override
    public void setPhaseBufferEndDated(Date PhaseBufferEndDated) {
        _PhaseBufferEndDated = PhaseBufferEndDated;
    }

    @JSON
    @Override
    public String getNextStatus() {
        if (_nextStatus == null) {
            return StringPool.BLANK;
        } else {
            return _nextStatus;
        }
    }

    @Override
    public void setNextStatus(String nextStatus) {
        _nextStatus = nextStatus;
    }

    @JSON
    @Override
    public Date getCreated() {
        return _created;
    }

    @Override
    public void setCreated(Date created) {
        _created = created;
    }

    @JSON
    @Override
    public Date getUpdated() {
        return _updated;
    }

    @Override
    public void setUpdated(Date updated) {
        _updated = updated;
    }

    @JSON
    @Override
    public long getAuthorId() {
        return _authorId;
    }

    @Override
    public void setAuthorId(long authorId) {
        _authorId = authorId;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            ContestPhase.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public ContestPhase toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (ContestPhase) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        ContestPhaseImpl contestPhaseImpl = new ContestPhaseImpl();

        contestPhaseImpl.setContestPhasePK(getContestPhasePK());
        contestPhaseImpl.setContestPK(getContestPK());
        contestPhaseImpl.setContestPhaseType(getContestPhaseType());
        contestPhaseImpl.setContestScheduleId(getContestScheduleId());
        contestPhaseImpl.setFellowScreeningActive(getFellowScreeningActive());
        contestPhaseImpl.setContestPhaseAutopromote(getContestPhaseAutopromote());
        contestPhaseImpl.setContestPhaseDescriptionOverride(getContestPhaseDescriptionOverride());
        contestPhaseImpl.setPhaseActiveOverride(getPhaseActiveOverride());
        contestPhaseImpl.setPhaseInactiveOverride(getPhaseInactiveOverride());
        contestPhaseImpl.setPhaseStartDate(getPhaseStartDate());
        contestPhaseImpl.setPhaseEndDate(getPhaseEndDate());
        contestPhaseImpl.setPhaseBufferEndDated(getPhaseBufferEndDated());
        contestPhaseImpl.setNextStatus(getNextStatus());
        contestPhaseImpl.setCreated(getCreated());
        contestPhaseImpl.setUpdated(getUpdated());
        contestPhaseImpl.setAuthorId(getAuthorId());

        contestPhaseImpl.resetOriginalValues();

        return contestPhaseImpl;
    }

    @Override
    public int compareTo(ContestPhase contestPhase) {
        int value = 0;

        value = DateUtil.compareTo(getPhaseStartDate(),
                contestPhase.getPhaseStartDate());

        if (value != 0) {
            return value;
        }

        return 0;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof ContestPhase)) {
            return false;
        }

        ContestPhase contestPhase = (ContestPhase) obj;

        long primaryKey = contestPhase.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        ContestPhaseModelImpl contestPhaseModelImpl = this;

        contestPhaseModelImpl._originalContestPK = contestPhaseModelImpl._ContestPK;

        contestPhaseModelImpl._setOriginalContestPK = false;

        contestPhaseModelImpl._originalContestScheduleId = contestPhaseModelImpl._contestScheduleId;

        contestPhaseModelImpl._setOriginalContestScheduleId = false;

        contestPhaseModelImpl._originalContestPhaseAutopromote = contestPhaseModelImpl._contestPhaseAutopromote;

        contestPhaseModelImpl._originalPhaseActiveOverride = contestPhaseModelImpl._phaseActiveOverride;

        contestPhaseModelImpl._setOriginalPhaseActiveOverride = false;

        contestPhaseModelImpl._originalPhaseInactiveOverride = contestPhaseModelImpl._phaseInactiveOverride;

        contestPhaseModelImpl._setOriginalPhaseInactiveOverride = false;

        contestPhaseModelImpl._originalPhaseStartDate = contestPhaseModelImpl._PhaseStartDate;

        contestPhaseModelImpl._originalPhaseEndDate = contestPhaseModelImpl._PhaseEndDate;

        contestPhaseModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<ContestPhase> toCacheModel() {
        ContestPhaseCacheModel contestPhaseCacheModel = new ContestPhaseCacheModel();

        contestPhaseCacheModel.ContestPhasePK = getContestPhasePK();

        contestPhaseCacheModel.ContestPK = getContestPK();

        contestPhaseCacheModel.ContestPhaseType = getContestPhaseType();

        contestPhaseCacheModel.contestScheduleId = getContestScheduleId();

        contestPhaseCacheModel.fellowScreeningActive = getFellowScreeningActive();

        contestPhaseCacheModel.contestPhaseAutopromote = getContestPhaseAutopromote();

        String contestPhaseAutopromote = contestPhaseCacheModel.contestPhaseAutopromote;

        if ((contestPhaseAutopromote != null) &&
                (contestPhaseAutopromote.length() == 0)) {
            contestPhaseCacheModel.contestPhaseAutopromote = null;
        }

        contestPhaseCacheModel.ContestPhaseDescriptionOverride = getContestPhaseDescriptionOverride();

        String ContestPhaseDescriptionOverride = contestPhaseCacheModel.ContestPhaseDescriptionOverride;

        if ((ContestPhaseDescriptionOverride != null) &&
                (ContestPhaseDescriptionOverride.length() == 0)) {
            contestPhaseCacheModel.ContestPhaseDescriptionOverride = null;
        }

        contestPhaseCacheModel.phaseActiveOverride = getPhaseActiveOverride();

        contestPhaseCacheModel.phaseInactiveOverride = getPhaseInactiveOverride();

        Date PhaseStartDate = getPhaseStartDate();

        if (PhaseStartDate != null) {
            contestPhaseCacheModel.PhaseStartDate = PhaseStartDate.getTime();
        } else {
            contestPhaseCacheModel.PhaseStartDate = Long.MIN_VALUE;
        }

        Date PhaseEndDate = getPhaseEndDate();

        if (PhaseEndDate != null) {
            contestPhaseCacheModel.PhaseEndDate = PhaseEndDate.getTime();
        } else {
            contestPhaseCacheModel.PhaseEndDate = Long.MIN_VALUE;
        }

        Date PhaseBufferEndDated = getPhaseBufferEndDated();

        if (PhaseBufferEndDated != null) {
            contestPhaseCacheModel.PhaseBufferEndDated = PhaseBufferEndDated.getTime();
        } else {
            contestPhaseCacheModel.PhaseBufferEndDated = Long.MIN_VALUE;
        }

        contestPhaseCacheModel.nextStatus = getNextStatus();

        String nextStatus = contestPhaseCacheModel.nextStatus;

        if ((nextStatus != null) && (nextStatus.length() == 0)) {
            contestPhaseCacheModel.nextStatus = null;
        }

        Date created = getCreated();

        if (created != null) {
            contestPhaseCacheModel.created = created.getTime();
        } else {
            contestPhaseCacheModel.created = Long.MIN_VALUE;
        }

        Date updated = getUpdated();

        if (updated != null) {
            contestPhaseCacheModel.updated = updated.getTime();
        } else {
            contestPhaseCacheModel.updated = Long.MIN_VALUE;
        }

        contestPhaseCacheModel.authorId = getAuthorId();

        return contestPhaseCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(33);

        sb.append("{ContestPhasePK=");
        sb.append(getContestPhasePK());
        sb.append(", ContestPK=");
        sb.append(getContestPK());
        sb.append(", ContestPhaseType=");
        sb.append(getContestPhaseType());
        sb.append(", contestScheduleId=");
        sb.append(getContestScheduleId());
        sb.append(", fellowScreeningActive=");
        sb.append(getFellowScreeningActive());
        sb.append(", contestPhaseAutopromote=");
        sb.append(getContestPhaseAutopromote());
        sb.append(", ContestPhaseDescriptionOverride=");
        sb.append(getContestPhaseDescriptionOverride());
        sb.append(", phaseActiveOverride=");
        sb.append(getPhaseActiveOverride());
        sb.append(", phaseInactiveOverride=");
        sb.append(getPhaseInactiveOverride());
        sb.append(", PhaseStartDate=");
        sb.append(getPhaseStartDate());
        sb.append(", PhaseEndDate=");
        sb.append(getPhaseEndDate());
        sb.append(", PhaseBufferEndDated=");
        sb.append(getPhaseBufferEndDated());
        sb.append(", nextStatus=");
        sb.append(getNextStatus());
        sb.append(", created=");
        sb.append(getCreated());
        sb.append(", updated=");
        sb.append(getUpdated());
        sb.append(", authorId=");
        sb.append(getAuthorId());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(52);

        sb.append("<model><model-name>");
        sb.append("com.ext.portlet.model.ContestPhase");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>ContestPhasePK</column-name><column-value><![CDATA[");
        sb.append(getContestPhasePK());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>ContestPK</column-name><column-value><![CDATA[");
        sb.append(getContestPK());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>ContestPhaseType</column-name><column-value><![CDATA[");
        sb.append(getContestPhaseType());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>contestScheduleId</column-name><column-value><![CDATA[");
        sb.append(getContestScheduleId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>fellowScreeningActive</column-name><column-value><![CDATA[");
        sb.append(getFellowScreeningActive());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>contestPhaseAutopromote</column-name><column-value><![CDATA[");
        sb.append(getContestPhaseAutopromote());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>ContestPhaseDescriptionOverride</column-name><column-value><![CDATA[");
        sb.append(getContestPhaseDescriptionOverride());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>phaseActiveOverride</column-name><column-value><![CDATA[");
        sb.append(getPhaseActiveOverride());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>phaseInactiveOverride</column-name><column-value><![CDATA[");
        sb.append(getPhaseInactiveOverride());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>PhaseStartDate</column-name><column-value><![CDATA[");
        sb.append(getPhaseStartDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>PhaseEndDate</column-name><column-value><![CDATA[");
        sb.append(getPhaseEndDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>PhaseBufferEndDated</column-name><column-value><![CDATA[");
        sb.append(getPhaseBufferEndDated());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>nextStatus</column-name><column-value><![CDATA[");
        sb.append(getNextStatus());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>created</column-name><column-value><![CDATA[");
        sb.append(getCreated());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>updated</column-name><column-value><![CDATA[");
        sb.append(getUpdated());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>authorId</column-name><column-value><![CDATA[");
        sb.append(getAuthorId());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
