package com.ext.portlet.model.impl;

import com.ext.portlet.model.Contest;
import com.ext.portlet.model.ContestModel;
import com.ext.portlet.model.ContestSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Contest service. Represents a row in the &quot;xcolab_Contest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ext.portlet.model.ContestModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContestImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContestImpl
 * @see com.ext.portlet.model.Contest
 * @see com.ext.portlet.model.ContestModel
 * @generated
 */
@JSON(strict = true)
public class ContestModelImpl extends BaseModelImpl<Contest>
    implements ContestModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a contest model instance should use the {@link com.ext.portlet.model.Contest} interface instead.
     */
    public static final String TABLE_NAME = "xcolab_Contest";
    public static final Object[][] TABLE_COLUMNS = {
            { "ContestPK", Types.BIGINT },
            { "contestTypeId", Types.BIGINT },
            { "ContestName", Types.VARCHAR },
            { "ContestShortName", Types.VARCHAR },
            { "ContestUrlName", Types.VARCHAR },
            { "ContestYear", Types.BIGINT },
            { "ContestDescription", Types.VARCHAR },
            { "ContestModelDescription", Types.VARCHAR },
            { "ContestPositionsDescription", Types.VARCHAR },
            { "created", Types.TIMESTAMP },
            { "updated", Types.TIMESTAMP },
            { "authorId", Types.BIGINT },
            { "contestActive", Types.BOOLEAN },
            { "planTemplateId", Types.BIGINT },
            { "contestScheduleId", Types.BIGINT },
            { "proposalCreationTemplateString", Types.VARCHAR },
            { "voteTemplateString", Types.VARCHAR },
            { "proposalVoteTemplateString", Types.VARCHAR },
            { "proposalVoteConfirmationTemplateString", Types.VARCHAR },
            { "voteQuestionTemplateString", Types.VARCHAR },
            { "focusAreaId", Types.BIGINT },
            { "contestTier", Types.BIGINT },
            { "contestLogoId", Types.BIGINT },
            { "featured_", Types.BOOLEAN },
            { "plansOpenByDefault", Types.BOOLEAN },
            { "sponsorLogoId", Types.BIGINT },
            { "sponsorText", Types.VARCHAR },
            { "sponsorLink", Types.VARCHAR },
            { "flag", Types.INTEGER },
            { "flagText", Types.VARCHAR },
            { "flagTooltip", Types.VARCHAR },
            { "groupId", Types.BIGINT },
            { "discussionGroupId", Types.BIGINT },
            { "weight", Types.INTEGER },
            { "resourcesUrl", Types.VARCHAR },
            { "contestPrivate", Types.BOOLEAN },
            { "usePermissions", Types.BOOLEAN },
            { "contestCreationStatus", Types.VARCHAR },
            { "defaultModelId", Types.BIGINT },
            { "otherModels", Types.VARCHAR },
            { "defaultModelSettings", Types.VARCHAR },
            { "points", Types.DOUBLE },
            { "defaultParentPointType", Types.BIGINT },
            { "pointDistributionStrategy", Types.VARCHAR },
            { "emailTemplateUrl", Types.VARCHAR },
            { "show_in_tile_view", Types.BOOLEAN },
            { "show_in_list_view", Types.BOOLEAN },
            { "show_in_outline_view", Types.BOOLEAN },
            { "hideRibbons", Types.BOOLEAN },
            { "resourceArticleId", Types.BIGINT }
        };
    public static final String TABLE_SQL_CREATE = "create table xcolab_Contest (ContestPK LONG not null primary key,contestTypeId LONG,ContestName VARCHAR(75) null,ContestShortName VARCHAR(75) null,ContestUrlName VARCHAR(75) null,ContestYear LONG,ContestDescription VARCHAR(75) null,ContestModelDescription VARCHAR(75) null,ContestPositionsDescription VARCHAR(75) null,created DATE null,updated DATE null,authorId LONG,contestActive BOOLEAN,planTemplateId LONG,contestScheduleId LONG,proposalCreationTemplateString VARCHAR(75) null,voteTemplateString VARCHAR(75) null,proposalVoteTemplateString VARCHAR(75) null,proposalVoteConfirmationTemplateString VARCHAR(75) null,voteQuestionTemplateString VARCHAR(75) null,focusAreaId LONG,contestTier LONG,contestLogoId LONG,featured_ BOOLEAN,plansOpenByDefault BOOLEAN,sponsorLogoId LONG,sponsorText VARCHAR(75) null,sponsorLink VARCHAR(75) null,flag INTEGER,flagText VARCHAR(75) null,flagTooltip VARCHAR(75) null,groupId LONG,discussionGroupId LONG,weight INTEGER,resourcesUrl VARCHAR(75) null,contestPrivate BOOLEAN,usePermissions BOOLEAN,contestCreationStatus VARCHAR(75) null,defaultModelId LONG,otherModels VARCHAR(75) null,defaultModelSettings VARCHAR(75) null,points DOUBLE,defaultParentPointType LONG,pointDistributionStrategy VARCHAR(75) null,emailTemplateUrl VARCHAR(75) null,show_in_tile_view BOOLEAN,show_in_list_view BOOLEAN,show_in_outline_view BOOLEAN,hideRibbons BOOLEAN,resourceArticleId LONG)";
    public static final String TABLE_SQL_DROP = "drop table xcolab_Contest";
    public static final String ORDER_BY_JPQL = " ORDER BY contest.weight ASC, contest.created ASC";
    public static final String ORDER_BY_SQL = " ORDER BY xcolab_Contest.weight ASC, xcolab_Contest.created ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.ext.portlet.model.Contest"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.ext.portlet.model.Contest"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.ext.portlet.model.Contest"),
            true);
    public static long CONTESTURLNAME_COLUMN_BITMASK = 1L;
    public static long CONTESTYEAR_COLUMN_BITMASK = 2L;
    public static long CONTESTACTIVE_COLUMN_BITMASK = 4L;
    public static long CONTESTPRIVATE_COLUMN_BITMASK = 8L;
    public static long CONTESTTIER_COLUMN_BITMASK = 16L;
    public static long CONTESTTYPEID_COLUMN_BITMASK = 32L;
    public static long FEATURED_COLUMN_BITMASK = 64L;
    public static long FLAG_COLUMN_BITMASK = 128L;
    public static long WEIGHT_COLUMN_BITMASK = 256L;
    public static long CREATED_COLUMN_BITMASK = 512L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.ext.portlet.model.Contest"));
    private static ClassLoader _classLoader = Contest.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            Contest.class
        };
    private long _ContestPK;
    private long _contestTypeId;
    private long _originalContestTypeId;
    private boolean _setOriginalContestTypeId;
    private String _ContestName;
    private String _ContestShortName;
    private String _ContestUrlName;
    private String _originalContestUrlName;
    private long _ContestYear;
    private long _originalContestYear;
    private boolean _setOriginalContestYear;
    private String _ContestDescription;
    private String _ContestModelDescription;
    private String _ContestPositionsDescription;
    private Date _created;
    private Date _updated;
    private long _authorId;
    private boolean _contestActive;
    private boolean _originalContestActive;
    private boolean _setOriginalContestActive;
    private long _planTemplateId;
    private long _contestScheduleId;
    private String _proposalCreationTemplateString;
    private String _voteTemplateString;
    private String _proposalVoteTemplateString;
    private String _proposalVoteConfirmationTemplateString;
    private String _voteQuestionTemplateString;
    private long _focusAreaId;
    private long _contestTier;
    private long _originalContestTier;
    private boolean _setOriginalContestTier;
    private long _contestLogoId;
    private boolean _featured;
    private boolean _originalFeatured;
    private boolean _setOriginalFeatured;
    private boolean _plansOpenByDefault;
    private long _sponsorLogoId;
    private String _sponsorText;
    private String _sponsorLink;
    private int _flag;
    private int _originalFlag;
    private boolean _setOriginalFlag;
    private String _flagText;
    private String _flagTooltip;
    private long _groupId;
    private long _discussionGroupId;
    private int _weight;
    private String _resourcesUrl;
    private boolean _contestPrivate;
    private boolean _originalContestPrivate;
    private boolean _setOriginalContestPrivate;
    private boolean _usePermissions;
    private String _contestCreationStatus;
    private long _defaultModelId;
    private String _otherModels;
    private String _defaultModelSettings;
    private double _points;
    private long _defaultParentPointType;
    private String _pointDistributionStrategy;
    private String _emailTemplateUrl;
    private boolean _show_in_tile_view;
    private boolean _show_in_list_view;
    private boolean _show_in_outline_view;
    private boolean _hideRibbons;
    private long _resourceArticleId;
    private long _columnBitmask;
    private Contest _escapedModel;

    public ContestModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Contest toModel(ContestSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Contest model = new ContestImpl();

        model.setContestPK(soapModel.getContestPK());
        model.setContestTypeId(soapModel.getContestTypeId());
        model.setContestName(soapModel.getContestName());
        model.setContestShortName(soapModel.getContestShortName());
        model.setContestUrlName(soapModel.getContestUrlName());
        model.setContestYear(soapModel.getContestYear());
        model.setContestDescription(soapModel.getContestDescription());
        model.setContestModelDescription(soapModel.getContestModelDescription());
        model.setContestPositionsDescription(soapModel.getContestPositionsDescription());
        model.setCreated(soapModel.getCreated());
        model.setUpdated(soapModel.getUpdated());
        model.setAuthorId(soapModel.getAuthorId());
        model.setContestActive(soapModel.getContestActive());
        model.setPlanTemplateId(soapModel.getPlanTemplateId());
        model.setContestScheduleId(soapModel.getContestScheduleId());
        model.setProposalCreationTemplateString(soapModel.getProposalCreationTemplateString());
        model.setVoteTemplateString(soapModel.getVoteTemplateString());
        model.setProposalVoteTemplateString(soapModel.getProposalVoteTemplateString());
        model.setProposalVoteConfirmationTemplateString(soapModel.getProposalVoteConfirmationTemplateString());
        model.setVoteQuestionTemplateString(soapModel.getVoteQuestionTemplateString());
        model.setFocusAreaId(soapModel.getFocusAreaId());
        model.setContestTier(soapModel.getContestTier());
        model.setContestLogoId(soapModel.getContestLogoId());
        model.setFeatured(soapModel.getFeatured());
        model.setPlansOpenByDefault(soapModel.getPlansOpenByDefault());
        model.setSponsorLogoId(soapModel.getSponsorLogoId());
        model.setSponsorText(soapModel.getSponsorText());
        model.setSponsorLink(soapModel.getSponsorLink());
        model.setFlag(soapModel.getFlag());
        model.setFlagText(soapModel.getFlagText());
        model.setFlagTooltip(soapModel.getFlagTooltip());
        model.setGroupId(soapModel.getGroupId());
        model.setDiscussionGroupId(soapModel.getDiscussionGroupId());
        model.setWeight(soapModel.getWeight());
        model.setResourcesUrl(soapModel.getResourcesUrl());
        model.setContestPrivate(soapModel.getContestPrivate());
        model.setUsePermissions(soapModel.getUsePermissions());
        model.setContestCreationStatus(soapModel.getContestCreationStatus());
        model.setDefaultModelId(soapModel.getDefaultModelId());
        model.setOtherModels(soapModel.getOtherModels());
        model.setDefaultModelSettings(soapModel.getDefaultModelSettings());
        model.setPoints(soapModel.getPoints());
        model.setDefaultParentPointType(soapModel.getDefaultParentPointType());
        model.setPointDistributionStrategy(soapModel.getPointDistributionStrategy());
        model.setEmailTemplateUrl(soapModel.getEmailTemplateUrl());
        model.setShow_in_tile_view(soapModel.getShow_in_tile_view());
        model.setShow_in_list_view(soapModel.getShow_in_list_view());
        model.setShow_in_outline_view(soapModel.getShow_in_outline_view());
        model.setHideRibbons(soapModel.getHideRibbons());
        model.setResourceArticleId(soapModel.getResourceArticleId());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Contest> toModels(ContestSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Contest> models = new ArrayList<Contest>(soapModels.length);

        for (ContestSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _ContestPK;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setContestPK(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _ContestPK;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Contest.class;
    }

    @Override
    public String getModelClassName() {
        return Contest.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("ContestPK", getContestPK());
        attributes.put("contestTypeId", getContestTypeId());
        attributes.put("ContestName", getContestName());
        attributes.put("ContestShortName", getContestShortName());
        attributes.put("ContestUrlName", getContestUrlName());
        attributes.put("ContestYear", getContestYear());
        attributes.put("ContestDescription", getContestDescription());
        attributes.put("ContestModelDescription", getContestModelDescription());
        attributes.put("ContestPositionsDescription",
            getContestPositionsDescription());
        attributes.put("created", getCreated());
        attributes.put("updated", getUpdated());
        attributes.put("authorId", getAuthorId());
        attributes.put("contestActive", getContestActive());
        attributes.put("planTemplateId", getPlanTemplateId());
        attributes.put("contestScheduleId", getContestScheduleId());
        attributes.put("proposalCreationTemplateString",
            getProposalCreationTemplateString());
        attributes.put("voteTemplateString", getVoteTemplateString());
        attributes.put("proposalVoteTemplateString",
            getProposalVoteTemplateString());
        attributes.put("proposalVoteConfirmationTemplateString",
            getProposalVoteConfirmationTemplateString());
        attributes.put("voteQuestionTemplateString",
            getVoteQuestionTemplateString());
        attributes.put("focusAreaId", getFocusAreaId());
        attributes.put("contestTier", getContestTier());
        attributes.put("contestLogoId", getContestLogoId());
        attributes.put("featured", getFeatured());
        attributes.put("plansOpenByDefault", getPlansOpenByDefault());
        attributes.put("sponsorLogoId", getSponsorLogoId());
        attributes.put("sponsorText", getSponsorText());
        attributes.put("sponsorLink", getSponsorLink());
        attributes.put("flag", getFlag());
        attributes.put("flagText", getFlagText());
        attributes.put("flagTooltip", getFlagTooltip());
        attributes.put("groupId", getGroupId());
        attributes.put("discussionGroupId", getDiscussionGroupId());
        attributes.put("weight", getWeight());
        attributes.put("resourcesUrl", getResourcesUrl());
        attributes.put("contestPrivate", getContestPrivate());
        attributes.put("usePermissions", getUsePermissions());
        attributes.put("contestCreationStatus", getContestCreationStatus());
        attributes.put("defaultModelId", getDefaultModelId());
        attributes.put("otherModels", getOtherModels());
        attributes.put("defaultModelSettings", getDefaultModelSettings());
        attributes.put("points", getPoints());
        attributes.put("defaultParentPointType", getDefaultParentPointType());
        attributes.put("pointDistributionStrategy",
            getPointDistributionStrategy());
        attributes.put("emailTemplateUrl", getEmailTemplateUrl());
        attributes.put("show_in_tile_view", getShow_in_tile_view());
        attributes.put("show_in_list_view", getShow_in_list_view());
        attributes.put("show_in_outline_view", getShow_in_outline_view());
        attributes.put("hideRibbons", getHideRibbons());
        attributes.put("resourceArticleId", getResourceArticleId());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long ContestPK = (Long) attributes.get("ContestPK");

        if (ContestPK != null) {
            setContestPK(ContestPK);
        }

        Long contestTypeId = (Long) attributes.get("contestTypeId");

        if (contestTypeId != null) {
            setContestTypeId(contestTypeId);
        }

        String ContestName = (String) attributes.get("ContestName");

        if (ContestName != null) {
            setContestName(ContestName);
        }

        String ContestShortName = (String) attributes.get("ContestShortName");

        if (ContestShortName != null) {
            setContestShortName(ContestShortName);
        }

        String ContestUrlName = (String) attributes.get("ContestUrlName");

        if (ContestUrlName != null) {
            setContestUrlName(ContestUrlName);
        }

        Long ContestYear = (Long) attributes.get("ContestYear");

        if (ContestYear != null) {
            setContestYear(ContestYear);
        }

        String ContestDescription = (String) attributes.get(
                "ContestDescription");

        if (ContestDescription != null) {
            setContestDescription(ContestDescription);
        }

        String ContestModelDescription = (String) attributes.get(
                "ContestModelDescription");

        if (ContestModelDescription != null) {
            setContestModelDescription(ContestModelDescription);
        }

        String ContestPositionsDescription = (String) attributes.get(
                "ContestPositionsDescription");

        if (ContestPositionsDescription != null) {
            setContestPositionsDescription(ContestPositionsDescription);
        }

        Date created = (Date) attributes.get("created");

        if (created != null) {
            setCreated(created);
        }

        Date updated = (Date) attributes.get("updated");

        if (updated != null) {
            setUpdated(updated);
        }

        Long authorId = (Long) attributes.get("authorId");

        if (authorId != null) {
            setAuthorId(authorId);
        }

        Boolean contestActive = (Boolean) attributes.get("contestActive");

        if (contestActive != null) {
            setContestActive(contestActive);
        }

        Long planTemplateId = (Long) attributes.get("planTemplateId");

        if (planTemplateId != null) {
            setPlanTemplateId(planTemplateId);
        }

        Long contestScheduleId = (Long) attributes.get("contestScheduleId");

        if (contestScheduleId != null) {
            setContestScheduleId(contestScheduleId);
        }

        String proposalCreationTemplateString = (String) attributes.get(
                "proposalCreationTemplateString");

        if (proposalCreationTemplateString != null) {
            setProposalCreationTemplateString(proposalCreationTemplateString);
        }

        String voteTemplateString = (String) attributes.get(
                "voteTemplateString");

        if (voteTemplateString != null) {
            setVoteTemplateString(voteTemplateString);
        }

        String proposalVoteTemplateString = (String) attributes.get(
                "proposalVoteTemplateString");

        if (proposalVoteTemplateString != null) {
            setProposalVoteTemplateString(proposalVoteTemplateString);
        }

        String proposalVoteConfirmationTemplateString = (String) attributes.get(
                "proposalVoteConfirmationTemplateString");

        if (proposalVoteConfirmationTemplateString != null) {
            setProposalVoteConfirmationTemplateString(proposalVoteConfirmationTemplateString);
        }

        String voteQuestionTemplateString = (String) attributes.get(
                "voteQuestionTemplateString");

        if (voteQuestionTemplateString != null) {
            setVoteQuestionTemplateString(voteQuestionTemplateString);
        }

        Long focusAreaId = (Long) attributes.get("focusAreaId");

        if (focusAreaId != null) {
            setFocusAreaId(focusAreaId);
        }

        Long contestTier = (Long) attributes.get("contestTier");

        if (contestTier != null) {
            setContestTier(contestTier);
        }

        Long contestLogoId = (Long) attributes.get("contestLogoId");

        if (contestLogoId != null) {
            setContestLogoId(contestLogoId);
        }

        Boolean featured = (Boolean) attributes.get("featured");

        if (featured != null) {
            setFeatured(featured);
        }

        Boolean plansOpenByDefault = (Boolean) attributes.get(
                "plansOpenByDefault");

        if (plansOpenByDefault != null) {
            setPlansOpenByDefault(plansOpenByDefault);
        }

        Long sponsorLogoId = (Long) attributes.get("sponsorLogoId");

        if (sponsorLogoId != null) {
            setSponsorLogoId(sponsorLogoId);
        }

        String sponsorText = (String) attributes.get("sponsorText");

        if (sponsorText != null) {
            setSponsorText(sponsorText);
        }

        String sponsorLink = (String) attributes.get("sponsorLink");

        if (sponsorLink != null) {
            setSponsorLink(sponsorLink);
        }

        Integer flag = (Integer) attributes.get("flag");

        if (flag != null) {
            setFlag(flag);
        }

        String flagText = (String) attributes.get("flagText");

        if (flagText != null) {
            setFlagText(flagText);
        }

        String flagTooltip = (String) attributes.get("flagTooltip");

        if (flagTooltip != null) {
            setFlagTooltip(flagTooltip);
        }

        Long groupId = (Long) attributes.get("groupId");

        if (groupId != null) {
            setGroupId(groupId);
        }

        Long discussionGroupId = (Long) attributes.get("discussionGroupId");

        if (discussionGroupId != null) {
            setDiscussionGroupId(discussionGroupId);
        }

        Integer weight = (Integer) attributes.get("weight");

        if (weight != null) {
            setWeight(weight);
        }

        String resourcesUrl = (String) attributes.get("resourcesUrl");

        if (resourcesUrl != null) {
            setResourcesUrl(resourcesUrl);
        }

        Boolean contestPrivate = (Boolean) attributes.get("contestPrivate");

        if (contestPrivate != null) {
            setContestPrivate(contestPrivate);
        }

        Boolean usePermissions = (Boolean) attributes.get("usePermissions");

        if (usePermissions != null) {
            setUsePermissions(usePermissions);
        }

        String contestCreationStatus = (String) attributes.get(
                "contestCreationStatus");

        if (contestCreationStatus != null) {
            setContestCreationStatus(contestCreationStatus);
        }

        Long defaultModelId = (Long) attributes.get("defaultModelId");

        if (defaultModelId != null) {
            setDefaultModelId(defaultModelId);
        }

        String otherModels = (String) attributes.get("otherModels");

        if (otherModels != null) {
            setOtherModels(otherModels);
        }

        String defaultModelSettings = (String) attributes.get(
                "defaultModelSettings");

        if (defaultModelSettings != null) {
            setDefaultModelSettings(defaultModelSettings);
        }

        Double points = (Double) attributes.get("points");

        if (points != null) {
            setPoints(points);
        }

        Long defaultParentPointType = (Long) attributes.get(
                "defaultParentPointType");

        if (defaultParentPointType != null) {
            setDefaultParentPointType(defaultParentPointType);
        }

        String pointDistributionStrategy = (String) attributes.get(
                "pointDistributionStrategy");

        if (pointDistributionStrategy != null) {
            setPointDistributionStrategy(pointDistributionStrategy);
        }

        String emailTemplateUrl = (String) attributes.get("emailTemplateUrl");

        if (emailTemplateUrl != null) {
            setEmailTemplateUrl(emailTemplateUrl);
        }

        Boolean show_in_tile_view = (Boolean) attributes.get(
                "show_in_tile_view");

        if (show_in_tile_view != null) {
            setShow_in_tile_view(show_in_tile_view);
        }

        Boolean show_in_list_view = (Boolean) attributes.get(
                "show_in_list_view");

        if (show_in_list_view != null) {
            setShow_in_list_view(show_in_list_view);
        }

        Boolean show_in_outline_view = (Boolean) attributes.get(
                "show_in_outline_view");

        if (show_in_outline_view != null) {
            setShow_in_outline_view(show_in_outline_view);
        }

        Boolean hideRibbons = (Boolean) attributes.get("hideRibbons");

        if (hideRibbons != null) {
            setHideRibbons(hideRibbons);
        }

        Long resourceArticleId = (Long) attributes.get("resourceArticleId");

        if (resourceArticleId != null) {
            setResourceArticleId(resourceArticleId);
        }
    }

    @JSON
    @Override
    public long getContestPK() {
        return _ContestPK;
    }

    @Override
    public void setContestPK(long ContestPK) {
        _ContestPK = ContestPK;
    }

    @JSON
    @Override
    public long getContestTypeId() {
        return _contestTypeId;
    }

    @Override
    public void setContestTypeId(long contestTypeId) {
        _columnBitmask |= CONTESTTYPEID_COLUMN_BITMASK;

        if (!_setOriginalContestTypeId) {
            _setOriginalContestTypeId = true;

            _originalContestTypeId = _contestTypeId;
        }

        _contestTypeId = contestTypeId;
    }

    public long getOriginalContestTypeId() {
        return _originalContestTypeId;
    }

    @JSON
    @Override
    public String getContestName() {
        if (_ContestName == null) {
            return StringPool.BLANK;
        } else {
            return _ContestName;
        }
    }

    @Override
    public void setContestName(String ContestName) {
        _ContestName = ContestName;
    }

    @JSON
    @Override
    public String getContestShortName() {
        if (_ContestShortName == null) {
            return StringPool.BLANK;
        } else {
            return _ContestShortName;
        }
    }

    @Override
    public void setContestShortName(String ContestShortName) {
        _ContestShortName = ContestShortName;
    }

    @JSON
    @Override
    public String getContestUrlName() {
        if (_ContestUrlName == null) {
            return StringPool.BLANK;
        } else {
            return _ContestUrlName;
        }
    }

    @Override
    public void setContestUrlName(String ContestUrlName) {
        _columnBitmask |= CONTESTURLNAME_COLUMN_BITMASK;

        if (_originalContestUrlName == null) {
            _originalContestUrlName = _ContestUrlName;
        }

        _ContestUrlName = ContestUrlName;
    }

    public String getOriginalContestUrlName() {
        return GetterUtil.getString(_originalContestUrlName);
    }

    @JSON
    @Override
    public long getContestYear() {
        return _ContestYear;
    }

    @Override
    public void setContestYear(long ContestYear) {
        _columnBitmask |= CONTESTYEAR_COLUMN_BITMASK;

        if (!_setOriginalContestYear) {
            _setOriginalContestYear = true;

            _originalContestYear = _ContestYear;
        }

        _ContestYear = ContestYear;
    }

    public long getOriginalContestYear() {
        return _originalContestYear;
    }

    @JSON
    @Override
    public String getContestDescription() {
        if (_ContestDescription == null) {
            return StringPool.BLANK;
        } else {
            return _ContestDescription;
        }
    }

    @Override
    public void setContestDescription(String ContestDescription) {
        _ContestDescription = ContestDescription;
    }

    @JSON
    @Override
    public String getContestModelDescription() {
        if (_ContestModelDescription == null) {
            return StringPool.BLANK;
        } else {
            return _ContestModelDescription;
        }
    }

    @Override
    public void setContestModelDescription(String ContestModelDescription) {
        _ContestModelDescription = ContestModelDescription;
    }

    @JSON
    @Override
    public String getContestPositionsDescription() {
        if (_ContestPositionsDescription == null) {
            return StringPool.BLANK;
        } else {
            return _ContestPositionsDescription;
        }
    }

    @Override
    public void setContestPositionsDescription(
        String ContestPositionsDescription) {
        _ContestPositionsDescription = ContestPositionsDescription;
    }

    @JSON
    @Override
    public Date getCreated() {
        return _created;
    }

    @Override
    public void setCreated(Date created) {
        _columnBitmask = -1L;

        _created = created;
    }

    @JSON
    @Override
    public Date getUpdated() {
        return _updated;
    }

    @Override
    public void setUpdated(Date updated) {
        _updated = updated;
    }

    @JSON
    @Override
    public long getAuthorId() {
        return _authorId;
    }

    @Override
    public void setAuthorId(long authorId) {
        _authorId = authorId;
    }

    @JSON
    @Override
    public boolean getContestActive() {
        return _contestActive;
    }

    @Override
    public boolean isContestActive() {
        return _contestActive;
    }

    @Override
    public void setContestActive(boolean contestActive) {
        _columnBitmask |= CONTESTACTIVE_COLUMN_BITMASK;

        if (!_setOriginalContestActive) {
            _setOriginalContestActive = true;

            _originalContestActive = _contestActive;
        }

        _contestActive = contestActive;
    }

    public boolean getOriginalContestActive() {
        return _originalContestActive;
    }

    @JSON
    @Override
    public long getPlanTemplateId() {
        return _planTemplateId;
    }

    @Override
    public void setPlanTemplateId(long planTemplateId) {
        _planTemplateId = planTemplateId;
    }

    @JSON
    @Override
    public long getContestScheduleId() {
        return _contestScheduleId;
    }

    @Override
    public void setContestScheduleId(long contestScheduleId) {
        _contestScheduleId = contestScheduleId;
    }

    @JSON
    @Override
    public String getProposalCreationTemplateString() {
        if (_proposalCreationTemplateString == null) {
            return StringPool.BLANK;
        } else {
            return _proposalCreationTemplateString;
        }
    }

    @Override
    public void setProposalCreationTemplateString(
        String proposalCreationTemplateString) {
        _proposalCreationTemplateString = proposalCreationTemplateString;
    }

    @JSON
    @Override
    public String getVoteTemplateString() {
        if (_voteTemplateString == null) {
            return StringPool.BLANK;
        } else {
            return _voteTemplateString;
        }
    }

    @Override
    public void setVoteTemplateString(String voteTemplateString) {
        _voteTemplateString = voteTemplateString;
    }

    @JSON
    @Override
    public String getProposalVoteTemplateString() {
        if (_proposalVoteTemplateString == null) {
            return StringPool.BLANK;
        } else {
            return _proposalVoteTemplateString;
        }
    }

    @Override
    public void setProposalVoteTemplateString(String proposalVoteTemplateString) {
        _proposalVoteTemplateString = proposalVoteTemplateString;
    }

    @JSON
    @Override
    public String getProposalVoteConfirmationTemplateString() {
        if (_proposalVoteConfirmationTemplateString == null) {
            return StringPool.BLANK;
        } else {
            return _proposalVoteConfirmationTemplateString;
        }
    }

    @Override
    public void setProposalVoteConfirmationTemplateString(
        String proposalVoteConfirmationTemplateString) {
        _proposalVoteConfirmationTemplateString = proposalVoteConfirmationTemplateString;
    }

    @JSON
    @Override
    public String getVoteQuestionTemplateString() {
        if (_voteQuestionTemplateString == null) {
            return StringPool.BLANK;
        } else {
            return _voteQuestionTemplateString;
        }
    }

    @Override
    public void setVoteQuestionTemplateString(String voteQuestionTemplateString) {
        _voteQuestionTemplateString = voteQuestionTemplateString;
    }

    @JSON
    @Override
    public long getFocusAreaId() {
        return _focusAreaId;
    }

    @Override
    public void setFocusAreaId(long focusAreaId) {
        _focusAreaId = focusAreaId;
    }

    @JSON
    @Override
    public long getContestTier() {
        return _contestTier;
    }

    @Override
    public void setContestTier(long contestTier) {
        _columnBitmask |= CONTESTTIER_COLUMN_BITMASK;

        if (!_setOriginalContestTier) {
            _setOriginalContestTier = true;

            _originalContestTier = _contestTier;
        }

        _contestTier = contestTier;
    }

    public long getOriginalContestTier() {
        return _originalContestTier;
    }

    @JSON
    @Override
    public long getContestLogoId() {
        return _contestLogoId;
    }

    @Override
    public void setContestLogoId(long contestLogoId) {
        _contestLogoId = contestLogoId;
    }

    @JSON
    @Override
    public boolean getFeatured() {
        return _featured;
    }

    @Override
    public boolean isFeatured() {
        return _featured;
    }

    @Override
    public void setFeatured(boolean featured) {
        _columnBitmask |= FEATURED_COLUMN_BITMASK;

        if (!_setOriginalFeatured) {
            _setOriginalFeatured = true;

            _originalFeatured = _featured;
        }

        _featured = featured;
    }

    public boolean getOriginalFeatured() {
        return _originalFeatured;
    }

    @JSON
    @Override
    public boolean getPlansOpenByDefault() {
        return _plansOpenByDefault;
    }

    @Override
    public boolean isPlansOpenByDefault() {
        return _plansOpenByDefault;
    }

    @Override
    public void setPlansOpenByDefault(boolean plansOpenByDefault) {
        _plansOpenByDefault = plansOpenByDefault;
    }

    @JSON
    @Override
    public long getSponsorLogoId() {
        return _sponsorLogoId;
    }

    @Override
    public void setSponsorLogoId(long sponsorLogoId) {
        _sponsorLogoId = sponsorLogoId;
    }

    @JSON
    @Override
    public String getSponsorText() {
        if (_sponsorText == null) {
            return StringPool.BLANK;
        } else {
            return _sponsorText;
        }
    }

    @Override
    public void setSponsorText(String sponsorText) {
        _sponsorText = sponsorText;
    }

    @JSON
    @Override
    public String getSponsorLink() {
        if (_sponsorLink == null) {
            return StringPool.BLANK;
        } else {
            return _sponsorLink;
        }
    }

    @Override
    public void setSponsorLink(String sponsorLink) {
        _sponsorLink = sponsorLink;
    }

    @JSON
    @Override
    public int getFlag() {
        return _flag;
    }

    @Override
    public void setFlag(int flag) {
        _columnBitmask |= FLAG_COLUMN_BITMASK;

        if (!_setOriginalFlag) {
            _setOriginalFlag = true;

            _originalFlag = _flag;
        }

        _flag = flag;
    }

    public int getOriginalFlag() {
        return _originalFlag;
    }

    @JSON
    @Override
    public String getFlagText() {
        if (_flagText == null) {
            return StringPool.BLANK;
        } else {
            return _flagText;
        }
    }

    @Override
    public void setFlagText(String flagText) {
        _flagText = flagText;
    }

    @JSON
    @Override
    public String getFlagTooltip() {
        if (_flagTooltip == null) {
            return StringPool.BLANK;
        } else {
            return _flagTooltip;
        }
    }

    @Override
    public void setFlagTooltip(String flagTooltip) {
        _flagTooltip = flagTooltip;
    }

    @JSON
    @Override
    public long getGroupId() {
        return _groupId;
    }

    @Override
    public void setGroupId(long groupId) {
        _groupId = groupId;
    }

    @JSON
    @Override
    public long getDiscussionGroupId() {
        return _discussionGroupId;
    }

    @Override
    public void setDiscussionGroupId(long discussionGroupId) {
        _discussionGroupId = discussionGroupId;
    }

    @JSON
    @Override
    public int getWeight() {
        return _weight;
    }

    @Override
    public void setWeight(int weight) {
        _columnBitmask = -1L;

        _weight = weight;
    }

    @JSON
    @Override
    public String getResourcesUrl() {
        if (_resourcesUrl == null) {
            return StringPool.BLANK;
        } else {
            return _resourcesUrl;
        }
    }

    @Override
    public void setResourcesUrl(String resourcesUrl) {
        _resourcesUrl = resourcesUrl;
    }

    @JSON
    @Override
    public boolean getContestPrivate() {
        return _contestPrivate;
    }

    @Override
    public boolean isContestPrivate() {
        return _contestPrivate;
    }

    @Override
    public void setContestPrivate(boolean contestPrivate) {
        _columnBitmask |= CONTESTPRIVATE_COLUMN_BITMASK;

        if (!_setOriginalContestPrivate) {
            _setOriginalContestPrivate = true;

            _originalContestPrivate = _contestPrivate;
        }

        _contestPrivate = contestPrivate;
    }

    public boolean getOriginalContestPrivate() {
        return _originalContestPrivate;
    }

    @JSON
    @Override
    public boolean getUsePermissions() {
        return _usePermissions;
    }

    @Override
    public boolean isUsePermissions() {
        return _usePermissions;
    }

    @Override
    public void setUsePermissions(boolean usePermissions) {
        _usePermissions = usePermissions;
    }

    @JSON
    @Override
    public String getContestCreationStatus() {
        if (_contestCreationStatus == null) {
            return StringPool.BLANK;
        } else {
            return _contestCreationStatus;
        }
    }

    @Override
    public void setContestCreationStatus(String contestCreationStatus) {
        _contestCreationStatus = contestCreationStatus;
    }

    @JSON
    @Override
    public long getDefaultModelId() {
        return _defaultModelId;
    }

    @Override
    public void setDefaultModelId(long defaultModelId) {
        _defaultModelId = defaultModelId;
    }

    @JSON
    @Override
    public String getOtherModels() {
        if (_otherModels == null) {
            return StringPool.BLANK;
        } else {
            return _otherModels;
        }
    }

    @Override
    public void setOtherModels(String otherModels) {
        _otherModels = otherModels;
    }

    @JSON
    @Override
    public String getDefaultModelSettings() {
        if (_defaultModelSettings == null) {
            return StringPool.BLANK;
        } else {
            return _defaultModelSettings;
        }
    }

    @Override
    public void setDefaultModelSettings(String defaultModelSettings) {
        _defaultModelSettings = defaultModelSettings;
    }

    @JSON
    @Override
    public double getPoints() {
        return _points;
    }

    @Override
    public void setPoints(double points) {
        _points = points;
    }

    @JSON
    @Override
    public long getDefaultParentPointType() {
        return _defaultParentPointType;
    }

    @Override
    public void setDefaultParentPointType(long defaultParentPointType) {
        _defaultParentPointType = defaultParentPointType;
    }

    @JSON
    @Override
    public String getPointDistributionStrategy() {
        if (_pointDistributionStrategy == null) {
            return StringPool.BLANK;
        } else {
            return _pointDistributionStrategy;
        }
    }

    @Override
    public void setPointDistributionStrategy(String pointDistributionStrategy) {
        _pointDistributionStrategy = pointDistributionStrategy;
    }

    @JSON
    @Override
    public String getEmailTemplateUrl() {
        if (_emailTemplateUrl == null) {
            return StringPool.BLANK;
        } else {
            return _emailTemplateUrl;
        }
    }

    @Override
    public void setEmailTemplateUrl(String emailTemplateUrl) {
        _emailTemplateUrl = emailTemplateUrl;
    }

    @JSON
    @Override
    public boolean getShow_in_tile_view() {
        return _show_in_tile_view;
    }

    @Override
    public boolean isShow_in_tile_view() {
        return _show_in_tile_view;
    }

    @Override
    public void setShow_in_tile_view(boolean show_in_tile_view) {
        _show_in_tile_view = show_in_tile_view;
    }

    @JSON
    @Override
    public boolean getShow_in_list_view() {
        return _show_in_list_view;
    }

    @Override
    public boolean isShow_in_list_view() {
        return _show_in_list_view;
    }

    @Override
    public void setShow_in_list_view(boolean show_in_list_view) {
        _show_in_list_view = show_in_list_view;
    }

    @JSON
    @Override
    public boolean getShow_in_outline_view() {
        return _show_in_outline_view;
    }

    @Override
    public boolean isShow_in_outline_view() {
        return _show_in_outline_view;
    }

    @Override
    public void setShow_in_outline_view(boolean show_in_outline_view) {
        _show_in_outline_view = show_in_outline_view;
    }

    @JSON
    @Override
    public boolean getHideRibbons() {
        return _hideRibbons;
    }

    @Override
    public boolean isHideRibbons() {
        return _hideRibbons;
    }

    @Override
    public void setHideRibbons(boolean hideRibbons) {
        _hideRibbons = hideRibbons;
    }

    @JSON
    @Override
    public long getResourceArticleId() {
        return _resourceArticleId;
    }

    @Override
    public void setResourceArticleId(long resourceArticleId) {
        _resourceArticleId = resourceArticleId;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            Contest.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Contest toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Contest) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        ContestImpl contestImpl = new ContestImpl();

        contestImpl.setContestPK(getContestPK());
        contestImpl.setContestTypeId(getContestTypeId());
        contestImpl.setContestName(getContestName());
        contestImpl.setContestShortName(getContestShortName());
        contestImpl.setContestUrlName(getContestUrlName());
        contestImpl.setContestYear(getContestYear());
        contestImpl.setContestDescription(getContestDescription());
        contestImpl.setContestModelDescription(getContestModelDescription());
        contestImpl.setContestPositionsDescription(getContestPositionsDescription());
        contestImpl.setCreated(getCreated());
        contestImpl.setUpdated(getUpdated());
        contestImpl.setAuthorId(getAuthorId());
        contestImpl.setContestActive(getContestActive());
        contestImpl.setPlanTemplateId(getPlanTemplateId());
        contestImpl.setContestScheduleId(getContestScheduleId());
        contestImpl.setProposalCreationTemplateString(getProposalCreationTemplateString());
        contestImpl.setVoteTemplateString(getVoteTemplateString());
        contestImpl.setProposalVoteTemplateString(getProposalVoteTemplateString());
        contestImpl.setProposalVoteConfirmationTemplateString(getProposalVoteConfirmationTemplateString());
        contestImpl.setVoteQuestionTemplateString(getVoteQuestionTemplateString());
        contestImpl.setFocusAreaId(getFocusAreaId());
        contestImpl.setContestTier(getContestTier());
        contestImpl.setContestLogoId(getContestLogoId());
        contestImpl.setFeatured(getFeatured());
        contestImpl.setPlansOpenByDefault(getPlansOpenByDefault());
        contestImpl.setSponsorLogoId(getSponsorLogoId());
        contestImpl.setSponsorText(getSponsorText());
        contestImpl.setSponsorLink(getSponsorLink());
        contestImpl.setFlag(getFlag());
        contestImpl.setFlagText(getFlagText());
        contestImpl.setFlagTooltip(getFlagTooltip());
        contestImpl.setGroupId(getGroupId());
        contestImpl.setDiscussionGroupId(getDiscussionGroupId());
        contestImpl.setWeight(getWeight());
        contestImpl.setResourcesUrl(getResourcesUrl());
        contestImpl.setContestPrivate(getContestPrivate());
        contestImpl.setUsePermissions(getUsePermissions());
        contestImpl.setContestCreationStatus(getContestCreationStatus());
        contestImpl.setDefaultModelId(getDefaultModelId());
        contestImpl.setOtherModels(getOtherModels());
        contestImpl.setDefaultModelSettings(getDefaultModelSettings());
        contestImpl.setPoints(getPoints());
        contestImpl.setDefaultParentPointType(getDefaultParentPointType());
        contestImpl.setPointDistributionStrategy(getPointDistributionStrategy());
        contestImpl.setEmailTemplateUrl(getEmailTemplateUrl());
        contestImpl.setShow_in_tile_view(getShow_in_tile_view());
        contestImpl.setShow_in_list_view(getShow_in_list_view());
        contestImpl.setShow_in_outline_view(getShow_in_outline_view());
        contestImpl.setHideRibbons(getHideRibbons());
        contestImpl.setResourceArticleId(getResourceArticleId());

        contestImpl.resetOriginalValues();

        return contestImpl;
    }

    @Override
    public int compareTo(Contest contest) {
        int value = 0;

        if (getWeight() < contest.getWeight()) {
            value = -1;
        } else if (getWeight() > contest.getWeight()) {
            value = 1;
        } else {
            value = 0;
        }

        if (value != 0) {
            return value;
        }

        value = DateUtil.compareTo(getCreated(), contest.getCreated());

        if (value != 0) {
            return value;
        }

        return 0;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Contest)) {
            return false;
        }

        Contest contest = (Contest) obj;

        long primaryKey = contest.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        ContestModelImpl contestModelImpl = this;

        contestModelImpl._originalContestTypeId = contestModelImpl._contestTypeId;

        contestModelImpl._setOriginalContestTypeId = false;

        contestModelImpl._originalContestUrlName = contestModelImpl._ContestUrlName;

        contestModelImpl._originalContestYear = contestModelImpl._ContestYear;

        contestModelImpl._setOriginalContestYear = false;

        contestModelImpl._originalContestActive = contestModelImpl._contestActive;

        contestModelImpl._setOriginalContestActive = false;

        contestModelImpl._originalContestTier = contestModelImpl._contestTier;

        contestModelImpl._setOriginalContestTier = false;

        contestModelImpl._originalFeatured = contestModelImpl._featured;

        contestModelImpl._setOriginalFeatured = false;

        contestModelImpl._originalFlag = contestModelImpl._flag;

        contestModelImpl._setOriginalFlag = false;

        contestModelImpl._originalContestPrivate = contestModelImpl._contestPrivate;

        contestModelImpl._setOriginalContestPrivate = false;

        contestModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<Contest> toCacheModel() {
        ContestCacheModel contestCacheModel = new ContestCacheModel();

        contestCacheModel.ContestPK = getContestPK();

        contestCacheModel.contestTypeId = getContestTypeId();

        contestCacheModel.ContestName = getContestName();

        String ContestName = contestCacheModel.ContestName;

        if ((ContestName != null) && (ContestName.length() == 0)) {
            contestCacheModel.ContestName = null;
        }

        contestCacheModel.ContestShortName = getContestShortName();

        String ContestShortName = contestCacheModel.ContestShortName;

        if ((ContestShortName != null) && (ContestShortName.length() == 0)) {
            contestCacheModel.ContestShortName = null;
        }

        contestCacheModel.ContestUrlName = getContestUrlName();

        String ContestUrlName = contestCacheModel.ContestUrlName;

        if ((ContestUrlName != null) && (ContestUrlName.length() == 0)) {
            contestCacheModel.ContestUrlName = null;
        }

        contestCacheModel.ContestYear = getContestYear();

        contestCacheModel.ContestDescription = getContestDescription();

        String ContestDescription = contestCacheModel.ContestDescription;

        if ((ContestDescription != null) && (ContestDescription.length() == 0)) {
            contestCacheModel.ContestDescription = null;
        }

        contestCacheModel.ContestModelDescription = getContestModelDescription();

        String ContestModelDescription = contestCacheModel.ContestModelDescription;

        if ((ContestModelDescription != null) &&
                (ContestModelDescription.length() == 0)) {
            contestCacheModel.ContestModelDescription = null;
        }

        contestCacheModel.ContestPositionsDescription = getContestPositionsDescription();

        String ContestPositionsDescription = contestCacheModel.ContestPositionsDescription;

        if ((ContestPositionsDescription != null) &&
                (ContestPositionsDescription.length() == 0)) {
            contestCacheModel.ContestPositionsDescription = null;
        }

        Date created = getCreated();

        if (created != null) {
            contestCacheModel.created = created.getTime();
        } else {
            contestCacheModel.created = Long.MIN_VALUE;
        }

        Date updated = getUpdated();

        if (updated != null) {
            contestCacheModel.updated = updated.getTime();
        } else {
            contestCacheModel.updated = Long.MIN_VALUE;
        }

        contestCacheModel.authorId = getAuthorId();

        contestCacheModel.contestActive = getContestActive();

        contestCacheModel.planTemplateId = getPlanTemplateId();

        contestCacheModel.contestScheduleId = getContestScheduleId();

        contestCacheModel.proposalCreationTemplateString = getProposalCreationTemplateString();

        String proposalCreationTemplateString = contestCacheModel.proposalCreationTemplateString;

        if ((proposalCreationTemplateString != null) &&
                (proposalCreationTemplateString.length() == 0)) {
            contestCacheModel.proposalCreationTemplateString = null;
        }

        contestCacheModel.voteTemplateString = getVoteTemplateString();

        String voteTemplateString = contestCacheModel.voteTemplateString;

        if ((voteTemplateString != null) && (voteTemplateString.length() == 0)) {
            contestCacheModel.voteTemplateString = null;
        }

        contestCacheModel.proposalVoteTemplateString = getProposalVoteTemplateString();

        String proposalVoteTemplateString = contestCacheModel.proposalVoteTemplateString;

        if ((proposalVoteTemplateString != null) &&
                (proposalVoteTemplateString.length() == 0)) {
            contestCacheModel.proposalVoteTemplateString = null;
        }

        contestCacheModel.proposalVoteConfirmationTemplateString = getProposalVoteConfirmationTemplateString();

        String proposalVoteConfirmationTemplateString = contestCacheModel.proposalVoteConfirmationTemplateString;

        if ((proposalVoteConfirmationTemplateString != null) &&
                (proposalVoteConfirmationTemplateString.length() == 0)) {
            contestCacheModel.proposalVoteConfirmationTemplateString = null;
        }

        contestCacheModel.voteQuestionTemplateString = getVoteQuestionTemplateString();

        String voteQuestionTemplateString = contestCacheModel.voteQuestionTemplateString;

        if ((voteQuestionTemplateString != null) &&
                (voteQuestionTemplateString.length() == 0)) {
            contestCacheModel.voteQuestionTemplateString = null;
        }

        contestCacheModel.focusAreaId = getFocusAreaId();

        contestCacheModel.contestTier = getContestTier();

        contestCacheModel.contestLogoId = getContestLogoId();

        contestCacheModel.featured = getFeatured();

        contestCacheModel.plansOpenByDefault = getPlansOpenByDefault();

        contestCacheModel.sponsorLogoId = getSponsorLogoId();

        contestCacheModel.sponsorText = getSponsorText();

        String sponsorText = contestCacheModel.sponsorText;

        if ((sponsorText != null) && (sponsorText.length() == 0)) {
            contestCacheModel.sponsorText = null;
        }

        contestCacheModel.sponsorLink = getSponsorLink();

        String sponsorLink = contestCacheModel.sponsorLink;

        if ((sponsorLink != null) && (sponsorLink.length() == 0)) {
            contestCacheModel.sponsorLink = null;
        }

        contestCacheModel.flag = getFlag();

        contestCacheModel.flagText = getFlagText();

        String flagText = contestCacheModel.flagText;

        if ((flagText != null) && (flagText.length() == 0)) {
            contestCacheModel.flagText = null;
        }

        contestCacheModel.flagTooltip = getFlagTooltip();

        String flagTooltip = contestCacheModel.flagTooltip;

        if ((flagTooltip != null) && (flagTooltip.length() == 0)) {
            contestCacheModel.flagTooltip = null;
        }

        contestCacheModel.groupId = getGroupId();

        contestCacheModel.discussionGroupId = getDiscussionGroupId();

        contestCacheModel.weight = getWeight();

        contestCacheModel.resourcesUrl = getResourcesUrl();

        String resourcesUrl = contestCacheModel.resourcesUrl;

        if ((resourcesUrl != null) && (resourcesUrl.length() == 0)) {
            contestCacheModel.resourcesUrl = null;
        }

        contestCacheModel.contestPrivate = getContestPrivate();

        contestCacheModel.usePermissions = getUsePermissions();

        contestCacheModel.contestCreationStatus = getContestCreationStatus();

        String contestCreationStatus = contestCacheModel.contestCreationStatus;

        if ((contestCreationStatus != null) &&
                (contestCreationStatus.length() == 0)) {
            contestCacheModel.contestCreationStatus = null;
        }

        contestCacheModel.defaultModelId = getDefaultModelId();

        contestCacheModel.otherModels = getOtherModels();

        String otherModels = contestCacheModel.otherModels;

        if ((otherModels != null) && (otherModels.length() == 0)) {
            contestCacheModel.otherModels = null;
        }

        contestCacheModel.defaultModelSettings = getDefaultModelSettings();

        String defaultModelSettings = contestCacheModel.defaultModelSettings;

        if ((defaultModelSettings != null) &&
                (defaultModelSettings.length() == 0)) {
            contestCacheModel.defaultModelSettings = null;
        }

        contestCacheModel.points = getPoints();

        contestCacheModel.defaultParentPointType = getDefaultParentPointType();

        contestCacheModel.pointDistributionStrategy = getPointDistributionStrategy();

        String pointDistributionStrategy = contestCacheModel.pointDistributionStrategy;

        if ((pointDistributionStrategy != null) &&
                (pointDistributionStrategy.length() == 0)) {
            contestCacheModel.pointDistributionStrategy = null;
        }

        contestCacheModel.emailTemplateUrl = getEmailTemplateUrl();

        String emailTemplateUrl = contestCacheModel.emailTemplateUrl;

        if ((emailTemplateUrl != null) && (emailTemplateUrl.length() == 0)) {
            contestCacheModel.emailTemplateUrl = null;
        }

        contestCacheModel.show_in_tile_view = getShow_in_tile_view();

        contestCacheModel.show_in_list_view = getShow_in_list_view();

        contestCacheModel.show_in_outline_view = getShow_in_outline_view();

        contestCacheModel.hideRibbons = getHideRibbons();

        contestCacheModel.resourceArticleId = getResourceArticleId();

        return contestCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(101);

        sb.append("{ContestPK=");
        sb.append(getContestPK());
        sb.append(", contestTypeId=");
        sb.append(getContestTypeId());
        sb.append(", ContestName=");
        sb.append(getContestName());
        sb.append(", ContestShortName=");
        sb.append(getContestShortName());
        sb.append(", ContestUrlName=");
        sb.append(getContestUrlName());
        sb.append(", ContestYear=");
        sb.append(getContestYear());
        sb.append(", ContestDescription=");
        sb.append(getContestDescription());
        sb.append(", ContestModelDescription=");
        sb.append(getContestModelDescription());
        sb.append(", ContestPositionsDescription=");
        sb.append(getContestPositionsDescription());
        sb.append(", created=");
        sb.append(getCreated());
        sb.append(", updated=");
        sb.append(getUpdated());
        sb.append(", authorId=");
        sb.append(getAuthorId());
        sb.append(", contestActive=");
        sb.append(getContestActive());
        sb.append(", planTemplateId=");
        sb.append(getPlanTemplateId());
        sb.append(", contestScheduleId=");
        sb.append(getContestScheduleId());
        sb.append(", proposalCreationTemplateString=");
        sb.append(getProposalCreationTemplateString());
        sb.append(", voteTemplateString=");
        sb.append(getVoteTemplateString());
        sb.append(", proposalVoteTemplateString=");
        sb.append(getProposalVoteTemplateString());
        sb.append(", proposalVoteConfirmationTemplateString=");
        sb.append(getProposalVoteConfirmationTemplateString());
        sb.append(", voteQuestionTemplateString=");
        sb.append(getVoteQuestionTemplateString());
        sb.append(", focusAreaId=");
        sb.append(getFocusAreaId());
        sb.append(", contestTier=");
        sb.append(getContestTier());
        sb.append(", contestLogoId=");
        sb.append(getContestLogoId());
        sb.append(", featured=");
        sb.append(getFeatured());
        sb.append(", plansOpenByDefault=");
        sb.append(getPlansOpenByDefault());
        sb.append(", sponsorLogoId=");
        sb.append(getSponsorLogoId());
        sb.append(", sponsorText=");
        sb.append(getSponsorText());
        sb.append(", sponsorLink=");
        sb.append(getSponsorLink());
        sb.append(", flag=");
        sb.append(getFlag());
        sb.append(", flagText=");
        sb.append(getFlagText());
        sb.append(", flagTooltip=");
        sb.append(getFlagTooltip());
        sb.append(", groupId=");
        sb.append(getGroupId());
        sb.append(", discussionGroupId=");
        sb.append(getDiscussionGroupId());
        sb.append(", weight=");
        sb.append(getWeight());
        sb.append(", resourcesUrl=");
        sb.append(getResourcesUrl());
        sb.append(", contestPrivate=");
        sb.append(getContestPrivate());
        sb.append(", usePermissions=");
        sb.append(getUsePermissions());
        sb.append(", contestCreationStatus=");
        sb.append(getContestCreationStatus());
        sb.append(", defaultModelId=");
        sb.append(getDefaultModelId());
        sb.append(", otherModels=");
        sb.append(getOtherModels());
        sb.append(", defaultModelSettings=");
        sb.append(getDefaultModelSettings());
        sb.append(", points=");
        sb.append(getPoints());
        sb.append(", defaultParentPointType=");
        sb.append(getDefaultParentPointType());
        sb.append(", pointDistributionStrategy=");
        sb.append(getPointDistributionStrategy());
        sb.append(", emailTemplateUrl=");
        sb.append(getEmailTemplateUrl());
        sb.append(", show_in_tile_view=");
        sb.append(getShow_in_tile_view());
        sb.append(", show_in_list_view=");
        sb.append(getShow_in_list_view());
        sb.append(", show_in_outline_view=");
        sb.append(getShow_in_outline_view());
        sb.append(", hideRibbons=");
        sb.append(getHideRibbons());
        sb.append(", resourceArticleId=");
        sb.append(getResourceArticleId());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(154);

        sb.append("<model><model-name>");
        sb.append("com.ext.portlet.model.Contest");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>ContestPK</column-name><column-value><![CDATA[");
        sb.append(getContestPK());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>contestTypeId</column-name><column-value><![CDATA[");
        sb.append(getContestTypeId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>ContestName</column-name><column-value><![CDATA[");
        sb.append(getContestName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>ContestShortName</column-name><column-value><![CDATA[");
        sb.append(getContestShortName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>ContestUrlName</column-name><column-value><![CDATA[");
        sb.append(getContestUrlName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>ContestYear</column-name><column-value><![CDATA[");
        sb.append(getContestYear());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>ContestDescription</column-name><column-value><![CDATA[");
        sb.append(getContestDescription());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>ContestModelDescription</column-name><column-value><![CDATA[");
        sb.append(getContestModelDescription());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>ContestPositionsDescription</column-name><column-value><![CDATA[");
        sb.append(getContestPositionsDescription());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>created</column-name><column-value><![CDATA[");
        sb.append(getCreated());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>updated</column-name><column-value><![CDATA[");
        sb.append(getUpdated());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>authorId</column-name><column-value><![CDATA[");
        sb.append(getAuthorId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>contestActive</column-name><column-value><![CDATA[");
        sb.append(getContestActive());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>planTemplateId</column-name><column-value><![CDATA[");
        sb.append(getPlanTemplateId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>contestScheduleId</column-name><column-value><![CDATA[");
        sb.append(getContestScheduleId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>proposalCreationTemplateString</column-name><column-value><![CDATA[");
        sb.append(getProposalCreationTemplateString());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>voteTemplateString</column-name><column-value><![CDATA[");
        sb.append(getVoteTemplateString());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>proposalVoteTemplateString</column-name><column-value><![CDATA[");
        sb.append(getProposalVoteTemplateString());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>proposalVoteConfirmationTemplateString</column-name><column-value><![CDATA[");
        sb.append(getProposalVoteConfirmationTemplateString());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>voteQuestionTemplateString</column-name><column-value><![CDATA[");
        sb.append(getVoteQuestionTemplateString());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>focusAreaId</column-name><column-value><![CDATA[");
        sb.append(getFocusAreaId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>contestTier</column-name><column-value><![CDATA[");
        sb.append(getContestTier());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>contestLogoId</column-name><column-value><![CDATA[");
        sb.append(getContestLogoId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>featured</column-name><column-value><![CDATA[");
        sb.append(getFeatured());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>plansOpenByDefault</column-name><column-value><![CDATA[");
        sb.append(getPlansOpenByDefault());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>sponsorLogoId</column-name><column-value><![CDATA[");
        sb.append(getSponsorLogoId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>sponsorText</column-name><column-value><![CDATA[");
        sb.append(getSponsorText());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>sponsorLink</column-name><column-value><![CDATA[");
        sb.append(getSponsorLink());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>flag</column-name><column-value><![CDATA[");
        sb.append(getFlag());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>flagText</column-name><column-value><![CDATA[");
        sb.append(getFlagText());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>flagTooltip</column-name><column-value><![CDATA[");
        sb.append(getFlagTooltip());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>groupId</column-name><column-value><![CDATA[");
        sb.append(getGroupId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>discussionGroupId</column-name><column-value><![CDATA[");
        sb.append(getDiscussionGroupId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>weight</column-name><column-value><![CDATA[");
        sb.append(getWeight());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>resourcesUrl</column-name><column-value><![CDATA[");
        sb.append(getResourcesUrl());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>contestPrivate</column-name><column-value><![CDATA[");
        sb.append(getContestPrivate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>usePermissions</column-name><column-value><![CDATA[");
        sb.append(getUsePermissions());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>contestCreationStatus</column-name><column-value><![CDATA[");
        sb.append(getContestCreationStatus());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>defaultModelId</column-name><column-value><![CDATA[");
        sb.append(getDefaultModelId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>otherModels</column-name><column-value><![CDATA[");
        sb.append(getOtherModels());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>defaultModelSettings</column-name><column-value><![CDATA[");
        sb.append(getDefaultModelSettings());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>points</column-name><column-value><![CDATA[");
        sb.append(getPoints());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>defaultParentPointType</column-name><column-value><![CDATA[");
        sb.append(getDefaultParentPointType());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>pointDistributionStrategy</column-name><column-value><![CDATA[");
        sb.append(getPointDistributionStrategy());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>emailTemplateUrl</column-name><column-value><![CDATA[");
        sb.append(getEmailTemplateUrl());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>show_in_tile_view</column-name><column-value><![CDATA[");
        sb.append(getShow_in_tile_view());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>show_in_list_view</column-name><column-value><![CDATA[");
        sb.append(getShow_in_list_view());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>show_in_outline_view</column-name><column-value><![CDATA[");
        sb.append(getShow_in_outline_view());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>hideRibbons</column-name><column-value><![CDATA[");
        sb.append(getHideRibbons());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>resourceArticleId</column-name><column-value><![CDATA[");
        sb.append(getResourceArticleId());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
