package com.ext.portlet.model.impl;

import com.ext.portlet.model.ContestPhaseType;
import com.ext.portlet.model.ContestPhaseTypeModel;
import com.ext.portlet.model.ContestPhaseTypeSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.List;

/**
 * The base model implementation for the ContestPhaseType service. Represents a row in the &quot;xcolab_ContestPhaseType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ext.portlet.model.ContestPhaseTypeModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContestPhaseTypeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContestPhaseTypeImpl
 * @see com.ext.portlet.model.ContestPhaseType
 * @see com.ext.portlet.model.ContestPhaseTypeModel
 * @generated
 */
@JSON(strict = true)
public class ContestPhaseTypeModelImpl extends BaseModelImpl<ContestPhaseType>
    implements ContestPhaseTypeModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a contest phase type model instance should use the {@link com.ext.portlet.model.ContestPhaseType} interface instead.
     */
    public static final String TABLE_NAME = "xcolab_ContestPhaseType";
    public static final Object[][] TABLE_COLUMNS = {
            { "id_", Types.BIGINT },
            { "name", Types.VARCHAR },
            { "description", Types.VARCHAR },
            { "status", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table xcolab_ContestPhaseType (id_ LONG not null primary key,name VARCHAR(1024) null,description TEXT null,status VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table xcolab_ContestPhaseType";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.ext.portlet.model.ContestPhaseType"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.ext.portlet.model.ContestPhaseType"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.ext.portlet.model.ContestPhaseType"));
    private static ClassLoader _classLoader = ContestPhaseType.class.getClassLoader();
    private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
            ContestPhaseType.class
        };
    private long _id;
    private String _name;
    private String _description;
    private String _status;
    private transient ExpandoBridge _expandoBridge;
    private ContestPhaseType _escapedModelProxy;

    public ContestPhaseTypeModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static ContestPhaseType toModel(ContestPhaseTypeSoap soapModel) {
        ContestPhaseType model = new ContestPhaseTypeImpl();

        model.setId(soapModel.getId());
        model.setName(soapModel.getName());
        model.setDescription(soapModel.getDescription());
        model.setStatus(soapModel.getStatus());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<ContestPhaseType> toModels(
        ContestPhaseTypeSoap[] soapModels) {
        List<ContestPhaseType> models = new ArrayList<ContestPhaseType>(soapModels.length);

        for (ContestPhaseTypeSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    public long getPrimaryKey() {
        return _id;
    }

    public void setPrimaryKey(long primaryKey) {
        setId(primaryKey);
    }

    public Serializable getPrimaryKeyObj() {
        return new Long(_id);
    }

    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    public Class<?> getModelClass() {
        return ContestPhaseType.class;
    }

    public String getModelClassName() {
        return ContestPhaseType.class.getName();
    }

    @JSON
    public long getId() {
        return _id;
    }

    public void setId(long id) {
        _id = id;
    }

    @JSON
    public String getName() {
        if (_name == null) {
            return StringPool.BLANK;
        } else {
            return _name;
        }
    }

    public void setName(String name) {
        _name = name;
    }

    @JSON
    public String getDescription() {
        if (_description == null) {
            return StringPool.BLANK;
        } else {
            return _description;
        }
    }

    public void setDescription(String description) {
        _description = description;
    }

    @JSON
    public String getStatus() {
        if (_status == null) {
            return StringPool.BLANK;
        } else {
            return _status;
        }
    }

    public void setStatus(String status) {
        _status = status;
    }

    @Override
    public ContestPhaseType toEscapedModel() {
        if (_escapedModelProxy == null) {
            _escapedModelProxy = (ContestPhaseType) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelProxyInterfaces,
                    new AutoEscapeBeanHandler(this));
        }

        return _escapedModelProxy;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        if (_expandoBridge == null) {
            _expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
                    ContestPhaseType.class.getName(), getPrimaryKey());
        }

        return _expandoBridge;
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        getExpandoBridge().setAttributes(serviceContext);
    }

    @Override
    public Object clone() {
        ContestPhaseTypeImpl contestPhaseTypeImpl = new ContestPhaseTypeImpl();

        contestPhaseTypeImpl.setId(getId());
        contestPhaseTypeImpl.setName(getName());
        contestPhaseTypeImpl.setDescription(getDescription());
        contestPhaseTypeImpl.setStatus(getStatus());

        contestPhaseTypeImpl.resetOriginalValues();

        return contestPhaseTypeImpl;
    }

    public int compareTo(ContestPhaseType contestPhaseType) {
        long primaryKey = contestPhaseType.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }

        ContestPhaseType contestPhaseType = null;

        try {
            contestPhaseType = (ContestPhaseType) obj;
        } catch (ClassCastException cce) {
            return false;
        }

        long primaryKey = contestPhaseType.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<ContestPhaseType> toCacheModel() {
        ContestPhaseTypeCacheModel contestPhaseTypeCacheModel = new ContestPhaseTypeCacheModel();

        contestPhaseTypeCacheModel.id = getId();

        contestPhaseTypeCacheModel.name = getName();

        String name = contestPhaseTypeCacheModel.name;

        if ((name != null) && (name.length() == 0)) {
            contestPhaseTypeCacheModel.name = null;
        }

        contestPhaseTypeCacheModel.description = getDescription();

        String description = contestPhaseTypeCacheModel.description;

        if ((description != null) && (description.length() == 0)) {
            contestPhaseTypeCacheModel.description = null;
        }

        contestPhaseTypeCacheModel.status = getStatus();

        String status = contestPhaseTypeCacheModel.status;

        if ((status != null) && (status.length() == 0)) {
            contestPhaseTypeCacheModel.status = null;
        }

        return contestPhaseTypeCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(9);

        sb.append("{id=");
        sb.append(getId());
        sb.append(", name=");
        sb.append(getName());
        sb.append(", description=");
        sb.append(getDescription());
        sb.append(", status=");
        sb.append(getStatus());
        sb.append("}");

        return sb.toString();
    }

    public String toXmlString() {
        StringBundler sb = new StringBundler(16);

        sb.append("<model><model-name>");
        sb.append("com.ext.portlet.model.ContestPhaseType");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>id</column-name><column-value><![CDATA[");
        sb.append(getId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>name</column-name><column-value><![CDATA[");
        sb.append(getName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>description</column-name><column-value><![CDATA[");
        sb.append(getDescription());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>status</column-name><column-value><![CDATA[");
        sb.append(getStatus());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
