package com.ext.portlet.model.impl;

import com.ext.portlet.model.ImpactTemplateFocusAreaList;
import com.ext.portlet.model.ImpactTemplateFocusAreaListModel;
import com.ext.portlet.model.ImpactTemplateFocusAreaListSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ImpactTemplateFocusAreaList service. Represents a row in the &quot;xcolab_ImpactTemplateFocusAreaList&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ext.portlet.model.ImpactTemplateFocusAreaListModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ImpactTemplateFocusAreaListImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ImpactTemplateFocusAreaListImpl
 * @see com.ext.portlet.model.ImpactTemplateFocusAreaList
 * @see com.ext.portlet.model.ImpactTemplateFocusAreaListModel
 * @generated
 */
@JSON(strict = true)
public class ImpactTemplateFocusAreaListModelImpl extends BaseModelImpl<ImpactTemplateFocusAreaList>
    implements ImpactTemplateFocusAreaListModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a impact template focus area list model instance should use the {@link com.ext.portlet.model.ImpactTemplateFocusAreaList} interface instead.
     */
    public static final String TABLE_NAME = "xcolab_ImpactTemplateFocusAreaList";
    public static final Object[][] TABLE_COLUMNS = {
            { "focusAreaListId", Types.BIGINT },
            { "name", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table xcolab_ImpactTemplateFocusAreaList (focusAreaListId LONG not null primary key,name VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table xcolab_ImpactTemplateFocusAreaList";
    public static final String ORDER_BY_JPQL = " ORDER BY impactTemplateFocusAreaList.focusAreaListId ASC";
    public static final String ORDER_BY_SQL = " ORDER BY xcolab_ImpactTemplateFocusAreaList.focusAreaListId ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.ext.portlet.model.ImpactTemplateFocusAreaList"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.ext.portlet.model.ImpactTemplateFocusAreaList"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.ext.portlet.model.ImpactTemplateFocusAreaList"));
    private static ClassLoader _classLoader = ImpactTemplateFocusAreaList.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            ImpactTemplateFocusAreaList.class
        };
    private long _focusAreaListId;
    private String _name;
    private ImpactTemplateFocusAreaList _escapedModel;

    public ImpactTemplateFocusAreaListModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static ImpactTemplateFocusAreaList toModel(
        ImpactTemplateFocusAreaListSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        ImpactTemplateFocusAreaList model = new ImpactTemplateFocusAreaListImpl();

        model.setFocusAreaListId(soapModel.getFocusAreaListId());
        model.setName(soapModel.getName());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<ImpactTemplateFocusAreaList> toModels(
        ImpactTemplateFocusAreaListSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<ImpactTemplateFocusAreaList> models = new ArrayList<ImpactTemplateFocusAreaList>(soapModels.length);

        for (ImpactTemplateFocusAreaListSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _focusAreaListId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setFocusAreaListId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _focusAreaListId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return ImpactTemplateFocusAreaList.class;
    }

    @Override
    public String getModelClassName() {
        return ImpactTemplateFocusAreaList.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("focusAreaListId", getFocusAreaListId());
        attributes.put("name", getName());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long focusAreaListId = (Long) attributes.get("focusAreaListId");

        if (focusAreaListId != null) {
            setFocusAreaListId(focusAreaListId);
        }

        String name = (String) attributes.get("name");

        if (name != null) {
            setName(name);
        }
    }

    @JSON
    @Override
    public long getFocusAreaListId() {
        return _focusAreaListId;
    }

    @Override
    public void setFocusAreaListId(long focusAreaListId) {
        _focusAreaListId = focusAreaListId;
    }

    @JSON
    @Override
    public String getName() {
        if (_name == null) {
            return StringPool.BLANK;
        } else {
            return _name;
        }
    }

    @Override
    public void setName(String name) {
        _name = name;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            ImpactTemplateFocusAreaList.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public ImpactTemplateFocusAreaList toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (ImpactTemplateFocusAreaList) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        ImpactTemplateFocusAreaListImpl impactTemplateFocusAreaListImpl = new ImpactTemplateFocusAreaListImpl();

        impactTemplateFocusAreaListImpl.setFocusAreaListId(getFocusAreaListId());
        impactTemplateFocusAreaListImpl.setName(getName());

        impactTemplateFocusAreaListImpl.resetOriginalValues();

        return impactTemplateFocusAreaListImpl;
    }

    @Override
    public int compareTo(
        ImpactTemplateFocusAreaList impactTemplateFocusAreaList) {
        long primaryKey = impactTemplateFocusAreaList.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof ImpactTemplateFocusAreaList)) {
            return false;
        }

        ImpactTemplateFocusAreaList impactTemplateFocusAreaList = (ImpactTemplateFocusAreaList) obj;

        long primaryKey = impactTemplateFocusAreaList.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<ImpactTemplateFocusAreaList> toCacheModel() {
        ImpactTemplateFocusAreaListCacheModel impactTemplateFocusAreaListCacheModel =
            new ImpactTemplateFocusAreaListCacheModel();

        impactTemplateFocusAreaListCacheModel.focusAreaListId = getFocusAreaListId();

        impactTemplateFocusAreaListCacheModel.name = getName();

        String name = impactTemplateFocusAreaListCacheModel.name;

        if ((name != null) && (name.length() == 0)) {
            impactTemplateFocusAreaListCacheModel.name = null;
        }

        return impactTemplateFocusAreaListCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(5);

        sb.append("{focusAreaListId=");
        sb.append(getFocusAreaListId());
        sb.append(", name=");
        sb.append(getName());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(10);

        sb.append("<model><model-name>");
        sb.append("com.ext.portlet.model.ImpactTemplateFocusAreaList");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>focusAreaListId</column-name><column-value><![CDATA[");
        sb.append(getFocusAreaListId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>name</column-name><column-value><![CDATA[");
        sb.append(getName());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
