package com.ext.portlet.model.impl;

import com.ext.portlet.model.ImpactDefaultSeriesData;
import com.ext.portlet.service.ImpactDefaultSeriesDataLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the ImpactDefaultSeriesData service. Represents a row in the &quot;xcolab_ImpactDefaultSeriesData&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ImpactDefaultSeriesDataImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ImpactDefaultSeriesDataImpl
 * @see com.ext.portlet.model.ImpactDefaultSeriesData
 * @generated
 */
public abstract class ImpactDefaultSeriesDataBaseImpl
    extends ImpactDefaultSeriesDataModelImpl implements ImpactDefaultSeriesData {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a impact default series data model instance should use the {@link ImpactDefaultSeriesData} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ImpactDefaultSeriesDataLocalServiceUtil.addImpactDefaultSeriesData(this);
        } else {
            ImpactDefaultSeriesDataLocalServiceUtil.updateImpactDefaultSeriesData(this);
        }
    }
}
