package com.ext.portlet.model.impl;

import com.ext.portlet.model.MessagingMessage;
import com.ext.portlet.service.MessagingMessageLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the MessagingMessage service. Represents a row in the &quot;xcolab_MessagingMessage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MessagingMessageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MessagingMessageImpl
 * @see com.ext.portlet.model.MessagingMessage
 * @generated
 */
public abstract class MessagingMessageBaseImpl extends MessagingMessageModelImpl
    implements MessagingMessage {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a messaging message model instance should use the {@link MessagingMessage} interface instead.
     */
    public void persist() throws SystemException {
        if (this.isNew()) {
            MessagingMessageLocalServiceUtil.addMessagingMessage(this);
        } else {
            MessagingMessageLocalServiceUtil.updateMessagingMessage(this);
        }
    }
}
