package com.ext.portlet.model.impl;

import com.ext.portlet.model.MessageRecipientStatus;
import com.ext.portlet.service.MessageRecipientStatusLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the MessageRecipientStatus service. Represents a row in the &quot;xcolab_MessageRecipientStatus&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MessageRecipientStatusImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MessageRecipientStatusImpl
 * @see com.ext.portlet.model.MessageRecipientStatus
 * @generated
 */
public abstract class MessageRecipientStatusBaseImpl
    extends MessageRecipientStatusModelImpl implements MessageRecipientStatus {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a message recipient status model instance should use the {@link MessageRecipientStatus} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            MessageRecipientStatusLocalServiceUtil.addMessageRecipientStatus(this);
        } else {
            MessageRecipientStatusLocalServiceUtil.updateMessageRecipientStatus(this);
        }
    }
}
