package com.ext.portlet.model.impl;

import com.ext.portlet.model.ModelGlobalPreference;
import com.ext.portlet.service.ModelGlobalPreferenceLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the ModelGlobalPreference service. Represents a row in the &quot;xcolab_ModelGlobalPreference&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ModelGlobalPreferenceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ModelGlobalPreferenceImpl
 * @see com.ext.portlet.model.ModelGlobalPreference
 * @generated
 */
public abstract class ModelGlobalPreferenceBaseImpl
    extends ModelGlobalPreferenceModelImpl implements ModelGlobalPreference {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a model global preference model instance should use the {@link ModelGlobalPreference} interface instead.
     */
    public void persist() throws SystemException {
        if (this.isNew()) {
            ModelGlobalPreferenceLocalServiceUtil.addModelGlobalPreference(this);
        } else {
            ModelGlobalPreferenceLocalServiceUtil.updateModelGlobalPreference(this);
        }
    }
}
