package com.ext.portlet.model.impl;

import com.ext.portlet.model.PlanType;
import com.ext.portlet.model.PlanTypeModel;
import com.ext.portlet.model.PlanTypeSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the PlanType service. Represents a row in the &quot;xcolab_PlanType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ext.portlet.model.PlanTypeModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PlanTypeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PlanTypeImpl
 * @see com.ext.portlet.model.PlanType
 * @see com.ext.portlet.model.PlanTypeModel
 * @generated
 */
@JSON(strict = true)
public class PlanTypeModelImpl extends BaseModelImpl<PlanType>
    implements PlanTypeModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a plan type model instance should use the {@link com.ext.portlet.model.PlanType} interface instead.
     */
    public static final String TABLE_NAME = "xcolab_PlanType";
    public static final Object[][] TABLE_COLUMNS = {
            { "planTypeId", Types.BIGINT },
            { "name", Types.VARCHAR },
            { "description", Types.VARCHAR },
            { "modelId", Types.BIGINT },
            { "modelTypeName", Types.VARCHAR },
            { "published", Types.BOOLEAN },
            { "publishedCounterpartId", Types.BIGINT },
            { "isDefault", Types.BOOLEAN },
            { "defaultModelId", Types.BIGINT },
            { "defaultScenarioId", Types.BIGINT }
        };
    public static final String TABLE_SQL_CREATE = "create table xcolab_PlanType (planTypeId LONG not null primary key,name VARCHAR(75) null,description VARCHAR(2048) null,modelId LONG,modelTypeName VARCHAR(75) null,published BOOLEAN,publishedCounterpartId LONG,isDefault BOOLEAN,defaultModelId LONG,defaultScenarioId LONG)";
    public static final String TABLE_SQL_DROP = "drop table xcolab_PlanType";
    public static final String ORDER_BY_JPQL = " ORDER BY planType.planTypeId ASC";
    public static final String ORDER_BY_SQL = " ORDER BY xcolab_PlanType.planTypeId ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.ext.portlet.model.PlanType"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.ext.portlet.model.PlanType"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.ext.portlet.model.PlanType"),
            true);
    public static long ISDEFAULT_COLUMN_BITMASK = 1L;
    public static long PLANTYPEID_COLUMN_BITMASK = 2L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.ext.portlet.model.PlanType"));
    private static ClassLoader _classLoader = PlanType.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            PlanType.class
        };
    private long _planTypeId;
    private String _name;
    private String _description;
    private long _modelId;
    private String _modelTypeName;
    private boolean _published;
    private long _publishedCounterpartId;
    private boolean _isDefault;
    private boolean _originalIsDefault;
    private boolean _setOriginalIsDefault;
    private long _defaultModelId;
    private long _defaultScenarioId;
    private long _columnBitmask;
    private PlanType _escapedModel;

    public PlanTypeModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static PlanType toModel(PlanTypeSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        PlanType model = new PlanTypeImpl();

        model.setPlanTypeId(soapModel.getPlanTypeId());
        model.setName(soapModel.getName());
        model.setDescription(soapModel.getDescription());
        model.setModelId(soapModel.getModelId());
        model.setModelTypeName(soapModel.getModelTypeName());
        model.setPublished(soapModel.getPublished());
        model.setPublishedCounterpartId(soapModel.getPublishedCounterpartId());
        model.setIsDefault(soapModel.getIsDefault());
        model.setDefaultModelId(soapModel.getDefaultModelId());
        model.setDefaultScenarioId(soapModel.getDefaultScenarioId());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<PlanType> toModels(PlanTypeSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<PlanType> models = new ArrayList<PlanType>(soapModels.length);

        for (PlanTypeSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _planTypeId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setPlanTypeId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _planTypeId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return PlanType.class;
    }

    @Override
    public String getModelClassName() {
        return PlanType.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("planTypeId", getPlanTypeId());
        attributes.put("name", getName());
        attributes.put("description", getDescription());
        attributes.put("modelId", getModelId());
        attributes.put("modelTypeName", getModelTypeName());
        attributes.put("published", getPublished());
        attributes.put("publishedCounterpartId", getPublishedCounterpartId());
        attributes.put("isDefault", getIsDefault());
        attributes.put("defaultModelId", getDefaultModelId());
        attributes.put("defaultScenarioId", getDefaultScenarioId());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long planTypeId = (Long) attributes.get("planTypeId");

        if (planTypeId != null) {
            setPlanTypeId(planTypeId);
        }

        String name = (String) attributes.get("name");

        if (name != null) {
            setName(name);
        }

        String description = (String) attributes.get("description");

        if (description != null) {
            setDescription(description);
        }

        Long modelId = (Long) attributes.get("modelId");

        if (modelId != null) {
            setModelId(modelId);
        }

        String modelTypeName = (String) attributes.get("modelTypeName");

        if (modelTypeName != null) {
            setModelTypeName(modelTypeName);
        }

        Boolean published = (Boolean) attributes.get("published");

        if (published != null) {
            setPublished(published);
        }

        Long publishedCounterpartId = (Long) attributes.get(
                "publishedCounterpartId");

        if (publishedCounterpartId != null) {
            setPublishedCounterpartId(publishedCounterpartId);
        }

        Boolean isDefault = (Boolean) attributes.get("isDefault");

        if (isDefault != null) {
            setIsDefault(isDefault);
        }

        Long defaultModelId = (Long) attributes.get("defaultModelId");

        if (defaultModelId != null) {
            setDefaultModelId(defaultModelId);
        }

        Long defaultScenarioId = (Long) attributes.get("defaultScenarioId");

        if (defaultScenarioId != null) {
            setDefaultScenarioId(defaultScenarioId);
        }
    }

    @JSON
    @Override
    public long getPlanTypeId() {
        return _planTypeId;
    }

    @Override
    public void setPlanTypeId(long planTypeId) {
        _planTypeId = planTypeId;
    }

    @JSON
    @Override
    public String getName() {
        if (_name == null) {
            return StringPool.BLANK;
        } else {
            return _name;
        }
    }

    @Override
    public void setName(String name) {
        _name = name;
    }

    @JSON
    @Override
    public String getDescription() {
        if (_description == null) {
            return StringPool.BLANK;
        } else {
            return _description;
        }
    }

    @Override
    public void setDescription(String description) {
        _description = description;
    }

    @JSON
    @Override
    public long getModelId() {
        return _modelId;
    }

    @Override
    public void setModelId(long modelId) {
        _modelId = modelId;
    }

    @JSON
    @Override
    public String getModelTypeName() {
        if (_modelTypeName == null) {
            return StringPool.BLANK;
        } else {
            return _modelTypeName;
        }
    }

    @Override
    public void setModelTypeName(String modelTypeName) {
        _modelTypeName = modelTypeName;
    }

    @JSON
    @Override
    public boolean getPublished() {
        return _published;
    }

    @Override
    public boolean isPublished() {
        return _published;
    }

    @Override
    public void setPublished(boolean published) {
        _published = published;
    }

    @JSON
    @Override
    public long getPublishedCounterpartId() {
        return _publishedCounterpartId;
    }

    @Override
    public void setPublishedCounterpartId(long publishedCounterpartId) {
        _publishedCounterpartId = publishedCounterpartId;
    }

    @JSON
    @Override
    public boolean getIsDefault() {
        return _isDefault;
    }

    @Override
    public boolean isIsDefault() {
        return _isDefault;
    }

    @Override
    public void setIsDefault(boolean isDefault) {
        _columnBitmask |= ISDEFAULT_COLUMN_BITMASK;

        if (!_setOriginalIsDefault) {
            _setOriginalIsDefault = true;

            _originalIsDefault = _isDefault;
        }

        _isDefault = isDefault;
    }

    public boolean getOriginalIsDefault() {
        return _originalIsDefault;
    }

    @JSON
    @Override
    public long getDefaultModelId() {
        return _defaultModelId;
    }

    @Override
    public void setDefaultModelId(long defaultModelId) {
        _defaultModelId = defaultModelId;
    }

    @JSON
    @Override
    public long getDefaultScenarioId() {
        return _defaultScenarioId;
    }

    @Override
    public void setDefaultScenarioId(long defaultScenarioId) {
        _defaultScenarioId = defaultScenarioId;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            PlanType.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public PlanType toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (PlanType) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        PlanTypeImpl planTypeImpl = new PlanTypeImpl();

        planTypeImpl.setPlanTypeId(getPlanTypeId());
        planTypeImpl.setName(getName());
        planTypeImpl.setDescription(getDescription());
        planTypeImpl.setModelId(getModelId());
        planTypeImpl.setModelTypeName(getModelTypeName());
        planTypeImpl.setPublished(getPublished());
        planTypeImpl.setPublishedCounterpartId(getPublishedCounterpartId());
        planTypeImpl.setIsDefault(getIsDefault());
        planTypeImpl.setDefaultModelId(getDefaultModelId());
        planTypeImpl.setDefaultScenarioId(getDefaultScenarioId());

        planTypeImpl.resetOriginalValues();

        return planTypeImpl;
    }

    @Override
    public int compareTo(PlanType planType) {
        long primaryKey = planType.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof PlanType)) {
            return false;
        }

        PlanType planType = (PlanType) obj;

        long primaryKey = planType.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        PlanTypeModelImpl planTypeModelImpl = this;

        planTypeModelImpl._originalIsDefault = planTypeModelImpl._isDefault;

        planTypeModelImpl._setOriginalIsDefault = false;

        planTypeModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<PlanType> toCacheModel() {
        PlanTypeCacheModel planTypeCacheModel = new PlanTypeCacheModel();

        planTypeCacheModel.planTypeId = getPlanTypeId();

        planTypeCacheModel.name = getName();

        String name = planTypeCacheModel.name;

        if ((name != null) && (name.length() == 0)) {
            planTypeCacheModel.name = null;
        }

        planTypeCacheModel.description = getDescription();

        String description = planTypeCacheModel.description;

        if ((description != null) && (description.length() == 0)) {
            planTypeCacheModel.description = null;
        }

        planTypeCacheModel.modelId = getModelId();

        planTypeCacheModel.modelTypeName = getModelTypeName();

        String modelTypeName = planTypeCacheModel.modelTypeName;

        if ((modelTypeName != null) && (modelTypeName.length() == 0)) {
            planTypeCacheModel.modelTypeName = null;
        }

        planTypeCacheModel.published = getPublished();

        planTypeCacheModel.publishedCounterpartId = getPublishedCounterpartId();

        planTypeCacheModel.isDefault = getIsDefault();

        planTypeCacheModel.defaultModelId = getDefaultModelId();

        planTypeCacheModel.defaultScenarioId = getDefaultScenarioId();

        return planTypeCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(21);

        sb.append("{planTypeId=");
        sb.append(getPlanTypeId());
        sb.append(", name=");
        sb.append(getName());
        sb.append(", description=");
        sb.append(getDescription());
        sb.append(", modelId=");
        sb.append(getModelId());
        sb.append(", modelTypeName=");
        sb.append(getModelTypeName());
        sb.append(", published=");
        sb.append(getPublished());
        sb.append(", publishedCounterpartId=");
        sb.append(getPublishedCounterpartId());
        sb.append(", isDefault=");
        sb.append(getIsDefault());
        sb.append(", defaultModelId=");
        sb.append(getDefaultModelId());
        sb.append(", defaultScenarioId=");
        sb.append(getDefaultScenarioId());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(34);

        sb.append("<model><model-name>");
        sb.append("com.ext.portlet.model.PlanType");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>planTypeId</column-name><column-value><![CDATA[");
        sb.append(getPlanTypeId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>name</column-name><column-value><![CDATA[");
        sb.append(getName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>description</column-name><column-value><![CDATA[");
        sb.append(getDescription());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modelId</column-name><column-value><![CDATA[");
        sb.append(getModelId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modelTypeName</column-name><column-value><![CDATA[");
        sb.append(getModelTypeName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>published</column-name><column-value><![CDATA[");
        sb.append(getPublished());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>publishedCounterpartId</column-name><column-value><![CDATA[");
        sb.append(getPublishedCounterpartId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>isDefault</column-name><column-value><![CDATA[");
        sb.append(getIsDefault());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>defaultModelId</column-name><column-value><![CDATA[");
        sb.append(getDefaultModelId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>defaultScenarioId</column-name><column-value><![CDATA[");
        sb.append(getDefaultScenarioId());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
