package com.ext.portlet.model.impl;

import com.ext.portlet.model.PlanTeamHistory;
import com.ext.portlet.model.PlanTeamHistoryModel;
import com.ext.portlet.model.PlanTeamHistorySoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the PlanTeamHistory service. Represents a row in the &quot;xcolab_PlanTeamHistory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ext.portlet.model.PlanTeamHistoryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PlanTeamHistoryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PlanTeamHistoryImpl
 * @see com.ext.portlet.model.PlanTeamHistory
 * @see com.ext.portlet.model.PlanTeamHistoryModel
 * @generated
 */
@JSON(strict = true)
public class PlanTeamHistoryModelImpl extends BaseModelImpl<PlanTeamHistory>
    implements PlanTeamHistoryModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a plan team history model instance should use the {@link com.ext.portlet.model.PlanTeamHistory} interface instead.
     */
    public static final String TABLE_NAME = "xcolab_PlanTeamHistory";
    public static final Object[][] TABLE_COLUMNS = {
            { "id_", Types.BIGINT },
            { "planId", Types.BIGINT },
            { "userId", Types.BIGINT },
            { "action", Types.VARCHAR },
            { "payload", Types.VARCHAR },
            { "created", Types.TIMESTAMP },
            { "updateAuthorId", Types.BIGINT }
        };
    public static final String TABLE_SQL_CREATE = "create table xcolab_PlanTeamHistory (id_ LONG not null primary key,planId LONG,userId LONG,action VARCHAR(75) null,payload VARCHAR(75) null,created DATE null,updateAuthorId LONG)";
    public static final String TABLE_SQL_DROP = "drop table xcolab_PlanTeamHistory";
    public static final String ORDER_BY_JPQL = " ORDER BY planTeamHistory.id ASC";
    public static final String ORDER_BY_SQL = " ORDER BY xcolab_PlanTeamHistory.id_ ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.ext.portlet.model.PlanTeamHistory"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.ext.portlet.model.PlanTeamHistory"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.ext.portlet.model.PlanTeamHistory"),
            true);
    public static long PLANID_COLUMN_BITMASK = 1L;
    public static long USERID_COLUMN_BITMASK = 2L;
    public static long ID_COLUMN_BITMASK = 4L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.ext.portlet.model.PlanTeamHistory"));
    private static ClassLoader _classLoader = PlanTeamHistory.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            PlanTeamHistory.class
        };
    private long _id;
    private long _planId;
    private long _originalPlanId;
    private boolean _setOriginalPlanId;
    private long _userId;
    private String _userUuid;
    private long _originalUserId;
    private boolean _setOriginalUserId;
    private String _action;
    private String _payload;
    private Date _created;
    private long _updateAuthorId;
    private long _columnBitmask;
    private PlanTeamHistory _escapedModel;

    public PlanTeamHistoryModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static PlanTeamHistory toModel(PlanTeamHistorySoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        PlanTeamHistory model = new PlanTeamHistoryImpl();

        model.setId(soapModel.getId());
        model.setPlanId(soapModel.getPlanId());
        model.setUserId(soapModel.getUserId());
        model.setAction(soapModel.getAction());
        model.setPayload(soapModel.getPayload());
        model.setCreated(soapModel.getCreated());
        model.setUpdateAuthorId(soapModel.getUpdateAuthorId());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<PlanTeamHistory> toModels(
        PlanTeamHistorySoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<PlanTeamHistory> models = new ArrayList<PlanTeamHistory>(soapModels.length);

        for (PlanTeamHistorySoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _id;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _id;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return PlanTeamHistory.class;
    }

    @Override
    public String getModelClassName() {
        return PlanTeamHistory.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("id", getId());
        attributes.put("planId", getPlanId());
        attributes.put("userId", getUserId());
        attributes.put("action", getAction());
        attributes.put("payload", getPayload());
        attributes.put("created", getCreated());
        attributes.put("updateAuthorId", getUpdateAuthorId());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long id = (Long) attributes.get("id");

        if (id != null) {
            setId(id);
        }

        Long planId = (Long) attributes.get("planId");

        if (planId != null) {
            setPlanId(planId);
        }

        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        String action = (String) attributes.get("action");

        if (action != null) {
            setAction(action);
        }

        String payload = (String) attributes.get("payload");

        if (payload != null) {
            setPayload(payload);
        }

        Date created = (Date) attributes.get("created");

        if (created != null) {
            setCreated(created);
        }

        Long updateAuthorId = (Long) attributes.get("updateAuthorId");

        if (updateAuthorId != null) {
            setUpdateAuthorId(updateAuthorId);
        }
    }

    @JSON
    @Override
    public long getId() {
        return _id;
    }

    @Override
    public void setId(long id) {
        _columnBitmask = -1L;

        _id = id;
    }

    @JSON
    @Override
    public long getPlanId() {
        return _planId;
    }

    @Override
    public void setPlanId(long planId) {
        _columnBitmask |= PLANID_COLUMN_BITMASK;

        if (!_setOriginalPlanId) {
            _setOriginalPlanId = true;

            _originalPlanId = _planId;
        }

        _planId = planId;
    }

    public long getOriginalPlanId() {
        return _originalPlanId;
    }

    @JSON
    @Override
    public long getUserId() {
        return _userId;
    }

    @Override
    public void setUserId(long userId) {
        _columnBitmask |= USERID_COLUMN_BITMASK;

        if (!_setOriginalUserId) {
            _setOriginalUserId = true;

            _originalUserId = _userId;
        }

        _userId = userId;
    }

    @Override
    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    @Override
    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    public long getOriginalUserId() {
        return _originalUserId;
    }

    @JSON
    @Override
    public String getAction() {
        if (_action == null) {
            return StringPool.BLANK;
        } else {
            return _action;
        }
    }

    @Override
    public void setAction(String action) {
        _action = action;
    }

    @JSON
    @Override
    public String getPayload() {
        if (_payload == null) {
            return StringPool.BLANK;
        } else {
            return _payload;
        }
    }

    @Override
    public void setPayload(String payload) {
        _payload = payload;
    }

    @JSON
    @Override
    public Date getCreated() {
        return _created;
    }

    @Override
    public void setCreated(Date created) {
        _created = created;
    }

    @JSON
    @Override
    public long getUpdateAuthorId() {
        return _updateAuthorId;
    }

    @Override
    public void setUpdateAuthorId(long updateAuthorId) {
        _updateAuthorId = updateAuthorId;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            PlanTeamHistory.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public PlanTeamHistory toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (PlanTeamHistory) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        PlanTeamHistoryImpl planTeamHistoryImpl = new PlanTeamHistoryImpl();

        planTeamHistoryImpl.setId(getId());
        planTeamHistoryImpl.setPlanId(getPlanId());
        planTeamHistoryImpl.setUserId(getUserId());
        planTeamHistoryImpl.setAction(getAction());
        planTeamHistoryImpl.setPayload(getPayload());
        planTeamHistoryImpl.setCreated(getCreated());
        planTeamHistoryImpl.setUpdateAuthorId(getUpdateAuthorId());

        planTeamHistoryImpl.resetOriginalValues();

        return planTeamHistoryImpl;
    }

    @Override
    public int compareTo(PlanTeamHistory planTeamHistory) {
        int value = 0;

        if (getId() < planTeamHistory.getId()) {
            value = -1;
        } else if (getId() > planTeamHistory.getId()) {
            value = 1;
        } else {
            value = 0;
        }

        if (value != 0) {
            return value;
        }

        return 0;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof PlanTeamHistory)) {
            return false;
        }

        PlanTeamHistory planTeamHistory = (PlanTeamHistory) obj;

        long primaryKey = planTeamHistory.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        PlanTeamHistoryModelImpl planTeamHistoryModelImpl = this;

        planTeamHistoryModelImpl._originalPlanId = planTeamHistoryModelImpl._planId;

        planTeamHistoryModelImpl._setOriginalPlanId = false;

        planTeamHistoryModelImpl._originalUserId = planTeamHistoryModelImpl._userId;

        planTeamHistoryModelImpl._setOriginalUserId = false;

        planTeamHistoryModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<PlanTeamHistory> toCacheModel() {
        PlanTeamHistoryCacheModel planTeamHistoryCacheModel = new PlanTeamHistoryCacheModel();

        planTeamHistoryCacheModel.id = getId();

        planTeamHistoryCacheModel.planId = getPlanId();

        planTeamHistoryCacheModel.userId = getUserId();

        planTeamHistoryCacheModel.action = getAction();

        String action = planTeamHistoryCacheModel.action;

        if ((action != null) && (action.length() == 0)) {
            planTeamHistoryCacheModel.action = null;
        }

        planTeamHistoryCacheModel.payload = getPayload();

        String payload = planTeamHistoryCacheModel.payload;

        if ((payload != null) && (payload.length() == 0)) {
            planTeamHistoryCacheModel.payload = null;
        }

        Date created = getCreated();

        if (created != null) {
            planTeamHistoryCacheModel.created = created.getTime();
        } else {
            planTeamHistoryCacheModel.created = Long.MIN_VALUE;
        }

        planTeamHistoryCacheModel.updateAuthorId = getUpdateAuthorId();

        return planTeamHistoryCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(15);

        sb.append("{id=");
        sb.append(getId());
        sb.append(", planId=");
        sb.append(getPlanId());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", action=");
        sb.append(getAction());
        sb.append(", payload=");
        sb.append(getPayload());
        sb.append(", created=");
        sb.append(getCreated());
        sb.append(", updateAuthorId=");
        sb.append(getUpdateAuthorId());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(25);

        sb.append("<model><model-name>");
        sb.append("com.ext.portlet.model.PlanTeamHistory");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>id</column-name><column-value><![CDATA[");
        sb.append(getId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>planId</column-name><column-value><![CDATA[");
        sb.append(getPlanId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>action</column-name><column-value><![CDATA[");
        sb.append(getAction());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>payload</column-name><column-value><![CDATA[");
        sb.append(getPayload());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>created</column-name><column-value><![CDATA[");
        sb.append(getCreated());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>updateAuthorId</column-name><column-value><![CDATA[");
        sb.append(getUpdateAuthorId());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
