package com.ext.portlet.model.impl;

import com.ext.portlet.model.PlanDescription;
import com.ext.portlet.model.PlanDescriptionModel;
import com.ext.portlet.model.PlanDescriptionSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the PlanDescription service. Represents a row in the &quot;xcolab_PlanDescription&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ext.portlet.model.PlanDescriptionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PlanDescriptionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PlanDescriptionImpl
 * @see com.ext.portlet.model.PlanDescription
 * @see com.ext.portlet.model.PlanDescriptionModel
 * @generated
 */
@JSON(strict = true)
public class PlanDescriptionModelImpl extends BaseModelImpl<PlanDescription>
    implements PlanDescriptionModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a plan description model instance should use the {@link com.ext.portlet.model.PlanDescription} interface instead.
     */
    public static final String TABLE_NAME = "xcolab_PlanDescription";
    public static final Object[][] TABLE_COLUMNS = {
            { "id_", Types.BIGINT },
            { "planId", Types.BIGINT },
            { "name", Types.VARCHAR },
            { "description", Types.CLOB },
            { "version", Types.BIGINT },
            { "planVersion", Types.BIGINT },
            { "created", Types.TIMESTAMP },
            { "updateAuthorId", Types.BIGINT },
            { "image", Types.BIGINT },
            { "pitch", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table xcolab_PlanDescription (id_ LONG not null primary key,planId LONG,name VARCHAR(1024) null,description TEXT null,version LONG,planVersion LONG,created DATE null,updateAuthorId LONG,image LONG,pitch VARCHAR(2048) null)";
    public static final String TABLE_SQL_DROP = "drop table xcolab_PlanDescription";
    public static final String ORDER_BY_JPQL = " ORDER BY planDescription.id DESC";
    public static final String ORDER_BY_SQL = " ORDER BY xcolab_PlanDescription.id_ DESC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.ext.portlet.model.PlanDescription"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.ext.portlet.model.PlanDescription"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.ext.portlet.model.PlanDescription"),
            true);
    public static long PLANID_COLUMN_BITMASK = 1L;
    public static long PLANVERSION_COLUMN_BITMASK = 2L;
    public static long ID_COLUMN_BITMASK = 4L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.ext.portlet.model.PlanDescription"));
    private static ClassLoader _classLoader = PlanDescription.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            PlanDescription.class
        };
    private long _id;
    private long _planId;
    private long _originalPlanId;
    private boolean _setOriginalPlanId;
    private String _name;
    private String _description;
    private long _version;
    private long _planVersion;
    private long _originalPlanVersion;
    private boolean _setOriginalPlanVersion;
    private Date _created;
    private long _updateAuthorId;
    private long _image;
    private String _pitch;
    private long _columnBitmask;
    private PlanDescription _escapedModel;

    public PlanDescriptionModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static PlanDescription toModel(PlanDescriptionSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        PlanDescription model = new PlanDescriptionImpl();

        model.setId(soapModel.getId());
        model.setPlanId(soapModel.getPlanId());
        model.setName(soapModel.getName());
        model.setDescription(soapModel.getDescription());
        model.setVersion(soapModel.getVersion());
        model.setPlanVersion(soapModel.getPlanVersion());
        model.setCreated(soapModel.getCreated());
        model.setUpdateAuthorId(soapModel.getUpdateAuthorId());
        model.setImage(soapModel.getImage());
        model.setPitch(soapModel.getPitch());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<PlanDescription> toModels(
        PlanDescriptionSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<PlanDescription> models = new ArrayList<PlanDescription>(soapModels.length);

        for (PlanDescriptionSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _id;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _id;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return PlanDescription.class;
    }

    @Override
    public String getModelClassName() {
        return PlanDescription.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("id", getId());
        attributes.put("planId", getPlanId());
        attributes.put("name", getName());
        attributes.put("description", getDescription());
        attributes.put("version", getVersion());
        attributes.put("planVersion", getPlanVersion());
        attributes.put("created", getCreated());
        attributes.put("updateAuthorId", getUpdateAuthorId());
        attributes.put("image", getImage());
        attributes.put("pitch", getPitch());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long id = (Long) attributes.get("id");

        if (id != null) {
            setId(id);
        }

        Long planId = (Long) attributes.get("planId");

        if (planId != null) {
            setPlanId(planId);
        }

        String name = (String) attributes.get("name");

        if (name != null) {
            setName(name);
        }

        String description = (String) attributes.get("description");

        if (description != null) {
            setDescription(description);
        }

        Long version = (Long) attributes.get("version");

        if (version != null) {
            setVersion(version);
        }

        Long planVersion = (Long) attributes.get("planVersion");

        if (planVersion != null) {
            setPlanVersion(planVersion);
        }

        Date created = (Date) attributes.get("created");

        if (created != null) {
            setCreated(created);
        }

        Long updateAuthorId = (Long) attributes.get("updateAuthorId");

        if (updateAuthorId != null) {
            setUpdateAuthorId(updateAuthorId);
        }

        Long image = (Long) attributes.get("image");

        if (image != null) {
            setImage(image);
        }

        String pitch = (String) attributes.get("pitch");

        if (pitch != null) {
            setPitch(pitch);
        }
    }

    @JSON
    @Override
    public long getId() {
        return _id;
    }

    @Override
    public void setId(long id) {
        _columnBitmask = -1L;

        _id = id;
    }

    @JSON
    @Override
    public long getPlanId() {
        return _planId;
    }

    @Override
    public void setPlanId(long planId) {
        _columnBitmask |= PLANID_COLUMN_BITMASK;

        if (!_setOriginalPlanId) {
            _setOriginalPlanId = true;

            _originalPlanId = _planId;
        }

        _planId = planId;
    }

    public long getOriginalPlanId() {
        return _originalPlanId;
    }

    @JSON
    @Override
    public String getName() {
        if (_name == null) {
            return StringPool.BLANK;
        } else {
            return _name;
        }
    }

    @Override
    public void setName(String name) {
        _name = name;
    }

    @JSON
    @Override
    public String getDescription() {
        if (_description == null) {
            return StringPool.BLANK;
        } else {
            return _description;
        }
    }

    @Override
    public void setDescription(String description) {
        _description = description;
    }

    @JSON
    @Override
    public long getVersion() {
        return _version;
    }

    @Override
    public void setVersion(long version) {
        _version = version;
    }

    @JSON
    @Override
    public long getPlanVersion() {
        return _planVersion;
    }

    @Override
    public void setPlanVersion(long planVersion) {
        _columnBitmask |= PLANVERSION_COLUMN_BITMASK;

        if (!_setOriginalPlanVersion) {
            _setOriginalPlanVersion = true;

            _originalPlanVersion = _planVersion;
        }

        _planVersion = planVersion;
    }

    public long getOriginalPlanVersion() {
        return _originalPlanVersion;
    }

    @JSON
    @Override
    public Date getCreated() {
        return _created;
    }

    @Override
    public void setCreated(Date created) {
        _created = created;
    }

    @JSON
    @Override
    public long getUpdateAuthorId() {
        return _updateAuthorId;
    }

    @Override
    public void setUpdateAuthorId(long updateAuthorId) {
        _updateAuthorId = updateAuthorId;
    }

    @JSON
    @Override
    public long getImage() {
        return _image;
    }

    @Override
    public void setImage(long image) {
        _image = image;
    }

    @JSON
    @Override
    public String getPitch() {
        if (_pitch == null) {
            return StringPool.BLANK;
        } else {
            return _pitch;
        }
    }

    @Override
    public void setPitch(String pitch) {
        _pitch = pitch;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            PlanDescription.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public PlanDescription toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (PlanDescription) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        PlanDescriptionImpl planDescriptionImpl = new PlanDescriptionImpl();

        planDescriptionImpl.setId(getId());
        planDescriptionImpl.setPlanId(getPlanId());
        planDescriptionImpl.setName(getName());
        planDescriptionImpl.setDescription(getDescription());
        planDescriptionImpl.setVersion(getVersion());
        planDescriptionImpl.setPlanVersion(getPlanVersion());
        planDescriptionImpl.setCreated(getCreated());
        planDescriptionImpl.setUpdateAuthorId(getUpdateAuthorId());
        planDescriptionImpl.setImage(getImage());
        planDescriptionImpl.setPitch(getPitch());

        planDescriptionImpl.resetOriginalValues();

        return planDescriptionImpl;
    }

    @Override
    public int compareTo(PlanDescription planDescription) {
        int value = 0;

        if (getId() < planDescription.getId()) {
            value = -1;
        } else if (getId() > planDescription.getId()) {
            value = 1;
        } else {
            value = 0;
        }

        value = value * -1;

        if (value != 0) {
            return value;
        }

        return 0;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof PlanDescription)) {
            return false;
        }

        PlanDescription planDescription = (PlanDescription) obj;

        long primaryKey = planDescription.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        PlanDescriptionModelImpl planDescriptionModelImpl = this;

        planDescriptionModelImpl._originalPlanId = planDescriptionModelImpl._planId;

        planDescriptionModelImpl._setOriginalPlanId = false;

        planDescriptionModelImpl._originalPlanVersion = planDescriptionModelImpl._planVersion;

        planDescriptionModelImpl._setOriginalPlanVersion = false;

        planDescriptionModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<PlanDescription> toCacheModel() {
        PlanDescriptionCacheModel planDescriptionCacheModel = new PlanDescriptionCacheModel();

        planDescriptionCacheModel.id = getId();

        planDescriptionCacheModel.planId = getPlanId();

        planDescriptionCacheModel.name = getName();

        String name = planDescriptionCacheModel.name;

        if ((name != null) && (name.length() == 0)) {
            planDescriptionCacheModel.name = null;
        }

        planDescriptionCacheModel.description = getDescription();

        String description = planDescriptionCacheModel.description;

        if ((description != null) && (description.length() == 0)) {
            planDescriptionCacheModel.description = null;
        }

        planDescriptionCacheModel.version = getVersion();

        planDescriptionCacheModel.planVersion = getPlanVersion();

        Date created = getCreated();

        if (created != null) {
            planDescriptionCacheModel.created = created.getTime();
        } else {
            planDescriptionCacheModel.created = Long.MIN_VALUE;
        }

        planDescriptionCacheModel.updateAuthorId = getUpdateAuthorId();

        planDescriptionCacheModel.image = getImage();

        planDescriptionCacheModel.pitch = getPitch();

        String pitch = planDescriptionCacheModel.pitch;

        if ((pitch != null) && (pitch.length() == 0)) {
            planDescriptionCacheModel.pitch = null;
        }

        return planDescriptionCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(21);

        sb.append("{id=");
        sb.append(getId());
        sb.append(", planId=");
        sb.append(getPlanId());
        sb.append(", name=");
        sb.append(getName());
        sb.append(", description=");
        sb.append(getDescription());
        sb.append(", version=");
        sb.append(getVersion());
        sb.append(", planVersion=");
        sb.append(getPlanVersion());
        sb.append(", created=");
        sb.append(getCreated());
        sb.append(", updateAuthorId=");
        sb.append(getUpdateAuthorId());
        sb.append(", image=");
        sb.append(getImage());
        sb.append(", pitch=");
        sb.append(getPitch());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(34);

        sb.append("<model><model-name>");
        sb.append("com.ext.portlet.model.PlanDescription");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>id</column-name><column-value><![CDATA[");
        sb.append(getId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>planId</column-name><column-value><![CDATA[");
        sb.append(getPlanId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>name</column-name><column-value><![CDATA[");
        sb.append(getName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>description</column-name><column-value><![CDATA[");
        sb.append(getDescription());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>version</column-name><column-value><![CDATA[");
        sb.append(getVersion());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>planVersion</column-name><column-value><![CDATA[");
        sb.append(getPlanVersion());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>created</column-name><column-value><![CDATA[");
        sb.append(getCreated());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>updateAuthorId</column-name><column-value><![CDATA[");
        sb.append(getUpdateAuthorId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>image</column-name><column-value><![CDATA[");
        sb.append(getImage());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>pitch</column-name><column-value><![CDATA[");
        sb.append(getPitch());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
