package com.ext.portlet.model.impl;

import com.ext.portlet.model.ProposalRatingType;
import com.ext.portlet.service.ProposalRatingTypeLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the ProposalRatingType service. Represents a row in the &quot;xcolab_ProposalRatingType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProposalRatingTypeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProposalRatingTypeImpl
 * @see com.ext.portlet.model.ProposalRatingType
 * @generated
 */
public abstract class ProposalRatingTypeBaseImpl
    extends ProposalRatingTypeModelImpl implements ProposalRatingType {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a proposal rating type model instance should use the {@link ProposalRatingType} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ProposalRatingTypeLocalServiceUtil.addProposalRatingType(this);
        } else {
            ProposalRatingTypeLocalServiceUtil.updateProposalRatingType(this);
        }
    }
}
