package com.ext.portlet.model.impl;

import com.ext.portlet.model.ProposalContestPhaseAttributeType;
import com.ext.portlet.model.ProposalContestPhaseAttributeTypeModel;
import com.ext.portlet.model.ProposalContestPhaseAttributeTypeSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.List;

/**
 * The base model implementation for the ProposalContestPhaseAttributeType service. Represents a row in the &quot;xcolab_ProposalContestPhaseAttributeType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ext.portlet.model.ProposalContestPhaseAttributeTypeModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProposalContestPhaseAttributeTypeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProposalContestPhaseAttributeTypeImpl
 * @see com.ext.portlet.model.ProposalContestPhaseAttributeType
 * @see com.ext.portlet.model.ProposalContestPhaseAttributeTypeModel
 * @generated
 */
@JSON(strict = true)
public class ProposalContestPhaseAttributeTypeModelImpl extends BaseModelImpl<ProposalContestPhaseAttributeType>
    implements ProposalContestPhaseAttributeTypeModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a proposal contest phase attribute type model instance should use the {@link com.ext.portlet.model.ProposalContestPhaseAttributeType} interface instead.
     */
    public static final String TABLE_NAME = "xcolab_ProposalContestPhaseAttributeType";
    public static final Object[][] TABLE_COLUMNS = {
            { "id_", Types.BIGINT },
            { "ribbon", Types.VARCHAR },
            { "hoverText", Types.VARCHAR },
            { "description", Types.VARCHAR },
            { "copyOnPromote", Types.BOOLEAN }
        };
    public static final String TABLE_SQL_CREATE = "create table xcolab_ProposalContestPhaseAttributeType (id_ LONG not null primary key,ribbon VARCHAR(75) null,hoverText VARCHAR(75) null,description VARCHAR(75) null,copyOnPromote BOOLEAN)";
    public static final String TABLE_SQL_DROP = "drop table xcolab_ProposalContestPhaseAttributeType";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.ext.portlet.model.ProposalContestPhaseAttributeType"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.ext.portlet.model.ProposalContestPhaseAttributeType"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.ext.portlet.model.ProposalContestPhaseAttributeType"));
    private static ClassLoader _classLoader = ProposalContestPhaseAttributeType.class.getClassLoader();
    private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
            ProposalContestPhaseAttributeType.class
        };
    private long _id;
    private String _ribbon;
    private String _hoverText;
    private String _description;
    private boolean _copyOnPromote;
    private transient ExpandoBridge _expandoBridge;
    private ProposalContestPhaseAttributeType _escapedModelProxy;

    public ProposalContestPhaseAttributeTypeModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static ProposalContestPhaseAttributeType toModel(
        ProposalContestPhaseAttributeTypeSoap soapModel) {
        ProposalContestPhaseAttributeType model = new ProposalContestPhaseAttributeTypeImpl();

        model.setId(soapModel.getId());
        model.setRibbon(soapModel.getRibbon());
        model.setHoverText(soapModel.getHoverText());
        model.setDescription(soapModel.getDescription());
        model.setCopyOnPromote(soapModel.getCopyOnPromote());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<ProposalContestPhaseAttributeType> toModels(
        ProposalContestPhaseAttributeTypeSoap[] soapModels) {
        List<ProposalContestPhaseAttributeType> models = new ArrayList<ProposalContestPhaseAttributeType>(soapModels.length);

        for (ProposalContestPhaseAttributeTypeSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    public long getPrimaryKey() {
        return _id;
    }

    public void setPrimaryKey(long primaryKey) {
        setId(primaryKey);
    }

    public Serializable getPrimaryKeyObj() {
        return new Long(_id);
    }

    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    public Class<?> getModelClass() {
        return ProposalContestPhaseAttributeType.class;
    }

    public String getModelClassName() {
        return ProposalContestPhaseAttributeType.class.getName();
    }

    @JSON
    public long getId() {
        return _id;
    }

    public void setId(long id) {
        _id = id;
    }

    @JSON
    public String getRibbon() {
        if (_ribbon == null) {
            return StringPool.BLANK;
        } else {
            return _ribbon;
        }
    }

    public void setRibbon(String ribbon) {
        _ribbon = ribbon;
    }

    @JSON
    public String getHoverText() {
        if (_hoverText == null) {
            return StringPool.BLANK;
        } else {
            return _hoverText;
        }
    }

    public void setHoverText(String hoverText) {
        _hoverText = hoverText;
    }

    @JSON
    public String getDescription() {
        if (_description == null) {
            return StringPool.BLANK;
        } else {
            return _description;
        }
    }

    public void setDescription(String description) {
        _description = description;
    }

    @JSON
    public boolean getCopyOnPromote() {
        return _copyOnPromote;
    }

    public boolean isCopyOnPromote() {
        return _copyOnPromote;
    }

    public void setCopyOnPromote(boolean copyOnPromote) {
        _copyOnPromote = copyOnPromote;
    }

    @Override
    public ProposalContestPhaseAttributeType toEscapedModel() {
        if (_escapedModelProxy == null) {
            _escapedModelProxy = (ProposalContestPhaseAttributeType) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelProxyInterfaces,
                    new AutoEscapeBeanHandler(this));
        }

        return _escapedModelProxy;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        if (_expandoBridge == null) {
            _expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
                    ProposalContestPhaseAttributeType.class.getName(),
                    getPrimaryKey());
        }

        return _expandoBridge;
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        getExpandoBridge().setAttributes(serviceContext);
    }

    @Override
    public Object clone() {
        ProposalContestPhaseAttributeTypeImpl proposalContestPhaseAttributeTypeImpl =
            new ProposalContestPhaseAttributeTypeImpl();

        proposalContestPhaseAttributeTypeImpl.setId(getId());
        proposalContestPhaseAttributeTypeImpl.setRibbon(getRibbon());
        proposalContestPhaseAttributeTypeImpl.setHoverText(getHoverText());
        proposalContestPhaseAttributeTypeImpl.setDescription(getDescription());
        proposalContestPhaseAttributeTypeImpl.setCopyOnPromote(getCopyOnPromote());

        proposalContestPhaseAttributeTypeImpl.resetOriginalValues();

        return proposalContestPhaseAttributeTypeImpl;
    }

    public int compareTo(
        ProposalContestPhaseAttributeType proposalContestPhaseAttributeType) {
        long primaryKey = proposalContestPhaseAttributeType.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }

        ProposalContestPhaseAttributeType proposalContestPhaseAttributeType = null;

        try {
            proposalContestPhaseAttributeType = (ProposalContestPhaseAttributeType) obj;
        } catch (ClassCastException cce) {
            return false;
        }

        long primaryKey = proposalContestPhaseAttributeType.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<ProposalContestPhaseAttributeType> toCacheModel() {
        ProposalContestPhaseAttributeTypeCacheModel proposalContestPhaseAttributeTypeCacheModel =
            new ProposalContestPhaseAttributeTypeCacheModel();

        proposalContestPhaseAttributeTypeCacheModel.id = getId();

        proposalContestPhaseAttributeTypeCacheModel.ribbon = getRibbon();

        String ribbon = proposalContestPhaseAttributeTypeCacheModel.ribbon;

        if ((ribbon != null) && (ribbon.length() == 0)) {
            proposalContestPhaseAttributeTypeCacheModel.ribbon = null;
        }

        proposalContestPhaseAttributeTypeCacheModel.hoverText = getHoverText();

        String hoverText = proposalContestPhaseAttributeTypeCacheModel.hoverText;

        if ((hoverText != null) && (hoverText.length() == 0)) {
            proposalContestPhaseAttributeTypeCacheModel.hoverText = null;
        }

        proposalContestPhaseAttributeTypeCacheModel.description = getDescription();

        String description = proposalContestPhaseAttributeTypeCacheModel.description;

        if ((description != null) && (description.length() == 0)) {
            proposalContestPhaseAttributeTypeCacheModel.description = null;
        }

        proposalContestPhaseAttributeTypeCacheModel.copyOnPromote = getCopyOnPromote();

        return proposalContestPhaseAttributeTypeCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(11);

        sb.append("{id=");
        sb.append(getId());
        sb.append(", ribbon=");
        sb.append(getRibbon());
        sb.append(", hoverText=");
        sb.append(getHoverText());
        sb.append(", description=");
        sb.append(getDescription());
        sb.append(", copyOnPromote=");
        sb.append(getCopyOnPromote());
        sb.append("}");

        return sb.toString();
    }

    public String toXmlString() {
        StringBundler sb = new StringBundler(19);

        sb.append("<model><model-name>");
        sb.append("com.ext.portlet.model.ProposalContestPhaseAttributeType");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>id</column-name><column-value><![CDATA[");
        sb.append(getId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>ribbon</column-name><column-value><![CDATA[");
        sb.append(getRibbon());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>hoverText</column-name><column-value><![CDATA[");
        sb.append(getHoverText());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>description</column-name><column-value><![CDATA[");
        sb.append(getDescription());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>copyOnPromote</column-name><column-value><![CDATA[");
        sb.append(getCopyOnPromote());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
