package com.ext.portlet.model.impl;

import com.ext.portlet.model.Users_Roles;
import com.ext.portlet.service.Users_RolesLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Users_Roles service. Represents a row in the &quot;xcolab_Users_Roles&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Users_RolesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Users_RolesImpl
 * @see com.ext.portlet.model.Users_Roles
 * @generated
 */
public abstract class Users_RolesBaseImpl extends Users_RolesModelImpl
    implements Users_Roles {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a users_ roles model instance should use the {@link Users_Roles} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            Users_RolesLocalServiceUtil.addUsers_Roles(this);
        } else {
            Users_RolesLocalServiceUtil.updateUsers_Roles(this);
        }
    }
}
