package com.ext.portlet.plans.model;

import com.ext.portlet.plans.service.persistence.PlansFilterPositionPK;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the PlansFilterPosition service. Represents a row in the &quot;xcolab_PlansFilterPosition&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ext.portlet.plans.model.impl.PlansFilterPositionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ext.portlet.plans.model.impl.PlansFilterPositionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PlansFilterPosition
 * @see com.ext.portlet.plans.model.impl.PlansFilterPositionImpl
 * @see com.ext.portlet.plans.model.impl.PlansFilterPositionModelImpl
 * @generated
 */
public interface PlansFilterPositionModel extends BaseModel<PlansFilterPosition> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a plans filter position model instance should use the {@link PlansFilterPosition} interface instead.
     */

    /**
     * Returns the primary key of this plans filter position.
     *
     * @return the primary key of this plans filter position
     */
    public PlansFilterPositionPK getPrimaryKey();

    /**
     * Sets the primary key of this plans filter position.
     *
     * @param primaryKey the primary key of this plans filter position
     */
    public void setPrimaryKey(PlansFilterPositionPK primaryKey);

    /**
     * Returns the user ID of this plans filter position.
     *
     * @return the user ID of this plans filter position
     */
    public long getUserId();

    /**
     * Sets the user ID of this plans filter position.
     *
     * @param userId the user ID of this plans filter position
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this plans filter position.
     *
     * @return the user uuid of this plans filter position
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this plans filter position.
     *
     * @param userUuid the user uuid of this plans filter position
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the plan type ID of this plans filter position.
     *
     * @return the plan type ID of this plans filter position
     */
    public long getPlanTypeId();

    /**
     * Sets the plan type ID of this plans filter position.
     *
     * @param planTypeId the plan type ID of this plans filter position
     */
    public void setPlanTypeId(long planTypeId);

    /**
     * Returns the position ID of this plans filter position.
     *
     * @return the position ID of this plans filter position
     */
    public long getPositionId();

    /**
     * Sets the position ID of this plans filter position.
     *
     * @param positionId the position ID of this plans filter position
     */
    public void setPositionId(long positionId);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(PlansFilterPosition plansFilterPosition);

    public int hashCode();

    public CacheModel<PlansFilterPosition> toCacheModel();

    public PlansFilterPosition toEscapedModel();

    public String toString();

    public String toXmlString();
}
