package com.ext.portlet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BalloonUserTracking service. Represents a row in the &quot;xcolab_BalloonUserTracking&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ext.portlet.model.impl.BalloonUserTrackingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ext.portlet.model.impl.BalloonUserTrackingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BalloonUserTracking
 * @see com.ext.portlet.model.impl.BalloonUserTrackingImpl
 * @see com.ext.portlet.model.impl.BalloonUserTrackingModelImpl
 * @generated
 */
public interface BalloonUserTrackingModel extends BaseModel<BalloonUserTracking> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a balloon user tracking model instance should use the {@link BalloonUserTracking} interface instead.
     */

    /**
     * Returns the primary key of this balloon user tracking.
     *
     * @return the primary key of this balloon user tracking
     */
    public String getPrimaryKey();

    /**
     * Sets the primary key of this balloon user tracking.
     *
     * @param primaryKey the primary key of this balloon user tracking
     */
    public void setPrimaryKey(String primaryKey);

    /**
     * Returns the uuid of this balloon user tracking.
     *
     * @return the uuid of this balloon user tracking
     */
    @AutoEscape
    public String getUuid();

    /**
     * Sets the uuid of this balloon user tracking.
     *
     * @param uuid the uuid of this balloon user tracking
     */
    public void setUuid(String uuid);

    /**
     * Returns the email of this balloon user tracking.
     *
     * @return the email of this balloon user tracking
     */
    @AutoEscape
    public String getEmail();

    /**
     * Sets the email of this balloon user tracking.
     *
     * @param email the email of this balloon user tracking
     */
    public void setEmail(String email);

    /**
     * Returns the parent of this balloon user tracking.
     *
     * @return the parent of this balloon user tracking
     */
    @AutoEscape
    public String getParent();

    /**
     * Sets the parent of this balloon user tracking.
     *
     * @param parent the parent of this balloon user tracking
     */
    public void setParent(String parent);

    /**
     * Returns the ip of this balloon user tracking.
     *
     * @return the ip of this balloon user tracking
     */
    @AutoEscape
    public String getIp();

    /**
     * Sets the ip of this balloon user tracking.
     *
     * @param ip the ip of this balloon user tracking
     */
    public void setIp(String ip);

    /**
     * Returns the create date of this balloon user tracking.
     *
     * @return the create date of this balloon user tracking
     */
    public Date getCreateDate();

    /**
     * Sets the create date of this balloon user tracking.
     *
     * @param createDate the create date of this balloon user tracking
     */
    public void setCreateDate(Date createDate);

    /**
     * Returns the registration date of this balloon user tracking.
     *
     * @return the registration date of this balloon user tracking
     */
    public Date getRegistrationDate();

    /**
     * Sets the registration date of this balloon user tracking.
     *
     * @param registrationDate the registration date of this balloon user tracking
     */
    public void setRegistrationDate(Date registrationDate);

    /**
     * Returns the form filed date of this balloon user tracking.
     *
     * @return the form filed date of this balloon user tracking
     */
    public Date getFormFiledDate();

    /**
     * Sets the form filed date of this balloon user tracking.
     *
     * @param formFiledDate the form filed date of this balloon user tracking
     */
    public void setFormFiledDate(Date formFiledDate);

    /**
     * Returns the user ID of this balloon user tracking.
     *
     * @return the user ID of this balloon user tracking
     */
    public long getUserId();

    /**
     * Sets the user ID of this balloon user tracking.
     *
     * @param userId the user ID of this balloon user tracking
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this balloon user tracking.
     *
     * @return the user uuid of this balloon user tracking
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this balloon user tracking.
     *
     * @param userUuid the user uuid of this balloon user tracking
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the balloon text ID of this balloon user tracking.
     *
     * @return the balloon text ID of this balloon user tracking
     */
    public long getBalloonTextId();

    /**
     * Sets the balloon text ID of this balloon user tracking.
     *
     * @param balloonTextId the balloon text ID of this balloon user tracking
     */
    public void setBalloonTextId(long balloonTextId);

    /**
     * Returns the referrer of this balloon user tracking.
     *
     * @return the referrer of this balloon user tracking
     */
    @AutoEscape
    public String getReferrer();

    /**
     * Sets the referrer of this balloon user tracking.
     *
     * @param referrer the referrer of this balloon user tracking
     */
    public void setReferrer(String referrer);

    /**
     * Returns the latitude of this balloon user tracking.
     *
     * @return the latitude of this balloon user tracking
     */
    public double getLatitude();

    /**
     * Sets the latitude of this balloon user tracking.
     *
     * @param latitude the latitude of this balloon user tracking
     */
    public void setLatitude(double latitude);

    /**
     * Returns the longitude of this balloon user tracking.
     *
     * @return the longitude of this balloon user tracking
     */
    public double getLongitude();

    /**
     * Sets the longitude of this balloon user tracking.
     *
     * @param longitude the longitude of this balloon user tracking
     */
    public void setLongitude(double longitude);

    /**
     * Returns the city of this balloon user tracking.
     *
     * @return the city of this balloon user tracking
     */
    @AutoEscape
    public String getCity();

    /**
     * Sets the city of this balloon user tracking.
     *
     * @param city the city of this balloon user tracking
     */
    public void setCity(String city);

    /**
     * Returns the country of this balloon user tracking.
     *
     * @return the country of this balloon user tracking
     */
    @AutoEscape
    public String getCountry();

    /**
     * Sets the country of this balloon user tracking.
     *
     * @param country the country of this balloon user tracking
     */
    public void setCountry(String country);

    /**
     * Returns the extra data of this balloon user tracking.
     *
     * @return the extra data of this balloon user tracking
     */
    @AutoEscape
    public String getExtraData();

    /**
     * Sets the extra data of this balloon user tracking.
     *
     * @param extraData the extra data of this balloon user tracking
     */
    public void setExtraData(String extraData);

    /**
     * Returns the balloon link uuid of this balloon user tracking.
     *
     * @return the balloon link uuid of this balloon user tracking
     */
    @AutoEscape
    public String getBalloonLinkUuid();

    /**
     * Sets the balloon link uuid of this balloon user tracking.
     *
     * @param balloonLinkUuid the balloon link uuid of this balloon user tracking
     */
    public void setBalloonLinkUuid(String balloonLinkUuid);

    /**
     * Returns the balloon link context of this balloon user tracking.
     *
     * @return the balloon link context of this balloon user tracking
     */
    @AutoEscape
    public String getBalloonLinkContext();

    /**
     * Sets the balloon link context of this balloon user tracking.
     *
     * @param balloonLinkContext the balloon link context of this balloon user tracking
     */
    public void setBalloonLinkContext(String balloonLinkContext);

    /**
     * Returns the user agent of this balloon user tracking.
     *
     * @return the user agent of this balloon user tracking
     */
    @AutoEscape
    public String getUserAgent();

    /**
     * Sets the user agent of this balloon user tracking.
     *
     * @param userAgent the user agent of this balloon user tracking
     */
    public void setUserAgent(String userAgent);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(BalloonUserTracking balloonUserTracking);

    @Override
    public int hashCode();

    @Override
    public CacheModel<BalloonUserTracking> toCacheModel();

    @Override
    public BalloonUserTracking toEscapedModel();

    @Override
    public BalloonUserTracking toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
