package com.ext.portlet.model;

import com.ext.portlet.service.persistence.ConfigurationAttributePK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ConfigurationAttribute service. Represents a row in the &quot;xcolab_ConfigurationAttribute&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ext.portlet.model.impl.ConfigurationAttributeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ext.portlet.model.impl.ConfigurationAttributeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ConfigurationAttribute
 * @see com.ext.portlet.model.impl.ConfigurationAttributeImpl
 * @see com.ext.portlet.model.impl.ConfigurationAttributeModelImpl
 * @generated
 */
public interface ConfigurationAttributeModel extends BaseModel<ConfigurationAttribute> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a configuration attribute model instance should use the {@link ConfigurationAttribute} interface instead.
     */

    /**
     * Returns the primary key of this configuration attribute.
     *
     * @return the primary key of this configuration attribute
     */
    public ConfigurationAttributePK getPrimaryKey();

    /**
     * Sets the primary key of this configuration attribute.
     *
     * @param primaryKey the primary key of this configuration attribute
     */
    public void setPrimaryKey(ConfigurationAttributePK primaryKey);

    /**
     * Returns the name of this configuration attribute.
     *
     * @return the name of this configuration attribute
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this configuration attribute.
     *
     * @param name the name of this configuration attribute
     */
    public void setName(String name);

    /**
     * Returns the additional ID of this configuration attribute.
     *
     * @return the additional ID of this configuration attribute
     */
    public long getAdditionalId();

    /**
     * Sets the additional ID of this configuration attribute.
     *
     * @param additionalId the additional ID of this configuration attribute
     */
    public void setAdditionalId(long additionalId);

    /**
     * Returns the numeric value of this configuration attribute.
     *
     * @return the numeric value of this configuration attribute
     */
    public long getNumericValue();

    /**
     * Sets the numeric value of this configuration attribute.
     *
     * @param numericValue the numeric value of this configuration attribute
     */
    public void setNumericValue(long numericValue);

    /**
     * Returns the string value of this configuration attribute.
     *
     * @return the string value of this configuration attribute
     */
    @AutoEscape
    public String getStringValue();

    /**
     * Sets the string value of this configuration attribute.
     *
     * @param stringValue the string value of this configuration attribute
     */
    public void setStringValue(String stringValue);

    /**
     * Returns the real value of this configuration attribute.
     *
     * @return the real value of this configuration attribute
     */
    public double getRealValue();

    /**
     * Sets the real value of this configuration attribute.
     *
     * @param realValue the real value of this configuration attribute
     */
    public void setRealValue(double realValue);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        com.ext.portlet.model.ConfigurationAttribute configurationAttribute);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.ext.portlet.model.ConfigurationAttribute> toCacheModel();

    @Override
    public com.ext.portlet.model.ConfigurationAttribute toEscapedModel();

    @Override
    public com.ext.portlet.model.ConfigurationAttribute toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
