package com.ext.portlet.model;

import com.ext.portlet.service.persistence.FocusAreaOntologyTermPK;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the FocusAreaOntologyTerm service. Represents a row in the &quot;xcolab_FocusAreaOntologyTerm&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ext.portlet.model.impl.FocusAreaOntologyTermModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ext.portlet.model.impl.FocusAreaOntologyTermImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FocusAreaOntologyTerm
 * @see com.ext.portlet.model.impl.FocusAreaOntologyTermImpl
 * @see com.ext.portlet.model.impl.FocusAreaOntologyTermModelImpl
 * @generated
 */
public interface FocusAreaOntologyTermModel extends BaseModel<FocusAreaOntologyTerm> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a focus area ontology term model instance should use the {@link FocusAreaOntologyTerm} interface instead.
     */

    /**
     * Returns the primary key of this focus area ontology term.
     *
     * @return the primary key of this focus area ontology term
     */
    public FocusAreaOntologyTermPK getPrimaryKey();

    /**
     * Sets the primary key of this focus area ontology term.
     *
     * @param primaryKey the primary key of this focus area ontology term
     */
    public void setPrimaryKey(FocusAreaOntologyTermPK primaryKey);

    /**
     * Returns the focus area ID of this focus area ontology term.
     *
     * @return the focus area ID of this focus area ontology term
     */
    public long getFocusAreaId();

    /**
     * Sets the focus area ID of this focus area ontology term.
     *
     * @param focusAreaId the focus area ID of this focus area ontology term
     */
    public void setFocusAreaId(long focusAreaId);

    /**
     * Returns the ontology term ID of this focus area ontology term.
     *
     * @return the ontology term ID of this focus area ontology term
     */
    public long getOntologyTermId();

    /**
     * Sets the ontology term ID of this focus area ontology term.
     *
     * @param ontologyTermId the ontology term ID of this focus area ontology term
     */
    public void setOntologyTermId(long ontologyTermId);

    /**
     * Returns the order of this focus area ontology term.
     *
     * @return the order of this focus area ontology term
     */
    public int getOrder();

    /**
     * Sets the order of this focus area ontology term.
     *
     * @param order the order of this focus area ontology term
     */
    public void setOrder(int order);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        com.ext.portlet.model.FocusAreaOntologyTerm focusAreaOntologyTerm);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.ext.portlet.model.FocusAreaOntologyTerm> toCacheModel();

    @Override
    public com.ext.portlet.model.FocusAreaOntologyTerm toEscapedModel();

    @Override
    public com.ext.portlet.model.FocusAreaOntologyTerm toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
