package com.ext.portlet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the MessagingMessageConversionType service. Represents a row in the &quot;xcolab_MessagingMessageConversionType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ext.portlet.model.impl.MessagingMessageConversionTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ext.portlet.model.impl.MessagingMessageConversionTypeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MessagingMessageConversionType
 * @see com.ext.portlet.model.impl.MessagingMessageConversionTypeImpl
 * @see com.ext.portlet.model.impl.MessagingMessageConversionTypeModelImpl
 * @generated
 */
public interface MessagingMessageConversionTypeModel extends BaseModel<MessagingMessageConversionType> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a messaging message conversion type model instance should use the {@link MessagingMessageConversionType} interface instead.
     */

    /**
     * Returns the primary key of this messaging message conversion type.
     *
     * @return the primary key of this messaging message conversion type
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this messaging message conversion type.
     *
     * @param primaryKey the primary key of this messaging message conversion type
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the type ID of this messaging message conversion type.
     *
     * @return the type ID of this messaging message conversion type
     */
    public long getTypeId();

    /**
     * Sets the type ID of this messaging message conversion type.
     *
     * @param typeId the type ID of this messaging message conversion type
     */
    public void setTypeId(long typeId);

    /**
     * Returns the name of this messaging message conversion type.
     *
     * @return the name of this messaging message conversion type
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this messaging message conversion type.
     *
     * @param name the name of this messaging message conversion type
     */
    public void setName(String name);

    /**
     * Returns the description of this messaging message conversion type.
     *
     * @return the description of this messaging message conversion type
     */
    @AutoEscape
    public String getDescription();

    /**
     * Sets the description of this messaging message conversion type.
     *
     * @param description the description of this messaging message conversion type
     */
    public void setDescription(String description);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        com.ext.portlet.model.MessagingMessageConversionType messagingMessageConversionType);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.ext.portlet.model.MessagingMessageConversionType> toCacheModel();

    @Override
    public com.ext.portlet.model.MessagingMessageConversionType toEscapedModel();

    @Override
    public com.ext.portlet.model.MessagingMessageConversionType toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
