package com.ext.portlet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the PlanTypeAttribute service. Represents a row in the &quot;xcolab_PlanTypeAttribute&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ext.portlet.model.impl.PlanTypeAttributeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ext.portlet.model.impl.PlanTypeAttributeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PlanTypeAttribute
 * @see com.ext.portlet.model.impl.PlanTypeAttributeImpl
 * @see com.ext.portlet.model.impl.PlanTypeAttributeModelImpl
 * @generated
 */
public interface PlanTypeAttributeModel extends BaseModel<PlanTypeAttribute> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a plan type attribute model instance should use the {@link PlanTypeAttribute} interface instead.
     */

    /**
     * Returns the primary key of this plan type attribute.
     *
     * @return the primary key of this plan type attribute
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this plan type attribute.
     *
     * @param primaryKey the primary key of this plan type attribute
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the plan type attribute ID of this plan type attribute.
     *
     * @return the plan type attribute ID of this plan type attribute
     */
    public long getPlanTypeAttributeId();

    /**
     * Sets the plan type attribute ID of this plan type attribute.
     *
     * @param planTypeAttributeId the plan type attribute ID of this plan type attribute
     */
    public void setPlanTypeAttributeId(long planTypeAttributeId);

    /**
     * Returns the plan type ID of this plan type attribute.
     *
     * @return the plan type ID of this plan type attribute
     */
    public long getPlanTypeId();

    /**
     * Sets the plan type ID of this plan type attribute.
     *
     * @param planTypeId the plan type ID of this plan type attribute
     */
    public void setPlanTypeId(long planTypeId);

    /**
     * Returns the attribute name of this plan type attribute.
     *
     * @return the attribute name of this plan type attribute
     */
    @AutoEscape
    public String getAttributeName();

    /**
     * Sets the attribute name of this plan type attribute.
     *
     * @param attributeName the attribute name of this plan type attribute
     */
    public void setAttributeName(String attributeName);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(PlanTypeAttribute planTypeAttribute);

    public int hashCode();

    public CacheModel<PlanTypeAttribute> toCacheModel();

    public PlanTypeAttribute toEscapedModel();

    public String toString();

    public String toXmlString();
}
