package com.ext.portlet.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Points service. Represents a row in the &quot;xcolab_Points&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ext.portlet.model.impl.PointsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ext.portlet.model.impl.PointsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Points
 * @see com.ext.portlet.model.impl.PointsImpl
 * @see com.ext.portlet.model.impl.PointsModelImpl
 * @generated
 */
public interface PointsModel extends BaseModel<Points> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a points model instance should use the {@link Points} interface instead.
     */

    /**
     * Returns the primary key of this points.
     *
     * @return the primary key of this points
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this points.
     *
     * @param primaryKey the primary key of this points
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the ID of this points.
     *
     * @return the ID of this points
     */
    public long getId();

    /**
     * Sets the ID of this points.
     *
     * @param id the ID of this points
     */
    public void setId(long id);

    /**
     * Returns the proposal ID of this points.
     *
     * @return the proposal ID of this points
     */
    public long getProposalId();

    /**
     * Sets the proposal ID of this points.
     *
     * @param proposalId the proposal ID of this points
     */
    public void setProposalId(long proposalId);

    /**
     * Returns the user ID of this points.
     *
     * @return the user ID of this points
     */
    public long getUserId();

    /**
     * Sets the user ID of this points.
     *
     * @param userId the user ID of this points
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this points.
     *
     * @return the user uuid of this points
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this points.
     *
     * @param userUuid the user uuid of this points
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the materialized points of this points.
     *
     * @return the materialized points of this points
     */
    public double getMaterializedPoints();

    /**
     * Sets the materialized points of this points.
     *
     * @param materializedPoints the materialized points of this points
     */
    public void setMaterializedPoints(double materializedPoints);

    /**
     * Returns the hypothetical points of this points.
     *
     * @return the hypothetical points of this points
     */
    public double getHypotheticalPoints();

    /**
     * Sets the hypothetical points of this points.
     *
     * @param hypotheticalPoints the hypothetical points of this points
     */
    public void setHypotheticalPoints(double hypotheticalPoints);

    /**
     * Returns the points source ID of this points.
     *
     * @return the points source ID of this points
     */
    public long getPointsSourceId();

    /**
     * Sets the points source ID of this points.
     *
     * @param pointsSourceId the points source ID of this points
     */
    public void setPointsSourceId(long pointsSourceId);

    /**
     * Returns the originating contest p k of this points.
     *
     * @return the originating contest p k of this points
     */
    public long getOriginatingContestPK();

    /**
     * Sets the originating contest p k of this points.
     *
     * @param originatingContestPK the originating contest p k of this points
     */
    public void setOriginatingContestPK(long originatingContestPK);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Points points);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Points> toCacheModel();

    @Override
    public Points toEscapedModel();

    @Override
    public Points toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
