package com.ext.portlet.model;

import com.ext.portlet.service.persistence.ProposalAttributePK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ProposalAttribute service. Represents a row in the &quot;xcolab_ProposalAttribute&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ext.portlet.model.impl.ProposalAttributeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ext.portlet.model.impl.ProposalAttributeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProposalAttribute
 * @see com.ext.portlet.model.impl.ProposalAttributeImpl
 * @see com.ext.portlet.model.impl.ProposalAttributeModelImpl
 * @generated
 */
public interface ProposalAttributeModel extends BaseModel<ProposalAttribute> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a proposal attribute model instance should use the {@link ProposalAttribute} interface instead.
     */

    /**
     * Returns the primary key of this proposal attribute.
     *
     * @return the primary key of this proposal attribute
     */
    public ProposalAttributePK getPrimaryKey();

    /**
     * Sets the primary key of this proposal attribute.
     *
     * @param primaryKey the primary key of this proposal attribute
     */
    public void setPrimaryKey(ProposalAttributePK primaryKey);

    /**
     * Returns the proposal ID of this proposal attribute.
     *
     * @return the proposal ID of this proposal attribute
     */
    public long getProposalId();

    /**
     * Sets the proposal ID of this proposal attribute.
     *
     * @param proposalId the proposal ID of this proposal attribute
     */
    public void setProposalId(long proposalId);

    /**
     * Returns the version of this proposal attribute.
     *
     * @return the version of this proposal attribute
     */
    public int getVersion();

    /**
     * Sets the version of this proposal attribute.
     *
     * @param version the version of this proposal attribute
     */
    public void setVersion(int version);

    /**
     * Returns the name of this proposal attribute.
     *
     * @return the name of this proposal attribute
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this proposal attribute.
     *
     * @param name the name of this proposal attribute
     */
    public void setName(String name);

    /**
     * Returns the additional ID of this proposal attribute.
     *
     * @return the additional ID of this proposal attribute
     */
    public long getAdditionalId();

    /**
     * Sets the additional ID of this proposal attribute.
     *
     * @param additionalId the additional ID of this proposal attribute
     */
    public void setAdditionalId(long additionalId);

    /**
     * Returns the numeric value of this proposal attribute.
     *
     * @return the numeric value of this proposal attribute
     */
    public long getNumericValue();

    /**
     * Sets the numeric value of this proposal attribute.
     *
     * @param numericValue the numeric value of this proposal attribute
     */
    public void setNumericValue(long numericValue);

    /**
     * Returns the string value of this proposal attribute.
     *
     * @return the string value of this proposal attribute
     */
    @AutoEscape
    public String getStringValue();

    /**
     * Sets the string value of this proposal attribute.
     *
     * @param stringValue the string value of this proposal attribute
     */
    public void setStringValue(String stringValue);

    /**
     * Returns the real value of this proposal attribute.
     *
     * @return the real value of this proposal attribute
     */
    public double getRealValue();

    /**
     * Sets the real value of this proposal attribute.
     *
     * @param realValue the real value of this proposal attribute
     */
    public void setRealValue(double realValue);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(ProposalAttribute proposalAttribute);

    public int hashCode();

    public CacheModel<ProposalAttribute> toCacheModel();

    public ProposalAttribute toEscapedModel();

    public String toString();

    public String toXmlString();
}
