package com.ext.portlet.plans.model.impl;

import com.ext.portlet.plans.model.PlanVote;
import com.ext.portlet.plans.service.PlanVoteLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the PlanVote service. Represents a row in the &quot;xcolab_PlanVote&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PlanVoteImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PlanVoteImpl
 * @see com.ext.portlet.plans.model.PlanVote
 * @generated
 */
public abstract class PlanVoteBaseImpl extends PlanVoteModelImpl
    implements PlanVote {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a plan vote model instance should use the {@link PlanVote} interface instead.
     */
    public void persist() throws SystemException {
        if (this.isNew()) {
            PlanVoteLocalServiceUtil.addPlanVote(this);
        } else {
            PlanVoteLocalServiceUtil.updatePlanVote(this);
        }
    }
}
