package com.xcolab.services.sample.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.search.Indexer;
import com.liferay.portal.kernel.search.IndexerRegistryUtil;
import com.liferay.portal.kernel.search.SearchException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.xcolab.services.sample.model.SampleEntity;
import com.xcolab.services.sample.service.SampleEntityLocalService;
import com.xcolab.services.sample.service.SampleEntityService;
import com.xcolab.services.sample.service.persistence.SampleEntityPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the sample entity local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.xcolab.services.sample.service.impl.SampleEntityLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.xcolab.services.sample.service.impl.SampleEntityLocalServiceImpl
 * @see com.xcolab.services.sample.service.SampleEntityLocalServiceUtil
 * @generated
 */
public abstract class SampleEntityLocalServiceBaseImpl
    implements SampleEntityLocalService, IdentifiableBean {
    private static Log _log = LogFactoryUtil.getLog(SampleEntityLocalServiceBaseImpl.class);
    @BeanReference(type = SampleEntityLocalService.class)
    protected SampleEntityLocalService sampleEntityLocalService;
    @BeanReference(type = SampleEntityService.class)
    protected SampleEntityService sampleEntityService;
    @BeanReference(type = SampleEntityPersistence.class)
    protected SampleEntityPersistence sampleEntityPersistence;
    @BeanReference(type = CounterLocalService.class)
    protected CounterLocalService counterLocalService;
    @BeanReference(type = ResourceLocalService.class)
    protected ResourceLocalService resourceLocalService;
    @BeanReference(type = ResourceService.class)
    protected ResourceService resourceService;
    @BeanReference(type = ResourcePersistence.class)
    protected ResourcePersistence resourcePersistence;
    @BeanReference(type = UserLocalService.class)
    protected UserLocalService userLocalService;
    @BeanReference(type = UserService.class)
    protected UserService userService;
    @BeanReference(type = UserPersistence.class)
    protected UserPersistence userPersistence;
    private String _beanIdentifier;

    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. Always use {@link com.xcolab.services.sample.service.SampleEntityLocalServiceUtil} to access the sample entity local service.
     */

    /**
     * Adds the sample entity to the database. Also notifies the appropriate model listeners.
     *
     * @param sampleEntity the sample entity
     * @return the sample entity that was added
     * @throws SystemException if a system exception occurred
     */
    public SampleEntity addSampleEntity(SampleEntity sampleEntity)
        throws SystemException {
        sampleEntity.setNew(true);

        sampleEntity = sampleEntityPersistence.update(sampleEntity, false);

        Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

        if (indexer != null) {
            try {
                indexer.reindex(sampleEntity);
            } catch (SearchException se) {
                if (_log.isWarnEnabled()) {
                    _log.warn(se, se);
                }
            }
        }

        return sampleEntity;
    }

    /**
     * Creates a new sample entity with the primary key. Does not add the sample entity to the database.
     *
     * @param id the primary key for the new sample entity
     * @return the new sample entity
     */
    public SampleEntity createSampleEntity(long id) {
        return sampleEntityPersistence.create(id);
    }

    /**
     * Deletes the sample entity with the primary key from the database. Also notifies the appropriate model listeners.
     *
     * @param id the primary key of the sample entity
     * @throws PortalException if a sample entity with the primary key could not be found
     * @throws SystemException if a system exception occurred
     */
    public void deleteSampleEntity(long id)
        throws PortalException, SystemException {
        SampleEntity sampleEntity = sampleEntityPersistence.remove(id);

        Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

        if (indexer != null) {
            try {
                indexer.delete(sampleEntity);
            } catch (SearchException se) {
                if (_log.isWarnEnabled()) {
                    _log.warn(se, se);
                }
            }
        }
    }

    /**
     * Deletes the sample entity from the database. Also notifies the appropriate model listeners.
     *
     * @param sampleEntity the sample entity
     * @throws SystemException if a system exception occurred
     */
    public void deleteSampleEntity(SampleEntity sampleEntity)
        throws SystemException {
        sampleEntityPersistence.remove(sampleEntity);

        Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

        if (indexer != null) {
            try {
                indexer.delete(sampleEntity);
            } catch (SearchException se) {
                if (_log.isWarnEnabled()) {
                    _log.warn(se, se);
                }
            }
        }
    }

    /**
     * Performs a dynamic query on the database and returns the matching rows.
     *
     * @param dynamicQuery the dynamic query
     * @return the matching rows
     * @throws SystemException if a system exception occurred
     */
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery)
        throws SystemException {
        return sampleEntityPersistence.findWithDynamicQuery(dynamicQuery);
    }

    /**
     * Performs a dynamic query on the database and returns a range of the matching rows.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
     * </p>
     *
     * @param dynamicQuery the dynamic query
     * @param start the lower bound of the range of model instances
     * @param end the upper bound of the range of model instances (not inclusive)
     * @return the range of matching rows
     * @throws SystemException if a system exception occurred
     */
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
        throws SystemException {
        return sampleEntityPersistence.findWithDynamicQuery(dynamicQuery,
            start, end);
    }

    /**
     * Performs a dynamic query on the database and returns an ordered range of the matching rows.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
     * </p>
     *
     * @param dynamicQuery the dynamic query
     * @param start the lower bound of the range of model instances
     * @param end the upper bound of the range of model instances (not inclusive)
     * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
     * @return the ordered range of matching rows
     * @throws SystemException if a system exception occurred
     */
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
        OrderByComparator orderByComparator) throws SystemException {
        return sampleEntityPersistence.findWithDynamicQuery(dynamicQuery,
            start, end, orderByComparator);
    }

    /**
     * Returns the number of rows that match the dynamic query.
     *
     * @param dynamicQuery the dynamic query
     * @return the number of rows that match the dynamic query
     * @throws SystemException if a system exception occurred
     */
    public long dynamicQueryCount(DynamicQuery dynamicQuery)
        throws SystemException {
        return sampleEntityPersistence.countWithDynamicQuery(dynamicQuery);
    }

    public SampleEntity fetchSampleEntity(long id) throws SystemException {
        return sampleEntityPersistence.fetchByPrimaryKey(id);
    }

    /**
     * Returns the sample entity with the primary key.
     *
     * @param id the primary key of the sample entity
     * @return the sample entity
     * @throws PortalException if a sample entity with the primary key could not be found
     * @throws SystemException if a system exception occurred
     */
    public SampleEntity getSampleEntity(long id)
        throws PortalException, SystemException {
        return sampleEntityPersistence.findByPrimaryKey(id);
    }

    public PersistedModel getPersistedModel(Serializable primaryKeyObj)
        throws PortalException, SystemException {
        return sampleEntityPersistence.findByPrimaryKey(primaryKeyObj);
    }

    /**
     * Returns a range of all the sample entities.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
     * </p>
     *
     * @param start the lower bound of the range of sample entities
     * @param end the upper bound of the range of sample entities (not inclusive)
     * @return the range of sample entities
     * @throws SystemException if a system exception occurred
     */
    public List<SampleEntity> getSampleEntities(int start, int end)
        throws SystemException {
        return sampleEntityPersistence.findAll(start, end);
    }

    /**
     * Returns the number of sample entities.
     *
     * @return the number of sample entities
     * @throws SystemException if a system exception occurred
     */
    public int getSampleEntitiesCount() throws SystemException {
        return sampleEntityPersistence.countAll();
    }

    /**
     * Updates the sample entity in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
     *
     * @param sampleEntity the sample entity
     * @return the sample entity that was updated
     * @throws SystemException if a system exception occurred
     */
    public SampleEntity updateSampleEntity(SampleEntity sampleEntity)
        throws SystemException {
        return updateSampleEntity(sampleEntity, true);
    }

    /**
     * Updates the sample entity in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
     *
     * @param sampleEntity the sample entity
     * @param merge whether to merge the sample entity with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
     * @return the sample entity that was updated
     * @throws SystemException if a system exception occurred
     */
    public SampleEntity updateSampleEntity(SampleEntity sampleEntity,
        boolean merge) throws SystemException {
        sampleEntity.setNew(false);

        sampleEntity = sampleEntityPersistence.update(sampleEntity, merge);

        Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

        if (indexer != null) {
            try {
                indexer.reindex(sampleEntity);
            } catch (SearchException se) {
                if (_log.isWarnEnabled()) {
                    _log.warn(se, se);
                }
            }
        }

        return sampleEntity;
    }

    /**
     * Returns the sample entity local service.
     *
     * @return the sample entity local service
     */
    public SampleEntityLocalService getSampleEntityLocalService() {
        return sampleEntityLocalService;
    }

    /**
     * Sets the sample entity local service.
     *
     * @param sampleEntityLocalService the sample entity local service
     */
    public void setSampleEntityLocalService(
        SampleEntityLocalService sampleEntityLocalService) {
        this.sampleEntityLocalService = sampleEntityLocalService;
    }

    /**
     * Returns the sample entity remote service.
     *
     * @return the sample entity remote service
     */
    public SampleEntityService getSampleEntityService() {
        return sampleEntityService;
    }

    /**
     * Sets the sample entity remote service.
     *
     * @param sampleEntityService the sample entity remote service
     */
    public void setSampleEntityService(SampleEntityService sampleEntityService) {
        this.sampleEntityService = sampleEntityService;
    }

    /**
     * Returns the sample entity persistence.
     *
     * @return the sample entity persistence
     */
    public SampleEntityPersistence getSampleEntityPersistence() {
        return sampleEntityPersistence;
    }

    /**
     * Sets the sample entity persistence.
     *
     * @param sampleEntityPersistence the sample entity persistence
     */
    public void setSampleEntityPersistence(
        SampleEntityPersistence sampleEntityPersistence) {
        this.sampleEntityPersistence = sampleEntityPersistence;
    }

    /**
     * Returns the counter local service.
     *
     * @return the counter local service
     */
    public CounterLocalService getCounterLocalService() {
        return counterLocalService;
    }

    /**
     * Sets the counter local service.
     *
     * @param counterLocalService the counter local service
     */
    public void setCounterLocalService(CounterLocalService counterLocalService) {
        this.counterLocalService = counterLocalService;
    }

    /**
     * Returns the resource local service.
     *
     * @return the resource local service
     */
    public ResourceLocalService getResourceLocalService() {
        return resourceLocalService;
    }

    /**
     * Sets the resource local service.
     *
     * @param resourceLocalService the resource local service
     */
    public void setResourceLocalService(
        ResourceLocalService resourceLocalService) {
        this.resourceLocalService = resourceLocalService;
    }

    /**
     * Returns the resource remote service.
     *
     * @return the resource remote service
     */
    public ResourceService getResourceService() {
        return resourceService;
    }

    /**
     * Sets the resource remote service.
     *
     * @param resourceService the resource remote service
     */
    public void setResourceService(ResourceService resourceService) {
        this.resourceService = resourceService;
    }

    /**
     * Returns the resource persistence.
     *
     * @return the resource persistence
     */
    public ResourcePersistence getResourcePersistence() {
        return resourcePersistence;
    }

    /**
     * Sets the resource persistence.
     *
     * @param resourcePersistence the resource persistence
     */
    public void setResourcePersistence(ResourcePersistence resourcePersistence) {
        this.resourcePersistence = resourcePersistence;
    }

    /**
     * Returns the user local service.
     *
     * @return the user local service
     */
    public UserLocalService getUserLocalService() {
        return userLocalService;
    }

    /**
     * Sets the user local service.
     *
     * @param userLocalService the user local service
     */
    public void setUserLocalService(UserLocalService userLocalService) {
        this.userLocalService = userLocalService;
    }

    /**
     * Returns the user remote service.
     *
     * @return the user remote service
     */
    public UserService getUserService() {
        return userService;
    }

    /**
     * Sets the user remote service.
     *
     * @param userService the user remote service
     */
    public void setUserService(UserService userService) {
        this.userService = userService;
    }

    /**
     * Returns the user persistence.
     *
     * @return the user persistence
     */
    public UserPersistence getUserPersistence() {
        return userPersistence;
    }

    /**
     * Sets the user persistence.
     *
     * @param userPersistence the user persistence
     */
    public void setUserPersistence(UserPersistence userPersistence) {
        this.userPersistence = userPersistence;
    }

    public void afterPropertiesSet() {
        PersistedModelLocalServiceRegistryUtil.register("com.xcolab.services.sample.model.SampleEntity",
            sampleEntityLocalService);
    }

    public void destroy() {
        PersistedModelLocalServiceRegistryUtil.unregister(
            "com.xcolab.services.sample.model.SampleEntity");
    }

    /**
     * Returns the Spring bean ID for this bean.
     *
     * @return the Spring bean ID for this bean
     */
    public String getBeanIdentifier() {
        return _beanIdentifier;
    }

    /**
     * Sets the Spring bean ID for this bean.
     *
     * @param beanIdentifier the Spring bean ID for this bean
     */
    public void setBeanIdentifier(String beanIdentifier) {
        _beanIdentifier = beanIdentifier;
    }

    protected Class<?> getModelClass() {
        return SampleEntity.class;
    }

    protected String getModelClassName() {
        return SampleEntity.class.getName();
    }

    /**
     * Performs an SQL query.
     *
     * @param sql the sql query
     */
    protected void runSQL(String sql) throws SystemException {
        try {
            DataSource dataSource = sampleEntityPersistence.getDataSource();

            SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
                    sql, new int[0]);

            sqlUpdate.update();
        } catch (Exception e) {
            throw new SystemException(e);
        }
    }
}
