server:
  port: 18082
  compression:
    enabled: true
  error:
    whitelabel:
      enabled: false
    path: /spring/error

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jspx
    ignore-default-model-on-redirect: true