server:
  port: 18082
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always
  servlet:
    session:
      timeout: 7200
  compression:
    enabled: true

management:
  server:
    add-application-context-header: false
    servlet:
      context-path: /admin/management
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

cache:
  enabled: true
  provider: org.xcolab.util.http.caching.provider.ehcache3.CacheProviderEhcache3Impl
  disk-storage:
    enabled: true
    max-megabytes: 1000

spring:
  security:
    filter:
      dispatcher-types: ASYNC,REQUEST,ERROR
  servlet:
    multipart:
      max-file-size: 2MB
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jspx
    favicon:
      enabled: false
  session:
    store-type: REDIS
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths:
            - "/js/**"      # /static/js - our JavaScript files
            - "/css/**"     # /static/css - our CSS files
            - "/vendor/**"  # /dist/vendor - external dependencies (from yarn)
      cache: false
    cache:
      period: 31536000 # 365 days
    # use comma-separated list to override default value
    static-locations: >
      classpath:/dist/,
      classpath:/static/


  aop:
    proxy-target-class: false

eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

logging:
  level:
    ROOT: WARN
    com.netflix.eureka: INFO
    org.xcolab.util.http.caching.provider: INFO
    org.xcolab.view.config: INFO
    org.xcolab.view.crons: INFO
    org.springframework: INFO
    org.springframework.jmx: WARN
    org.springframework.web: WARN
    org.springframework.boot.web: WARN
    org.springframework.boot.actuate: WARN
    org.springframework.context.annotation: WARN
    org.springframework.beans.factory.annotation: WARN


security:
  oauth2:
    client:
      scope: openid,email,profile
    resource:
      user-info-uri: /oauth/userinfo
sso:
  facebook:
    client:
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope:
        - public_profile
        - email
    resource:
      userInfoUri: https://graph.facebook.com/me?fields=id,email,first_name,last_name,location,locale,picture
  google:
    client:
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope:
        - openid
        - email
        - profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true
  xcolab:
    client:
      accessTokenUri: ${sso.xcolab.hostname}/oauth/token
      userAuthorizationUri: ${sso.xcolab.hostname}/oauth/authorize
      scope:
       - openid
       - email
       - profile
    resource:
      userInfoUri: ${sso.xcolab.hostname}/api/user
  climatex:
    client:
      accessTokenUri: ${sso.climatex.hostname}/oauth2/token
      userAuthorizationUri: ${sso.climatex.hostname}/oauth2/authorize
      clientAuthenticationScheme: form
      scope:
       - openid
       - email
       - profile
    resource:
      userInfoUri: ${sso.climatex.hostname}/oauth2/UserInfo

http-client:
  connection-pool:
    max-total: 40
    default-max-per-route: 3
feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
---

spring:
  profiles: development
  resources:
    # use comma-separated list to override default value
    static-locations: >
      file:view/src/main/resources/static/,
      file:view/src/main/resources/dist/,
      classpath:/dist/,
      classpath:/static/
