server:
  port: 18082
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always
  session:
    timeout: 7200
  compression:
    enabled: true

management:
  add-application-context-header: false
  context-path: /admin/management
  security:
    roles: ACTUATOR,ADMIN

cache:
  enabled: true
  provider: org.xcolab.util.http.caching.provider.ehcache2.Ehcache2CacheProvider
  disk-storage:
    enabled: true
    max-megabytes: 1000

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jspx
    favicon:
      enabled: false
  http:
    multipart:
      max-file-size: 2MB
  session:
    store-type: hash_map
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths:
            - "/js/**"      # /static/js - our JavaScript files
            - "/css/**"     # /static/css - our CSS files
            - "/vendor/**"  # /dist/vendor - external dependencies (from yarn)
      cache: false
    cache-period: 31536000 # 365 days
    # use comma-separated list to override default value
    static-locations: >
      classpath:/dist/,
      classpath:/static/

eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

logging:
  level:
    ROOT: WARN
    com.netflix.eureka: INFO
    org.xcolab.util.http.caching.provider: INFO
    org.xcolab.view.config: INFO
    org.xcolab.view.crons: INFO
    org.springframework: INFO
    org.springframework.jmx: WARN
    org.springframework.web: WARN
    org.springframework.boot.web: WARN
    org.springframework.boot.actuate: WARN
    org.springframework.context.annotation: WARN
    org.springframework.beans.factory.annotation: WARN

security:
  filter-dispatcher-types: ASYNC,REQUEST,ERROR


http-client:
  connection-pool:
    max-total: 40
    default-max-per-route: 3

---

spring:
  profiles: development
  resources:
    # use comma-separated list to override default value
    static-locations: >
      file:view/src/main/resources/static/,
      file:view/src/main/resources/dist/,
      classpath:/dist/,
      classpath:/static/
