server:
  port: 18082
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always
  session:
    persistent: true

tomcat:
  ajp:
    enabled: true

management:
  add-application-context-header: false
  context-path: /admin/management

cache:
  enabled: true
  provider: org.xcolab.util.http.caching.provider.ehcache3.CacheProviderEhcache3Impl

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jspx
    favicon:
      enabled: false
  http:
    multipart:
      max-file-size: 2MB