server:
  port: 18083
  compression:
    enabled: true
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jspx
    favicon:
      enabled: false