server:
  port: 18082
  compression:
    enabled: true
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always

tomcat:
  ajp:
    enabled: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jspx
    favicon:
      enabled: false
  http:
    multipart:
      max-file-size: 2MB