-- COLAB-1999

UPDATE `xcolab_Contest` SET `ContestShortName`='Climate friendly diet' WHERE `ContestPK`='6';
UPDATE `xcolab_Contest` SET `ContestShortName`='Transportation efficiency' WHERE `ContestPK`='7';
UPDATE `xcolab_Contest` SET `ContestShortName`='Electric power sector' WHERE `ContestPK`='10';
UPDATE `xcolab_Contest` SET `ContestShortName`='Building efficiency' WHERE `ContestPK`='11';
UPDATE `xcolab_Contest` SET `ContestShortName`='Local solutions' WHERE `ContestPK`='13';
UPDATE `xcolab_Contest` SET `ContestShortName`='Urban adaptation: Climate resilient cities' WHERE `ContestPK`='14';
UPDATE `xcolab_Contest` SET `ContestShortName`='Profitably reducing emissions from cement' WHERE `ContestPK`='15';
UPDATE `xcolab_Contest` SET `ContestShortName`='Industrial efficiency' WHERE `ContestPK`='16';
UPDATE `xcolab_Contest` SET `ContestShortName`='Fossil fuel sector' WHERE `ContestPK`='17';
UPDATE `xcolab_Contest` SET `ContestShortName`='Agriculture and forestry' WHERE `ContestPK`='18';
UPDATE `xcolab_Contest` SET `ContestShortName`='Adaptation and Civil Society Groups' WHERE `ContestPK`='19';
UPDATE `xcolab_Contest` SET `ContestShortName`='Geoengineering' WHERE `ContestPK`='20';
UPDATE `xcolab_Contest` SET `ContestShortName`='Shifting cultures for a changing climate' WHERE `ContestPK`='21';
UPDATE `xcolab_Contest` SET `ContestShortName`='Enabling adaptation' WHERE `ContestPK`='22';
UPDATE `xcolab_Contest` SET `ContestShortName`='Scaling renewables in major emerging economies' WHERE `ContestPK`='23';
UPDATE `xcolab_Contest` SET `ContestShortName`='Replacing diesel generation' WHERE `ContestPK`='24';
UPDATE `xcolab_Contest` SET `ContestShortName`='Reducing consumption' WHERE `ContestPK`='25';
UPDATE `xcolab_Contest` SET `ContestShortName`='Waste management' WHERE `ContestPK`='26';
UPDATE `xcolab_Contest` SET `ContestShortName`='Hydraulic fracturing (fracking)' WHERE `ContestPK`='30';
UPDATE `xcolab_Contest` SET `ContestShortName`='Energy Supply' WHERE `ContestPK`='1300201';
UPDATE `xcolab_Contest` SET `ContestShortName`='Transportation' WHERE `ContestPK`='1300202';
UPDATE `xcolab_Contest` SET `ContestShortName`='Buildings' WHERE `ContestPK`='1300203';
UPDATE `xcolab_Contest` SET `ContestShortName`='Industry' WHERE `ContestPK`='1300204';
UPDATE `xcolab_Contest` SET `ContestShortName`='Waste Management' WHERE `ContestPK`='1300206';
UPDATE `xcolab_Contest` SET `ContestShortName`='Adaptation to Climate Change' WHERE `ContestPK`='1300208';
UPDATE `xcolab_Contest` SET `ContestShortName`='Geoengineering' WHERE `ContestPK`='1300209';
UPDATE `xcolab_Contest` SET `ContestShortName`='Shifting behavior for a changing climate' WHERE `ContestPK`='1300210';
UPDATE `xcolab_Contest` SET `ContestShortName`='U.S. Government' WHERE `ContestPK`='1300401';
UPDATE `xcolab_Contest` SET `ContestShortName`='Crowdsourcing for Disaster Risk Management' WHERE `ContestPK`='1300402';
UPDATE `xcolab_Contest` SET `ContestShortName`='Creating public demand for green buildings' WHERE `ContestPK`='1300403';
UPDATE `xcolab_Contest` SET `ContestShortName`='U.S. Carbon Price' WHERE `ContestPK`='1300404';
UPDATE `xcolab_Contest` SET `ContestShortName`='Urban Resilience: Climate Actions for Urban Areas' WHERE `ContestPK`='1300501';
UPDATE `xcolab_Contest` SET `ContestShortName`='Global plan' WHERE `ContestPK`='1300701';
UPDATE `xcolab_Contest` SET `ContestShortName`='Communicating Coastal Risk and Resilience' WHERE `ContestPK`='1300801';
UPDATE `xcolab_Contest` SET `ContestShortName`='Youth action on climate change' WHERE `ContestPK`='1300901';
UPDATE `xcolab_Contest` SET `ContestShortName`='Urban Heat Island Effect' WHERE `ContestPK`='1301101';
UPDATE `xcolab_Contest` SET `ContestShortName`='Anticipating Climate Change in the Pamir Mountains' WHERE `ContestPK`='1301102';
UPDATE `xcolab_Contest` SET `ContestShortName`='Atypical Ideas for Carbon Neutrality' WHERE `ContestPK`='1301402';
UPDATE `xcolab_Contest` SET `ContestShortName`='Energy solutions for Latin America' WHERE `ContestPK`='1301408';
UPDATE `xcolab_Contest` SET `ContestShortName`='Adaptation' WHERE `ContestPK`='1301411';
UPDATE `xcolab_Contest` SET `ContestShortName`='Buildings' WHERE `ContestPK`='1301412';
UPDATE `xcolab_Contest` SET `ContestShortName`='Energy Supply' WHERE `ContestPK`='1301413';
UPDATE `xcolab_Contest` SET `ContestShortName`='Industry' WHERE `ContestPK`='1301415';
UPDATE `xcolab_Contest` SET `ContestShortName`='Land Use: Agriculture, Forestry, Livestock' WHERE `ContestPK`='1301416';
UPDATE `xcolab_Contest` SET `ContestShortName`='Transportation' WHERE `ContestPK`='1301418';
UPDATE `xcolab_Contest` SET `ContestShortName`='U.S. Carbon Price' WHERE `ContestPK`='1301419';
UPDATE `xcolab_Contest` SET `ContestShortName`='Waste Management' WHERE `ContestPK`='1301420';
UPDATE `xcolab_Contest` SET `ContestShortName`='Energy-Water Nexus' WHERE `ContestPK`='1301501';
UPDATE `xcolab_Contest` SET `ContestShortName`='Rural resilience' WHERE `ContestPK`='1301502';
UPDATE `xcolab_Contest` SET `ContestShortName`='Urban Energy Efficiency' WHERE `ContestPK`='1301603';
UPDATE `xcolab_Contest` SET `ContestShortName`='United States’ Climate Action Plan' WHERE `ContestPK`='1302001';
UPDATE `xcolab_Contest` SET `ContestShortName`='Europe’s Climate Action Plan' WHERE `ContestPK`='1302007';
UPDATE `xcolab_Contest` SET `ContestShortName`='China’s Climate Action Plan' WHERE `ContestPK`='1302013';
UPDATE `xcolab_Contest` SET `ContestShortName`='India’s Climate Action Plan' WHERE `ContestPK`='1302019';
UPDATE `xcolab_Contest` SET `ContestShortName`='Other Developed Countries’ Climate Action Plan' WHERE `ContestPK`='1302025';
UPDATE `xcolab_Contest` SET `ContestShortName`='Other Developing Countries’ Climate Action Plan' WHERE `ContestPK`='1302031';
UPDATE `xcolab_Contest` SET `ContestShortName`='Improving firewood for clean cookstoves' WHERE `ContestPK`='1302301';
UPDATE `xcolab_Contest` SET `ContestShortName`='Materials Matter' WHERE `ContestPK`='1302601';
UPDATE `xcolab_Contest` SET `ContestShortName`='Designing High Density Urban Bike Parking' WHERE `ContestPK`='1302902';
UPDATE `xcolab_Contest` SET `ContestShortName`='Fostering Climate Collaboration in Boulder, CO' WHERE `ContestPK`='1302903';
UPDATE `xcolab_Contest` SET `ContestShortName`='Harnessing the power of MIT alumni' WHERE `ContestPK`='1303301';
UPDATE `xcolab_Contest` SET `ContestShortName`='Buildings' WHERE `ContestPK`='1303801';
UPDATE `xcolab_Contest` SET `ContestShortName`='The Smart Zero Carbon Cities Challenge' WHERE `ContestPK`='1303802';
UPDATE `xcolab_Contest` SET `ContestShortName`='Transportation' WHERE `ContestPK`='1303901';
UPDATE `xcolab_Contest` SET `ContestShortName`='Adaptation' WHERE `ContestPK`='1303902';
UPDATE `xcolab_Contest` SET `ContestShortName`='Industry' WHERE `ContestPK`='1303903';
UPDATE `xcolab_Contest` SET `ContestShortName`='Shifting Behavior for a Changing Climate' WHERE `ContestPK`='1303904';
UPDATE `xcolab_Contest` SET `ContestShortName`='Energy Supply' WHERE `ContestPK`='1303905';
UPDATE `xcolab_Contest` SET `ContestShortName`='Waste Management' WHERE `ContestPK`='1303906';
UPDATE `xcolab_Contest` SET `ContestShortName`='Land Use: Agriculture, Forestry, Livestock' WHERE `ContestPK`='1303907';
UPDATE `xcolab_Contest` SET `ContestShortName`='Aviation' WHERE `ContestPK`='1303908';
UPDATE `xcolab_Contest` SET `ContestShortName`='MIT Climate Mitigation Solutions' WHERE `ContestPK`='1303909';
UPDATE `xcolab_Contest` SET `ContestShortName`='Energy Water Nexus' WHERE `ContestPK`='1304101';
UPDATE `xcolab_Contest` SET `ContestShortName`='Anticipating Climate Hazards' WHERE `ContestPK`='1304501';
