package com.ext.portlet.ontology.model;

import com.liferay.portal.model.AttachedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the OntologyTermEntity service. Represents a row in the &quot;xcolab_OntologyTermEntity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ext.portlet.ontology.model.impl.OntologyTermEntityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ext.portlet.ontology.model.impl.OntologyTermEntityImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OntologyTermEntity
 * @see com.ext.portlet.ontology.model.impl.OntologyTermEntityImpl
 * @see com.ext.portlet.ontology.model.impl.OntologyTermEntityModelImpl
 * @generated
 */
public interface OntologyTermEntityModel extends AttachedModel,
    BaseModel<OntologyTermEntity> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a ontology term entity model instance should use the {@link OntologyTermEntity} interface instead.
     */

    /**
     * Returns the primary key of this ontology term entity.
     *
     * @return the primary key of this ontology term entity
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this ontology term entity.
     *
     * @param primaryKey the primary key of this ontology term entity
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the ID of this ontology term entity.
     *
     * @return the ID of this ontology term entity
     */
    public long getId();

    /**
     * Sets the ID of this ontology term entity.
     *
     * @param id the ID of this ontology term entity
     */
    public void setId(long id);

    /**
     * Returns the term ID of this ontology term entity.
     *
     * @return the term ID of this ontology term entity
     */
    public long getTermId();

    /**
     * Sets the term ID of this ontology term entity.
     *
     * @param termId the term ID of this ontology term entity
     */
    public void setTermId(long termId);

    /**
     * Returns the fully qualified class name of this ontology term entity.
     *
     * @return the fully qualified class name of this ontology term entity
     */
    public String getClassName();

    /**
     * Returns the class name ID of this ontology term entity.
     *
     * @return the class name ID of this ontology term entity
     */
    public long getClassNameId();

    /**
     * Sets the class name ID of this ontology term entity.
     *
     * @param classNameId the class name ID of this ontology term entity
     */
    public void setClassNameId(long classNameId);

    /**
     * Returns the class p k of this ontology term entity.
     *
     * @return the class p k of this ontology term entity
     */
    public long getClassPK();

    /**
     * Sets the class p k of this ontology term entity.
     *
     * @param classPK the class p k of this ontology term entity
     */
    public void setClassPK(long classPK);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(OntologyTermEntity ontologyTermEntity);

    public int hashCode();

    public CacheModel<OntologyTermEntity> toCacheModel();

    public OntologyTermEntity toEscapedModel();

    public String toString();

    public String toXmlString();
}
