CREATE INDEX xcolab_TrackedVisit_createDate_index ON xcolab_TrackedVisit (createDate DESC);
CREATE INDEX xcolab_TrackedVisitor2User_createDate_index ON xcolab_TrackedVisitor2User (createDate DESC);
CREATE INDEX xcolab_TrackedVisitor2User_userId_index ON xcolab_TrackedVisitor2User (userId);
