/**
 * This class is generated by jOOQ
 */
package org.xcolab.client.contest.pojo;


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.springframework.core.ParameterizedTypeReference;
import org.xcolab.util.http.client.types.TypeProvider;

import javax.annotation.Generated;
import java.io.Serializable;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContestType implements Serializable {

    public static final TypeProvider<ContestType> TYPES =
            new TypeProvider<>(ContestType.class,
                    new ParameterizedTypeReference<List<ContestType>>() {
                    });

    private static final long serialVersionUID = -816986355;

    private Long    id_;
    private String  contestname;
    private String  contestnameplural;
    private String  proposalname;
    private String  proposalnameplural;
    private String  portletname;
    private String  portleturl;
    private String  friendlyurlstringcontests;
    private String  friendlyurlstringproposal;
    private String  menuitemname;
    private Boolean hasdiscussion;
    private Long    suggestioncontestid;
    private String  rulespagename;
    private String  rulespageurl;

    public ContestType() {}

    public ContestType(ContestType value) {
        this.id_ = value.id_;
        this.contestname = value.contestname;
        this.contestnameplural = value.contestnameplural;
        this.proposalname = value.proposalname;
        this.proposalnameplural = value.proposalnameplural;
        this.portletname = value.portletname;
        this.portleturl = value.portleturl;
        this.friendlyurlstringcontests = value.friendlyurlstringcontests;
        this.friendlyurlstringproposal = value.friendlyurlstringproposal;
        this.menuitemname = value.menuitemname;
        this.hasdiscussion = value.hasdiscussion;
        this.suggestioncontestid = value.suggestioncontestid;
        this.rulespagename = value.rulespagename;
        this.rulespageurl = value.rulespageurl;
    }

    public ContestType(
        Long    id_,
        String  contestname,
        String  contestnameplural,
        String  proposalname,
        String  proposalnameplural,
        String  portletname,
        String  portleturl,
        String  friendlyurlstringcontests,
        String  friendlyurlstringproposal,
        String  menuitemname,
        Boolean hasdiscussion,
        Long    suggestioncontestid,
        String  rulespagename,
        String  rulespageurl
    ) {
        this.id_ = id_;
        this.contestname = contestname;
        this.contestnameplural = contestnameplural;
        this.proposalname = proposalname;
        this.proposalnameplural = proposalnameplural;
        this.portletname = portletname;
        this.portleturl = portleturl;
        this.friendlyurlstringcontests = friendlyurlstringcontests;
        this.friendlyurlstringproposal = friendlyurlstringproposal;
        this.menuitemname = menuitemname;
        this.hasdiscussion = hasdiscussion;
        this.suggestioncontestid = suggestioncontestid;
        this.rulespagename = rulespagename;
        this.rulespageurl = rulespageurl;
    }

    public Long getId_() {
        return this.id_;
    }

    public void setId_(Long id_) {
        this.id_ = id_;
    }

    public String getContestName() {
        return this.contestname;
    }

    public void setContestName(String contestname) {
        this.contestname = contestname;
    }

    public String getContestNamePlural() {
        return this.contestnameplural;
    }

    public void setContestNamePlural(String contestnameplural) {
        this.contestnameplural = contestnameplural;
    }

    public String getProposalName() {
        return this.proposalname;
    }

    public void setProposalName(String proposalname) {
        this.proposalname = proposalname;
    }

    public String getProposalNamePlural() {
        return this.proposalnameplural;
    }

    public void setProposalNamePlural(String proposalnameplural) {
        this.proposalnameplural = proposalnameplural;
    }

    public String getPortletName() {
        return this.portletname;
    }

    public void setPortletName(String portletname) {
        this.portletname = portletname;
    }

    public String getPortletUrl() {
        return this.portleturl;
    }

    public void setPortletUrl(String portleturl) {
        this.portleturl = portleturl;
    }

    public String getFriendlyUrlStringContests() {
        return this.friendlyurlstringcontests;
    }

    public void setFriendlyUrlStringContests(String friendlyurlstringcontests) {
        this.friendlyurlstringcontests = friendlyurlstringcontests;
    }

    public String getFriendlyUrlStringProposal() {
        return this.friendlyurlstringproposal;
    }

    public void setFriendlyUrlStringProposal(String friendlyurlstringproposal) {
        this.friendlyurlstringproposal = friendlyurlstringproposal;
    }

    public String getMenuItemName() {
        return this.menuitemname;
    }

    public void setMenuItemName(String menuitemname) {
        this.menuitemname = menuitemname;
    }

    public Boolean getHasDiscussion() {
        return this.hasdiscussion;
    }

    public void setHasDiscussion(Boolean hasdiscussion) {
        this.hasdiscussion = hasdiscussion;
    }

    public Long getSuggestionContestId() {
        return this.suggestioncontestid;
    }

    public void setSuggestionContestId(Long suggestioncontestid) {
        this.suggestioncontestid = suggestioncontestid;
    }

    public String getRulesPageName() {
        return this.rulespagename;
    }

    public void setRulesPageName(String rulespagename) {
        this.rulespagename = rulespagename;
    }

    public String getRulesPageUrl() {
        return this.rulespageurl;
    }

    public void setRulesPageUrl(String rulespageurl) {
        this.rulespageurl = rulespageurl;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ContestType other = (ContestType) obj;
        if (id_ == null) {
            if (other.id_ != null)
                return false;
        }
        else if (!id_.equals(other.id_))
            return false;
        if (contestname == null) {
            if (other.contestname != null)
                return false;
        }
        else if (!contestname.equals(other.contestname))
            return false;
        if (contestnameplural == null) {
            if (other.contestnameplural != null)
                return false;
        }
        else if (!contestnameplural.equals(other.contestnameplural))
            return false;
        if (proposalname == null) {
            if (other.proposalname != null)
                return false;
        }
        else if (!proposalname.equals(other.proposalname))
            return false;
        if (proposalnameplural == null) {
            if (other.proposalnameplural != null)
                return false;
        }
        else if (!proposalnameplural.equals(other.proposalnameplural))
            return false;
        if (portletname == null) {
            if (other.portletname != null)
                return false;
        }
        else if (!portletname.equals(other.portletname))
            return false;
        if (portleturl == null) {
            if (other.portleturl != null)
                return false;
        }
        else if (!portleturl.equals(other.portleturl))
            return false;
        if (friendlyurlstringcontests == null) {
            if (other.friendlyurlstringcontests != null)
                return false;
        }
        else if (!friendlyurlstringcontests.equals(other.friendlyurlstringcontests))
            return false;
        if (friendlyurlstringproposal == null) {
            if (other.friendlyurlstringproposal != null)
                return false;
        }
        else if (!friendlyurlstringproposal.equals(other.friendlyurlstringproposal))
            return false;
        if (menuitemname == null) {
            if (other.menuitemname != null)
                return false;
        }
        else if (!menuitemname.equals(other.menuitemname))
            return false;
        if (hasdiscussion == null) {
            if (other.hasdiscussion != null)
                return false;
        }
        else if (!hasdiscussion.equals(other.hasdiscussion))
            return false;
        if (suggestioncontestid == null) {
            if (other.suggestioncontestid != null)
                return false;
        }
        else if (!suggestioncontestid.equals(other.suggestioncontestid))
            return false;
        if (rulespagename == null) {
            if (other.rulespagename != null)
                return false;
        }
        else if (!rulespagename.equals(other.rulespagename))
            return false;
        if (rulespageurl == null) {
            if (other.rulespageurl != null)
                return false;
        }
        else if (!rulespageurl.equals(other.rulespageurl))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((id_ == null) ? 0 : id_.hashCode());
        result = prime * result + ((contestname == null) ? 0 : contestname.hashCode());
        result = prime * result + ((contestnameplural == null) ? 0 : contestnameplural.hashCode());
        result = prime * result + ((proposalname == null) ? 0 : proposalname.hashCode());
        result = prime * result + ((proposalnameplural == null) ? 0 : proposalnameplural.hashCode());
        result = prime * result + ((portletname == null) ? 0 : portletname.hashCode());
        result = prime * result + ((portleturl == null) ? 0 : portleturl.hashCode());
        result = prime * result + ((friendlyurlstringcontests == null) ? 0 : friendlyurlstringcontests.hashCode());
        result = prime * result + ((friendlyurlstringproposal == null) ? 0 : friendlyurlstringproposal.hashCode());
        result = prime * result + ((menuitemname == null) ? 0 : menuitemname.hashCode());
        result = prime * result + ((hasdiscussion == null) ? 0 : hasdiscussion.hashCode());
        result = prime * result + ((suggestioncontestid == null) ? 0 : suggestioncontestid.hashCode());
        result = prime * result + ((rulespagename == null) ? 0 : rulespagename.hashCode());
        result = prime * result + ((rulespageurl == null) ? 0 : rulespageurl.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ContestType (");

        sb.append(id_);
        sb.append(", ").append(contestname);
        sb.append(", ").append(contestnameplural);
        sb.append(", ").append(proposalname);
        sb.append(", ").append(proposalnameplural);
        sb.append(", ").append(portletname);
        sb.append(", ").append(portleturl);
        sb.append(", ").append(friendlyurlstringcontests);
        sb.append(", ").append(friendlyurlstringproposal);
        sb.append(", ").append(menuitemname);
        sb.append(", ").append(hasdiscussion);
        sb.append(", ").append(suggestioncontestid);
        sb.append(", ").append(rulespagename);
        sb.append(", ").append(rulespageurl);

        sb.append(")");
        return sb.toString();
    }
}
