/**
 * This class is generated by jOOQ
 */
package org.xcolab.client.contest.pojo;


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;

import org.springframework.core.ParameterizedTypeReference;
import org.xcolab.util.http.client.types.TypeProvider;

import java.io.Serializable;
import java.util.List;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ImpactDefaultSeriesData implements Serializable {

    public static final TypeProvider<ImpactDefaultSeriesData> TYPES =
            new TypeProvider<>(ImpactDefaultSeriesData.class,
                    new ParameterizedTypeReference<List<ImpactDefaultSeriesData>>() {
                    });
    private static final long serialVersionUID = -106036424;

    private Long    seriesid;
    private Integer year;
    private Double  value;

    public ImpactDefaultSeriesData() {}

    public ImpactDefaultSeriesData(ImpactDefaultSeriesData value) {
        this.seriesid = value.seriesid;
        this.year = value.year;
        this.value = value.value;
    }

    public ImpactDefaultSeriesData(
        Long    seriesid,
        Integer year,
        Double  value
    ) {
        this.seriesid = seriesid;
        this.year = year;
        this.value = value;
    }

    public Long getSeriesId() {
        return this.seriesid;
    }

    public void setSeriesId(Long seriesid) {
        this.seriesid = seriesid;
    }

    public Integer getYear() {
        return this.year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

    public Double getValue() {
        return this.value;
    }

    public void setValue(Double value) {
        this.value = value;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ImpactDefaultSeriesData other = (ImpactDefaultSeriesData) obj;
        if (seriesid == null) {
            if (other.seriesid != null)
                return false;
        }
        else if (!seriesid.equals(other.seriesid))
            return false;
        if (year == null) {
            if (other.year != null)
                return false;
        }
        else if (!year.equals(other.year))
            return false;
        if (value == null) {
            if (other.value != null)
                return false;
        }
        else if (!value.equals(other.value))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((seriesid == null) ? 0 : seriesid.hashCode());
        result = prime * result + ((year == null) ? 0 : year.hashCode());
        result = prime * result + ((value == null) ? 0 : value.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ImpactDefaultSeriesData (");

        sb.append(seriesid);
        sb.append(", ").append(year);
        sb.append(", ").append(value);

        sb.append(")");
        return sb.toString();
    }
}
