/**
 * This class is generated by jOOQ
 */
package org.xcolab.client.contest.pojo;


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;

import org.springframework.core.ParameterizedTypeReference;
import org.xcolab.util.http.client.types.TypeProvider;

import java.io.Serializable;
import java.util.List;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ImpactTemplateMaxFocusArea implements Serializable {

    private static final long serialVersionUID = 1276248760;

    public static final TypeProvider<ImpactTemplateMaxFocusArea> TYPES =
            new TypeProvider<>(ImpactTemplateMaxFocusArea.class,
                    new ParameterizedTypeReference<List<ImpactTemplateMaxFocusArea>>() {
                    });

    private Long focusarealistid;
    private Long focusareaid;

    public ImpactTemplateMaxFocusArea() {}

    public ImpactTemplateMaxFocusArea(ImpactTemplateMaxFocusArea value) {
        this.focusarealistid = value.focusarealistid;
        this.focusareaid = value.focusareaid;
    }

    public ImpactTemplateMaxFocusArea(
        Long focusarealistid,
        Long focusareaid
    ) {
        this.focusarealistid = focusarealistid;
        this.focusareaid = focusareaid;
    }

    public Long getFocusAreaListId() {
        return this.focusarealistid;
    }

    public void setFocusAreaListId(Long focusarealistid) {
        this.focusarealistid = focusarealistid;
    }

    public Long getFocusAreaId() {
        return this.focusareaid;
    }

    public void setFocusAreaId(Long focusareaid) {
        this.focusareaid = focusareaid;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ImpactTemplateMaxFocusArea other = (ImpactTemplateMaxFocusArea) obj;
        if (focusarealistid == null) {
            if (other.focusarealistid != null)
                return false;
        }
        else if (!focusarealistid.equals(other.focusarealistid))
            return false;
        if (focusareaid == null) {
            if (other.focusareaid != null)
                return false;
        }
        else if (!focusareaid.equals(other.focusareaid))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((focusarealistid == null) ? 0 : focusarealistid.hashCode());
        result = prime * result + ((focusareaid == null) ? 0 : focusareaid.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ImpactTemplateMaxFocusArea (");

        sb.append(focusarealistid);
        sb.append(", ").append(focusareaid);

        sb.append(")");
        return sb.toString();
    }
}
