package com.ext.portlet.plans;

public enum PlanTeamActions {
    MEMBERSHIP_REQUESTED,
    MEMBERSHIP_APPROVED,
    MEMBERSHIP_DECLEINED,
    MEMBERSHIP_RESIGNED, 
    PERMISSIONS_CHANGED, 
    MEMBER_REMOVED
}
